'use client';
import {ListPagination,useListPage} from '@/components/list-pagination';
import {useConfirmation} from '@/components/use-confirmation';
import {useEffect,useRef,useState} from 'react';
import {Wrench,Plus,RefreshCw,Package,CalendarDays,Settings2,ClipboardList,Activity,ArrowRight,ExternalLink,CheckCircle2,AlertTriangle,Clock,Search} from 'lucide-react';
import {HubFrame,hubRequest,useHubMeta} from '@/components/hub-layout';
import {SearchSelect} from '@/components/search-select';
import {MetricChart,chartModes} from '@/components/metric-chart';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AccountGate,type Account} from '@/components/account-gate';
import {newAsset,newOrder,newPlan,newPart,orderStatuses,orderPriorities,assetStatuses,finishedOrder,planDates,type GmaoRow,type GmaoAsset,type GmaoOrder,type GmaoPlan,type GmaoPart} from '@/lib/gmao';
import {todayParis} from '@/lib/hub';
import '../unites/style.css';
import '../tickets/tickets.css';
import './style.css';
type Payload={assets:GmaoRow<GmaoAsset>[];orders:GmaoRow<GmaoOrder>[];plans:GmaoRow<GmaoPlan>[];parts:GmaoRow<GmaoPart>[];technicians:{id:string;display_name:string}[];manage:boolean;maintenanceRead:boolean;editableTeams:string[];today:string};
type Kind='order'|'asset'|'plan'|'part'|'request'|'stock';
type Edit={kind:Kind;id:string;revision:number;data:any;quantity?:number;history:any[];movements:any[]};
const tabs=[['overview','Vue d’ensemble',Activity],['orders','Interventions',ClipboardList],['assets','Équipements',Settings2],['plans','Préventif',Wrench],['planning','Planning',CalendarDays],['parts','Pièces & stocks',Package]] as const;
const nextSteps:Record<string,string[]>={'À qualifier':['À planifier','Annulée'],'À planifier':['Planifiée','En cours','Annulée'],'Planifiée':['En cours','À planifier','Annulée'],'En cours':['En attente','À vérifier','Annulée'],'En attente':['En cours','Annulée'],'À vérifier':['Clôturée','En cours']};
const date=(s:string)=>s?new Date(s+'T12:00:00').toLocaleDateString('fr-FR'):'Non renseignée';
const norm=(s:string)=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();
const numeric=(s:string)=>s===''?null:Number(s);
const money=(n:number|null)=>n===null?'Coût non renseigné':n.toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const later=(days:number)=>{const d=new Date(todayParis()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
function Badge({value}:{value:string}){return <span className="gmao-badge" data-value={value}>{value}</span>}
function Select({label,value,options,onChange,disabled=false}:{label:string;value:string;options:string[];onChange:(s:string)=>void;disabled?:boolean}){return <label>{label}<select disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
export default function Page(){return <AccountGate>{account=><Maintenance account={account}/>}</AccountGate>}
function Maintenance({account}:{account:Account}){const {askConfirm,confirmation}=useConfirmation();
const {meta}=useHubMeta(),[data,setData]=useState<Payload|null>(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[detailLoading,setDetailLoading]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[assetFilter,setAssetFilter]=useState(''),[focus,setFocus]=useState('all'),[page,setPage]=useState(1),[edit,setEdit]=useState<Edit|null>(null),[baseline,setBaseline]=useState(''),[modalError,setModalError]=useState(''),[note,setNote]=useState(''),[pane,setPane]=useState('details'),[chart,setChart]=useState<'bar'|'pie'|'donut'|'line'>('bar'),[from,setFrom]=useState(todayParis()),[to,setTo]=useState(later(30)),[ticket,setTicket]=useState(''),[docs,setDocs]=useState<{id:string;name:string}[]>([]);
const sequence=useRef(0),listSequence=useRef(0),initialized=useRef(false),dirty=!!edit&&(JSON.stringify(edit.data)!==baseline||!!note),manage=!!data?.manage;
async function load(){const n=++listSequence.current;setLoading(true);try{const d=await hubRequest('/api/gmao');if(n===listSequence.current){setData(d);setError('')}return d as Payload}catch(e){if(n===listSequence.current)setError((e as Error).message)}finally{if(n===listSequence.current)setLoading(false)}}
async function open(kind:Kind,id:string){const n=++sequence.current;setDetailLoading(true);setModalError('');setNote('');setPane('details');try{const d=await hubRequest('/api/gmao?kind='+kind+'&id='+encodeURIComponent(id));if(n!==sequence.current)return;setEdit({kind,...d.row,history:d.history,movements:d.movements});setBaseline(JSON.stringify(d.row.data));history.replaceState(null,'','/maintenance?tab='+tab+'&'+kind+'='+encodeURIComponent(id))}catch(e){setError((e as Error).message)}finally{if(n===sequence.current)setDetailLoading(false)}}
useEffect(()=>{if(initialized.current)return;initialized.current=true;const q=new URLSearchParams(location.search);if(tabs.some(t=>t[0]===q.get('tab')))setTab(q.get('tab')!);load().then(d=>{if(!d)return;for(const k of ['order','asset','plan','part'] as Kind[])if(q.get(k)){open(k,q.get(k)!);return}if(q.has('new')&&account.role!=='reader'&&d.editableTeams.length){setEdit({kind:'request',id:'',revision:0,data:{...newOrder(),teamId:d.editableTeams.includes('production')?'production':d.editableTeams[0]},history:[],movements:[]});setBaseline('');return}if(q.get('ticket')&&d.manage){setTicket(q.get('ticket')!);hubRequest('/api/hub?scope=ticket&id='+encodeURIComponent(q.get('ticket')!)).then(t=>{const v={...newOrder(),title:t.ticket.data.title,description:t.ticket.data.description||t.ticket.data.title,teamId:t.ticket.data.teams.find((id:string)=>id!=='maintenance')||'maintenance'};setEdit({kind:'request',id:'',revision:0,data:v,history:[],movements:[]});setBaseline('')}).catch(e=>setError(e.message))}})},[]);
useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
useEffect(()=>{setPage(1)},[tab,search,filter,assetFilter,focus]);
useEffect(()=>{if(edit?.kind!=='asset'||!manage)return;let live=true;hubRequest('/api/ged').then(d=>{if(live)setDocs((d.documents||d.rows||[]).map((r:any)=>({id:r.id,name:(r.ref?r.ref+' · ':'')+(r.title||r.name||r.id)})))}).catch(()=>{if(live)setModalError('Le catalogue GED ne peut pas être chargé. Le lien existant est conservé ; rechargez la fiche pour réessayer.')});return()=>{live=false}},[edit?.kind,manage]);
function create(kind:Kind,values:any={}){sequence.current++;setTicket('');setNote('');setPane('details');setModalError('');const value=kind==='request'?{...newOrder(),teamId:data?.editableTeams.includes('production')?'production':data?.editableTeams[0]||''}:kind==='asset'?newAsset():kind==='plan'?{...newPlan(),start:todayParis()}:kind==='part'?newPart():{partId:'',orderId:'',kind:'Entrée',amount:null,note:''};setEdit({kind,id:'',revision:0,data:{...value,...values},quantity:kind==='part'?0:undefined,history:[],movements:[]});setBaseline('')}
async function close(){if(busy)return;if(dirty&&!await askConfirm('Fermer sans enregistrer les modifications ?'))return;sequence.current++;setEdit(null);setNote('');setTicket('');setModalError('');history.replaceState(null,'','/maintenance?tab='+tab)}
function patch(v:any){setEdit(e=>e&&({...e,data:{...e.data,...v}}))}
async function save(){if(!edit||!data)return;setBusy(true);setModalError('');try{let result:any;if(edit.kind==='stock'){const p=data.parts.find(p=>p.id===edit.data.partId);if(!p)throw Error('Choisissez une pièce.');result=await hubRequest('/api/gmao',{operation:'stock',...edit.data,revision:p.revision});await open(edit.data.kind==='Sortie intervention'?'order':'part',edit.data.kind==='Sortie intervention'?edit.data.orderId:edit.data.partId);setNotice('Mouvement enregistré. Le stock a été mis à jour.')}else{result=await hubRequest('/api/gmao',{operation:edit.kind==='request'?(ticket?'from-ticket':'request'):edit.kind,id:edit.id,revision:edit.revision,data:edit.kind==='plan'?{...edit.data,tasks:edit.data.tasks.filter((s:string)=>s.trim())}:edit.data,quantity:edit.quantity,ticketId:ticket||undefined});await open(edit.kind==='request'?'order':edit.kind,result.id);setNotice('Enregistrement confirmé.')}await load()}catch(e){setModalError((e as Error).message)}finally{setBusy(false)}}
async function transition(toStatus:string,operation='transition'){if(!edit)return;setBusy(true);setModalError('');try{await hubRequest('/api/gmao',{operation,id:edit.id,revision:edit.revision,to:toStatus,note});await open('order',edit.id);await load();setNotice('Intervention mise à jour.')}catch(e){setModalError((e as Error).message)}finally{setBusy(false)}}
async function generate(planId?:string){setBusy(true);setError('');try{const d=await hubRequest('/api/gmao',{operation:'generate',from,to,planId});setNotice(`${d.created} intervention(s) créée(s), ${d.existing} déjà existante(s).${d.limited?' Limite atteinte : relancez sur une période plus courte.':''}`);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function changeTab(value:string){setTab(value);setSearch('');setFilter('');setFocus('all');setAssetFilter('');history.replaceState(null,'','/maintenance?tab='+value)}
const assets=data?.assets||[],orders=data?.orders||[],plans=data?.plans||[],parts=data?.parts||[],today=data?.today||todayParis(),active=orders.filter(r=>!finishedOrder(r.data)),late=active.filter(r=>r.data.due&&r.data.due<today),low=parts.filter(p=>p.data.active&&(p.quantity||0)<=p.data.minimum),assetName=(id:string)=>assets.find(a=>a.id===id)?.data.name||'Sans équipement',techName=(id:string)=>data?.technicians.find(t=>t.id===id)?.display_name||'À attribuer';
const assetOptions=assets.map(a=>({id:a.id,name:a.data.code+' · '+a.data.name})),techOptions=(data?.technicians||[]).map(t=>({id:t.id,name:t.display_name})),teamOptions=meta.teams.filter(t=>manage||data?.editableTeams.includes(t.id)).map(t=>({id:t.id,name:t.name}));
const shownOrders=orders.filter(r=>(!filter||r.data.status===filter)&&(!assetFilter||r.data.assetId===assetFilter)&&(focus==='all'||focus==='active'&&!finishedOrder(r.data)||focus==='late'&&late.some(o=>o.id===r.id)||focus==='verify'&&r.data.status==='À vérifier'||focus==='mine'&&r.data.technicianId===account?.id||focus==='requests'&&r.data.requesterId===account?.id)&&norm(r.data.title+' '+r.data.description+' '+assetName(r.data.assetId)).includes(norm(search))).sort((a,b)=>(a.data.due||'9999').localeCompare(b.data.due||'9999'));
const shownAssets=assets.filter(r=>(!filter||r.data.status===filter)&&norm(r.data.code+' '+r.data.name+' '+r.data.location+' '+r.data.serial).includes(norm(search))),shownPlans=plans.filter(r=>norm(r.data.name+' '+assetName(r.data.assetId)).includes(norm(search))),shownParts=parts.filter(r=>norm(r.data.code+' '+r.data.name+' '+r.data.location).includes(norm(search))&&(!filter||filter==='low'&&low.some(p=>p.id===r.id)));
const rows:any[]=tab==='orders'?shownOrders:tab==='assets'?shownAssets:tab==='plans'?shownPlans:shownParts,pages=Math.max(1,Math.ceil(rows.length/15)),currentPage=Math.min(page,pages),subset=rows.slice((currentPage-1)*15,currentPage*15);
const planning=orders.filter(r=>!finishedOrder(r.data)&&(r.data.scheduled||r.data.due)>=''&&(r.data.scheduled||r.data.due)>=from&&(r.data.scheduled||r.data.due)<=to).map(r=>({date:r.data.scheduled||r.data.due,id:r.id,title:r.data.title,asset:r.data.assetId,status:r.data.status,technician:r.data.technicianId}));
if(data?.maintenanceRead&&from&&to&&to>=from&&Date.parse(to)-Date.parse(from)<=62*86400000)for(const p of plans.filter(p=>p.data.active)){for(const d of planDates(p.data,from,to))if(!orders.some(o=>o.data.planId===p.id&&o.data.occurrence===d)&&assets.find(a=>a.id===p.data.assetId)?.data.status!=='Retiré')planning.push({date:d,id:'',title:p.data.name,asset:p.data.assetId,status:'À générer',technician:p.data.technicianId})}
planning.sort((a,b)=>a.date.localeCompare(b.date));const planningPage=useListPage(planning,JSON.stringify([from,to]),20);
const order=edit?.kind==='order'?edit.data as GmaoOrder:null,ended=order&&finishedOrder(order),canProcess=manage&&!ended,canConfirm=order?.requesterId===account?.id&&account?.role!=='reader'&&order?.status==='À vérifier';
const editField=(key:string,label:string,type='text',required=false)=><label key={key}>{label}<input type={type} required={required} maxLength={key==='name'||key==='title'?200:500} step={type==='number'?'any':undefined} min={type==='number'?0:undefined} value={edit?.data[key]??''} onChange={e=>patch({[key]:type==='number'?numeric(e.target.value):e.target.value})}/></label>;
const textField=(key:string,label:string)=><label>{label}<textarea rows={4} maxLength={key==='description'?10000:5000} value={edit?.data[key]||''} onChange={e=>patch({[key]:e.target.value})}/></label>;
return <HubFrame active="Dashboard" className="gmao-workspace" teamId="maintenance"><div className="gmao-heading"><div><p className="eyebrow">SERVICE MAINTENANCE · GMAO</p><h1><Wrench size={29}/> Maintenance</h1><p>Du signalement au résultat, tout le cycle d’intervention au même endroit.</p></div><div className="gmao-tools"><button className="outline" disabled={busy||loading} onClick={load}><RefreshCw size={16}/> Actualiser</button>{account?.role!=='reader'&&!!data?.editableTeams.length&&<button className="primary" disabled={busy||detailLoading} onClick={()=>create('request')}><Plus size={17}/> Demande d’intervention</button>}</div></div>
<nav className="gmao-tabs" aria-label="GMAO">{tabs.filter(([id])=>data?.maintenanceRead||!['plans','parts'].includes(id)).map(([id,label,Icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>changeTab(id)}><Icon size={17}/>{label}{id==='orders'&&active.length>0&&<small>{active.length}</small>}</button>)}</nav>
{error&&<p className="error" role="alert">{error}<button onClick={load}>Réessayer</button></p>}{notice&&<p className="success" role="status">{notice}</p>}{loading&&!data?<p role="status">Chargement de la GMAO…</p>:data&&<>
{tab==='overview'&&<><div className="gmao-stats">{[['active','À traiter',active.length,ClipboardList],['late','En retard',late.length,Clock],['verify','À vérifier',active.filter(o=>o.data.status==='À vérifier').length,CheckCircle2],['mine','Mes interventions',active.filter(o=>o.data.technicianId===account?.id).length,Wrench]].map(([f,label,count,Icon]:any)=><button key={f} data-tone={f} onClick={()=>{changeTab('orders');setFocus(f)}}><span><Icon size={19}/>{label}</span><strong>{count}</strong><small>Voir les interventions <ArrowRight size={14}/></small></button>)}</div>
{!assets.length&&<section className="gmao-start"><Settings2 size={30}/><div><h2>Construire votre parc d’équipements</h2><p>Ajoutez les équipements réels, leurs emplacements et leurs plans de maintenance. Vous pouvez déjà déclarer une intervention sans équipement.</p></div>{manage&&<button className="primary" onClick={()=>create('asset')}>Ajouter un équipement</button>}</section>}
<div className="gmao-section-head"><h2>Pilotage de la maintenance</h2><label>Graphique<select value={chart} onChange={e=>setChart(e.target.value as any)}>{Object.entries(chartModes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><div className="gmao-charts"><article><h3>Répartition des interventions</h3><MetricChart title="Interventions par étape" mode={chart} accent="#cc742c" points={orderStatuses.map(label=>({label,value:orders.filter(o=>o.data.status===label).length}))} detailsContent={<div className="gmao-detail-links">{active.slice(0,30).map(o=><a key={o.id} href={'/maintenance?order='+o.id}>{o.data.title} · {o.data.status}</a>)}</div>}/></article><article><h3>Correctif et préventif</h3><MetricChart title="Types d’interventions" mode={chart} accent="#087b78" points={['Correctif','Préventif','Amélioration','Contrôle'].map(label=>({label,value:orders.filter(o=>o.data.type===label).length}))} caption="Nombre d’interventions enregistrées, tous états confondus."/></article><article><h3>Heures réalisées par équipement</h3><MetricChart title="Heures réalisées" mode={chart} points={assets.map(a=>({label:a.data.code,value:orders.filter(o=>o.data.assetId===a.id).reduce((s,o)=>s+(o.data.hours||0),0)}))} caption="Heures saisies dans les comptes rendus. Les durées non renseignées ne sont pas estimées." details="Les interventions sans équipement ne sont pas incluses dans ce graphique."/></article></div>
<div className="gmao-columns"><section className="gmao-card"><div className="gmao-section-head"><h2>À surveiller</h2><button onClick={()=>{changeTab('orders');setFocus('late')}}>Tout voir →</button></div>{!late.length&&<p className="gmao-muted">Aucune échéance dépassée.</p>}{late.slice(0,5).map(o=><button className="gmao-mini" key={o.id} onClick={()=>open('order',o.id)}><strong>{o.data.title}</strong><span>{assetName(o.data.assetId)}</span><Badge value={o.data.priority}/><small>Échéance : {date(o.data.due)}</small></button>)}</section><section className="gmao-card"><div className="gmao-section-head"><h2>{data.maintenanceRead?'Stock à réapprovisionner':'Mes demandes'}</h2><button onClick={()=>{changeTab(data.maintenanceRead?'parts':'orders');setFilter(data.maintenanceRead?'low':'');setFocus(data.maintenanceRead?'all':'requests')}}>Tout voir →</button></div>{data.maintenanceRead?<>{!low.length&&<p className="gmao-muted">Aucun seuil atteint dans le stock renseigné.</p>}{low.slice(0,5).map(p=><button className="gmao-mini" key={p.id} onClick={()=>open('part',p.id)}><strong>{p.data.code} · {p.data.name}</strong><Badge value="À réapprovisionner"/><small>{p.quantity} {p.data.unit} · seuil {p.data.minimum}</small></button>)}</>:orders.filter(o=>o.data.requesterId===account?.id).slice(0,5).map(o=><button className="gmao-mini" key={o.id} onClick={()=>open('order',o.id)}><strong>{o.data.title}</strong><Badge value={o.data.status}/></button>)}</section></div><a className="gmao-board-link" href="/unites?team=maintenance"><Settings2 size={17}/> Ouvrir les tableaux personnalisables du service</a></>}
{['orders','assets','plans','parts'].includes(tab)&&<><div className="gmao-section-head"><div><h2>{tabs.find(t=>t[0]===tab)?.[1]}</h2><p>{rows.length} résultat(s){tab==='plans'?' · Les plans définissent les contrôles ; la génération crée les interventions.':''}</p></div>{manage&&tab!=='orders'&&<button className="primary" onClick={()=>create(tab==='assets'?'asset':tab==='plans'?'plan':'part')}><Plus size={16}/>{tab==='assets'?'Nouvel équipement':tab==='plans'?'Nouveau plan':'Nouvelle pièce'}</button>}</div><div className="gmao-filters"><label><Search size={16}/><input aria-label="Rechercher" placeholder="Rechercher par nom, code, emplacement…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{tab==='orders'&&<><select aria-label="Étape" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Toutes les étapes</option>{orderStatuses.map(s=><option key={s}>{s}</option>)}</select><SearchSelect label="Équipement" options={assetOptions} value={assetFilter} onChange={setAssetFilter}/><select aria-label="Vue" value={focus} onChange={e=>setFocus(e.target.value)}>{[['all','Toutes'],['active','À traiter'],['late','En retard'],['verify','À vérifier'],['mine','Mes interventions'],['requests','Mes demandes']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></>}{tab==='assets'&&<select aria-label="État" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tous les états</option>{assetStatuses.map(s=><option key={s}>{s}</option>)}</select>}{tab==='parts'&&<><select aria-label="Stock" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Toutes les pièces</option><option value="low">Seuil atteint</option></select>{manage&&<button className="outline" onClick={()=>create('stock')}>Enregistrer un mouvement</button>}</>}{(search||filter||assetFilter||focus!=='all')&&<button onClick={()=>{setSearch('');setFilter('');setAssetFilter('');setFocus('all')}}>Effacer</button>}</div>
<div className="gmao-list">{subset.map(r=><button className="gmao-row" key={r.id} onClick={()=>open(tab==='orders'?'order':tab==='assets'?'asset':tab==='plans'?'plan':'part',r.id)}>{tab==='orders'?<><span className="gmao-row-icon"><Wrench size={20}/></span><div><strong>{r.data.title}</strong><small>{assetName(r.data.assetId)} · {r.data.type} · {r.data.requester}</small></div><Badge value={r.data.priority}/><span>{techName(r.data.technicianId)}<small className={r.data.due&&r.data.due<today&&!finishedOrder(r.data)?'gmao-late':''}>{date(r.data.due)}</small></span><Badge value={r.data.status}/></>:tab==='assets'?<><span className="gmao-row-icon"><Settings2 size={20}/></span><div><small>{r.data.code} · {r.data.family||'Équipement'}</small><strong>{r.data.name}</strong><small>{r.data.location||'Emplacement à préciser'} · {meta.teams.find(t=>t.id===r.data.teamId)?.name||r.data.teamId}</small></div><Badge value={r.data.criticality}/><span>{orders.filter(o=>o.data.assetId===r.id&&!finishedOrder(o.data)).length} intervention(s) ouverte(s)</span><Badge value={r.data.status}/></>:tab==='plans'?<><span className="gmao-row-icon"><CalendarDays size={20}/></span><div><strong>{r.data.name}</strong><small>{assetName(r.data.assetId)} · {r.data.tasks.length} contrôles</small></div><span>Toutes les {r.data.interval} {r.data.repeat==='weekly'?'semaines':'mois'}<small>Depuis le {date(r.data.start)}</small></span><Badge value={r.data.active?'Actif':'Suspendu'}/></>:<><span className="gmao-row-icon"><Package size={20}/></span><div><small>{r.data.code}</small><strong>{r.data.name}</strong><small>{r.data.location||'Emplacement à préciser'}</small></div><span><strong>{r.quantity} {r.data.unit}</strong><small>Seuil : {r.data.minimum}</small></span><span>{money(r.data.unitCost)}</span><Badge value={!r.data.active?'Inactive':(r.quantity||0)<=r.data.minimum?'À réapprovisionner':'Disponible'}/></>}</button>)}{!rows.length&&<div className="gmao-empty"><Wrench size={30}/><h3>Aucun résultat</h3><p>{search||filter||assetFilter?'Élargissez vos critères de recherche.':tab==='orders'?'Les demandes et les interventions préventives apparaîtront ici.':'Commencez avec vos données réelles pour construire un suivi fiable.'}</p></div>}</div><ListPagination page={currentPage-1} pages={pages} total={rows.length} onChange={p=>setPage(p+1)}/></>}
{tab==='planning'&&<><div className="gmao-section-head"><div><h2>Planning des interventions</h2><p>Les occurrences « À générer » deviennent des interventions après génération. Les interventions existantes gardent leur historique.</p></div></div><div className="gmao-filters"><label>Du<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Au<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{manage&&<button className="primary" disabled={busy||!from||!to} onClick={()=>generate()}>Générer le préventif sur cette période</button>}<small>Fenêtre de 62 jours maximum</small></div>{(!from||!to||to<from||Date.parse(to)-Date.parse(from)>62*86400000)&&<p className="error">Choisissez une période valide de 62 jours maximum.</p>}<div className="gmao-list">{planningPage.rows.map((p,i)=><div className="gmao-planning-row" key={p.id||p.title+p.date+i}><time>{date(p.date)}</time><div><strong>{p.title}</strong><small>{assetName(p.asset)} · {techName(p.technician)}</small></div><Badge value={p.status}/>{p.id?<button className="outline" onClick={()=>open('order',p.id)}>Ouvrir →</button>:<span className="gmao-muted">Prévision</span>}</div>)}{!planning.length&&<div className="gmao-empty">Aucune intervention ou occurrence sur cette période.</div>}{planning.length>200&&<p>200 éléments affichés : réduisez la période.</p>}</div></>}
{tab==='planning'&&<ListPagination page={planningPage.page} pages={planningPage.pages} total={planning.length} onChange={planningPage.setPage}/>}
</>}
{detailLoading&&<p role="status">Chargement de la fiche…</p>}
<Dialog open={!!edit} onOpenChange={v=>{if(!v)close()}}><DialogContent className="gmao-dialog" showCloseButton={!busy}><DialogTitle>{edit?.kind==='request'?(ticket?'Transformer le ticket en intervention':'Nouvelle demande d’intervention'):edit?.kind==='stock'?'Mouvement de stock':edit?.kind==='order'?edit.data.title:edit?.id?'Modifier la fiche':edit?.kind==='asset'?'Nouvel équipement':edit?.kind==='plan'?'Nouveau plan préventif':'Nouvelle pièce détachée'}</DialogTitle><DialogDescription>{edit?.kind==='order'?'Planification, réalisation, contrôle et historique de l’intervention.':edit?.kind==='request'?'Décrivez le constat. La maintenance qualifiera et organisera l’intervention.':'Les modifications sont enregistrées et historisées.'}</DialogDescription>
{modalError&&<p role="alert" className="error">{modalError}</p>}{edit&&<><div className="gmao-dialog-tabs">{[['details','Fiche'],...(edit.id?[['history','Historique']]:[])].map(([id,label])=><button key={id} aria-current={pane===id?'page':undefined} onClick={()=>setPane(id)}>{label}</button>)}</div>{pane==='history'?<div className="gmao-history">{!edit.history.length&&<p>Aucun événement enregistré.</p>}{edit.history.map(h=><article key={h.id}><strong>{h.action}</strong><small>{h.actor} · {new Date(h.created_at).toLocaleString('fr-FR')}</small>{h.note&&<p>{h.note}</p>}<details><summary>Voir la trace enregistrée</summary><pre>{JSON.stringify(JSON.parse(h.snapshot),null,2)}</pre></details></article>)}</div>:<>
{edit.kind==='request'&&<fieldset disabled={busy}><div className="gmao-form"><p className="gmao-tip">Une demande crée un ticket lié : commentaires, photos et documents restent accessibles depuis la fiche d’intervention.</p>{editField('title','Objet de la demande','text',true)}<SearchSelect label="Équipement concerné (facultatif)" options={assetOptions.filter(a=>{const r=assets.find(r=>r.id===a.id);return r?.data.status!=='Retiré'&&(manage||!!r&&data?.editableTeams.includes(r.data.teamId))})} value={edit.data.assetId} onChange={id=>{const a=assets.find(a=>a.id===id);patch({assetId:id,...(a?{teamId:a.data.teamId,location:a.data.location}:{})})}}/><div className="gmao-form-grid"><SearchSelect disabled={!!edit.data.assetId} label="Service concerné" options={teamOptions} value={edit.data.teamId} onChange={teamId=>patch({teamId})}/>{editField('location','Emplacement')}</div>{textField('description','Constat et symptômes')}<div className="gmao-form-grid"><Select label="Priorité demandée" value={edit.data.priority} options={orderPriorities} onChange={priority=>patch({priority})}/>{editField('due','Échéance souhaitée','date')}</div></div></fieldset>}
{order&&<><div className="gmao-order-summary"><Badge value={order.status}/><Badge value={order.priority}/><span>{order.type}</span><span>{assetName(order.assetId)}</span></div><div className="gmao-workflow">{['À qualifier','À planifier','Planifiée','En cours','À vérifier','Clôturée'].map((s,i)=><span key={s} aria-current={order.status===s?'step':undefined}><b>{i+1}</b>{s}</span>)}</div><div className="gmao-context"><p>Demandé par <strong>{order.requester}</strong> · {order.location||'Emplacement non renseigné'}</p><a href={'/tickets?id='+encodeURIComponent(order.ticketId)}><ExternalLink size={16}/> Commentaires, photos & documents du ticket</a>{order.assetId&&<button onClick={async()=>{if(!dirty||await askConfirm('Ouvrir l’équipement sans enregistrer les modifications ?'))open('asset',order.assetId)}}>Voir l’équipement</button>}</div><fieldset disabled={busy||!canProcess}><div className="gmao-form"><h3>1. Demande et qualification</h3>{editField('title','Objet')}{textField('description','Constat')}<Select label="Priorité retenue" options={orderPriorities} value={order.priority} onChange={priority=>patch({priority})}/><h3>2. Planification</h3><SearchSelect label="Technicien responsable" options={techOptions} value={order.technicianId} onChange={technicianId=>patch({technicianId})}/><div className="gmao-form-grid">{editField('scheduled','Date d’intervention prévue','date')}{editField('due','Échéance','date')}</div><h3>3. Réalisation</h3>{textField('safety','Conditions de sécurité et consignation')}{textField('waitReason','Motif d’attente (pièces, arrêt machine, prestataire…)')}{order.checklist.length>0&&<div className="gmao-checklist"><h4>Points de contrôle préventifs</h4>{order.checklist.map(c=><label key={c.id}><input type="checkbox" checked={c.done} onChange={e=>patch({checklist:order.checklist.map(t=>t.id===c.id?{...t,done:e.target.checked}:t)})}/>{c.label}</label>)}</div>}<h3>4. Compte rendu et résultat</h3>{textField('report','Travaux réalisés et cause identifiée')}{textField('result','Résultat et contrôle du fonctionnement')}<div className="gmao-form-grid">{editField('hours','Temps de travail réalisé (h)','number')}{editField('downtimeHours','Temps d’arrêt (h)','number')}{editField('externalCost','Coût externe (€)','number')}</div><small className="gmao-muted">Les valeurs vides restent inconnues. Saisissez 0 uniquement si vous avez confirmé une valeur nulle.</small></div></fieldset>
<section className="gmao-consumption"><div className="gmao-section-head"><h3>Pièces utilisées</h3>{canProcess&&<button disabled={busy||dirty} onClick={()=>create('stock',{kind:'Sortie intervention',orderId:edit.id})}>Sortir une pièce du stock</button>}</div>{!edit.movements.length&&<p className="gmao-muted">Aucune sortie de stock rattachée à cette intervention.</p>}{edit.movements.map(m=><p key={m.id}><strong>{JSON.parse(m.part_data).name}</strong> · {Math.abs(m.delta)} {JSON.parse(m.part_data).unit} · {money(m.unit_cost===null?null:Math.abs(m.delta)*m.unit_cost)}<small>{m.actor} · {new Date(m.created_at).toLocaleString('fr-FR')}</small></p>)}</section>
{(canProcess||canConfirm||manage&&ended)&&<section className="gmao-next"><h3>Faire avancer l’intervention</h3>{JSON.stringify(edit.data)!==baseline&&<p>Enregistrez les champs modifiés avant de changer d’étape.</p>}<label>Motif / confirmation (obligatoire pour clôturer, annuler ou rouvrir)<textarea disabled={busy} rows={2} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="gmao-tools">{(manage&&!ended?nextSteps[order.status]||[]:canConfirm?['Clôturée']:[]).map(s=><button key={s} className={s==='Annulée'?'outline':'primary'} disabled={busy||JSON.stringify(edit.data)!==baseline} onClick={()=>transition(s)}>{s==='Clôturée'?'Confirmer et clôturer':s==='En cours'?'Démarrer / reprendre':s==='À vérifier'?'Soumettre au contrôle':s==='Annulée'?'Annuler l’intervention':s==='À planifier'?'Passer à la planification':'Valider : '+s}</button>)}{manage&&ended&&<button className="outline" disabled={busy||!note.trim()} onClick={()=>transition('','reopen')}>Rouvrir l’intervention</button>}</div></section>}{order.closedAt&&<p>Clôturée le {new Date(order.closedAt).toLocaleString('fr-FR')} par {order.closedBy}.</p>}</>}
{edit.kind==='asset'&&<><fieldset disabled={busy||!manage}><div className="gmao-form"><div className="gmao-form-grid">{editField('code','Code équipement','text',true)}{editField('name','Nom','text',true)}</div><SearchSelect label="Service propriétaire" value={edit.data.teamId} options={teamOptions} onChange={teamId=>patch({teamId})}/><div className="gmao-form-grid">{editField('location','Emplacement')}{editField('family','Famille')}</div><SearchSelect label="Équipement parent (facultatif)" value={edit.data.parentId} options={assetOptions.filter(a=>a.id!==edit.id)} onChange={parentId=>patch({parentId})}/><div className="gmao-form-grid"><Select label="Criticité" value={edit.data.criticality} options={orderPriorities} onChange={criticality=>patch({criticality})}/><Select label="État" value={edit.data.status} options={assetStatuses} onChange={status=>patch({status})}/>{editField('manufacturer','Fabricant')}{editField('model','Modèle')}{editField('serial','N° de série')}</div><SearchSelect label="Document de référence GED" options={docs} value={edit.data.gedId} onChange={gedId=>patch({gedId})}/>{textField('notes','Informations techniques et consignes')}</div></fieldset>{edit.data.gedId&&<a href={'/ged?document='+encodeURIComponent(edit.data.gedId)}>Ouvrir le document de référence GED →</a>}{edit.id&&<section className="gmao-context"><h3>Historique d’interventions de cet équipement</h3>{!orders.some(o=>o.data.assetId===edit.id)&&<p>Aucune intervention enregistrée.</p>}{orders.filter(o=>o.data.assetId===edit.id).map(o=><a key={o.id} href={'/maintenance?order='+o.id}>{o.data.title} · {o.data.status} · {date(o.data.due)}</a>)}{manage&&<div className="gmao-tools"><button className="outline" disabled={dirty||busy} onClick={()=>create('request',{assetId:edit.id,teamId:edit.data.teamId,location:edit.data.location})}>Demander une intervention</button><button className="outline" disabled={dirty||busy} onClick={()=>create('plan',{assetId:edit.id})}>Créer un plan préventif</button></div>}</section>}</>}
{edit.kind==='plan'&&<fieldset disabled={busy||!manage}><div className="gmao-form">{editField('name','Nom du plan','text',true)}<SearchSelect label="Équipement" options={assetOptions} value={edit.data.assetId} onChange={assetId=>patch({assetId})}/><p className="gmao-tip">Après la première génération, le calendrier et l’équipement sont figés. Suspendez le plan et créez-en un nouveau pour les modifier. Les changements de consignes ne modifient pas les interventions déjà créées.</p><div className="gmao-form-grid">{editField('start','Première occurrence','date',true)}{editField('end','Dernière occurrence (facultative)','date')}<label>Récurrence<select value={edit.data.repeat} onChange={e=>patch({repeat:e.target.value})}><option value="weekly">Hebdomadaire</option><option value="monthly">Mensuelle</option></select></label>{editField('interval','Toutes les … semaines / mois','number',true)}<label>État<select value={edit.data.active?'1':'0'} onChange={e=>patch({active:e.target.value==='1'})}><option value="1">Actif</option><option value="0">Suspendu</option></select></label><Select label="Priorité" value={edit.data.priority} options={orderPriorities} onChange={priority=>patch({priority})}/></div><SearchSelect label="Technicien par défaut" options={techOptions} value={edit.data.technicianId} onChange={technicianId=>patch({technicianId})}/>{editField('estimatedHours','Durée prévue (h)','number')}{textField('instructions','Mode opératoire et consignes')}<label>Points de contrôle · un par ligne<textarea rows={6} maxLength={20000} value={edit.data.tasks.join('\n')} onChange={e=>patch({tasks:e.target.value.split('\n')})}/></label></div></fieldset>}
{edit.kind==='part'&&<><fieldset disabled={busy||!manage}><div className="gmao-form"><div className="gmao-form-grid">{editField('code','Référence pièce','text',true)}{editField('name','Désignation','text',true)}{editField('location','Emplacement')}{editField('unit','Unité (pièce, litre, mètre…)','text',true)}{editField('minimum','Seuil de réapprovisionnement','number',true)}{editField('unitCost','Coût unitaire (€)','number')}<label>État<select value={edit.data.active?'1':'0'} onChange={e=>patch({active:e.target.value==='1'})}><option value="1">Active</option><option value="0">Inactive</option></select></label>{!edit.id?<label>Stock initial constaté<input required type="number" min="0" step="any" value={edit.quantity??''} onChange={e=>setEdit({...edit,quantity:e.target.value===''?undefined:Number(e.target.value)})}/></label>:<p className="gmao-stock-count"><strong>{edit.quantity} {edit.data.unit}</strong>Stock actuel · utilisez un mouvement pour le modifier.</p>}</div></div></fieldset>{edit.id&&<><button className="outline" disabled={busy||dirty||!manage||!edit.data.active} onClick={()=>create('stock',{partId:edit.id})}>Enregistrer un mouvement</button><h3>Journal de stock</h3>{edit.movements.map(m=><article className="gmao-movement" key={m.id}><strong>{m.kind} · {m.delta>0?'+':''}{m.delta} · solde {m.quantity_after}</strong><p>{m.note}</p><small>{m.actor} · {new Date(m.created_at).toLocaleString('fr-FR')}</small>{m.order_id&&<a href={'/maintenance?order='+m.order_id}>Intervention liée →</a>}</article>)}</>}</>}
{edit.kind==='stock'&&<fieldset disabled={busy}><div className="gmao-form"><SearchSelect label="Pièce" value={edit.data.partId} options={parts.filter(p=>p.data.active).map(p=>({id:p.id,name:p.data.code+' · '+p.data.name+' · '+p.quantity+' '+p.data.unit}))} onChange={partId=>patch({partId})}/><Select label="Mouvement" options={['Entrée','Sortie intervention','Ajustement']} value={edit.data.kind} onChange={kind=>patch({kind})}/>{editField('amount',edit.data.kind==='Ajustement'?'Stock constaté après inventaire':'Quantité','number',true)}{edit.data.kind==='Ajustement'&&<p className="gmao-tip">Saisissez le stock réellement compté. La différence sera enregistrée avec votre motif.</p>}{edit.data.kind==='Sortie intervention'&&<SearchSelect label="Intervention consommatrice" options={active.map(o=>({id:o.id,name:o.data.title+' · '+assetName(o.data.assetId)}))} value={edit.data.orderId} onChange={orderId=>patch({orderId})}/>}<label>Motif / référence livraison<textarea required maxLength={2000} rows={3} value={edit.data.note} onChange={e=>patch({note:e.target.value})}/></label></div></fieldset>}
</>}
<footer className="gmao-dialog-footer"><small>{dirty?'Saisie non enregistrée':edit.id?'Version '+edit.revision:'Nouvelle fiche'}</small><button className="outline" disabled={busy} onClick={close}>Fermer</button>{edit.id&&<button className="outline" disabled={busy} onClick={async()=>{if(!dirty||await askConfirm("Recharger la fiche et abandonner la saisie en cours ?"))open(edit.kind,edit.id)}}>Recharger la fiche</button>}{pane==='details'&&(edit.kind==='request'||edit.kind==='stock'||manage&&(!order||!ended))&&<button className="primary" disabled={busy||!!edit.id&&JSON.stringify(edit.data)===baseline} onClick={save}>{busy?'Enregistrement…':edit.kind==='request'?'Envoyer la demande':edit.kind==='stock'?'Confirmer le mouvement':'Enregistrer'}</button>}</footer></>}</DialogContent></Dialog>{confirmation}</HubFrame>
}
