import {database} from '@/db/raw';
import {requireRole,checkOrigin} from '@/lib/access';
import {accessibleTeams,teamsAllowed} from '@/lib/team-access';
import {qualityActions} from '@/lib/quality-server';
import {qualitySource} from '@/lib/quality-private-source';
import {blankQualityAction,actionTeam,actionError,priority,effectiveness,type QualityAction} from '@/lib/quality-actions';
import {todayParis,newTicket} from '@/lib/hub';
import {gedDocuments,gedUsers} from '@/lib/ged-server';
const fail=(error:string,status=400)=>Response.json({error},{status});
const ok=(v:unknown)=>Response.json(v,{headers:{'Cache-Control':'private, no-store'}});
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;const all=await qualityActions(),allowed=await accessibleTeams(gate.user!),id=new URL(req.url).searchParams.get('id');if(id){const a=all.get(id);if(!a)return fail('Action introuvable.',404);if(gate.user!.role!=='admin'&&!allowed.has(actionTeam(a)))return fail('Accès au service nécessaire.',403);const history=(await database().prepare('SELECT snapshot,saved_at,saved_by FROM quality_action_history WHERE action_id=? ORDER BY saved_at DESC LIMIT 50').bind(id).all()).results;return ok({action:a,history})}return ok({actions:[...all.values()].filter(a=>gate.user!.role==='admin'||allowed.has(actionTeam(a))).map(({raw,...a})=>a),source:qualitySource.source,services:Object.keys(qualitySource.owners),methods:qualitySource.methods,origins:qualitySource.origins,guide:qualitySource.guide,trace:gate.user!.role==='admin'?qualitySource.trace:[]})}catch(e){console.error(e);return fail('Plan d’actions indisponible.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Origine non autorisée.',403);const gate=await requireRole(req,'editor');if(gate.error)return gate.error;const b=await req.json() as any,all=await qualityActions(),previous=b.id?all.get(b.id):b.operation==='save'?{...blankQualityAction(todayParis()),id:crypto.randomUUID(),parentId:typeof b.parentId==='string'?b.parentId:''}:undefined;if(!previous)return fail('Action introuvable.',404);if(b.id&&!await teamsAllowed(gate.user!,[actionTeam(previous)],true))return fail('Droit de modification du service nécessaire.',403);if(!Number.isInteger(b.revision)||b.revision!==previous.revision)return fail('Cette action a changé. Conservez votre saisie et rechargez la fiche.',409);const db=database(),now=new Date().toISOString(),author=gate.user!.displayName;let next={...previous},ticket:any=null;
if(b.operation==='ticket'){if(previous.ticketId)return ok({id:previous.id,ticketId:previous.ticketId});ticket={...newTicket(),qualityActionId:previous.id,title:(previous.reference+' · '+(previous.problem||previous.action)).slice(0,200),category:'Qualité',description:'Action du plan consolidé : '+previous.reference+'\n'+previous.problem+'\n'+previous.action+'\nSuivi de cotation et efficacité : /plan-actions?id='+encodeURIComponent(previous.id),teams:[actionTeam(previous)],pilot:previous.pilotId,due:previous.due,status:'Ouvert'};next.ticketId='quality-ticket-'+previous.id}
else if(b.operation==='save'){const fields=['reference','created','service','teamId','pilotId','origin','problem','objective','method','action','hours','cost','gravity','exposure','target','validation','due','status','comment','usedHours','usedCost','criterion','afterGravity','afterExposure','effectiveEvidence','gedId'];if(!b.data||typeof b.data!=='object')return fail('Saisie invalide.');for(const k of fields)(next as any)[k]=b.data[k];const error=actionError(next,todayParis());if(error)return fail(error);if(!await teamsAllowed(gate.user!,[actionTeam(next)],true))return fail('Service destinataire non autorisé.',403);if(previous.parentId){const parent=all.get(previous.parentId);if(!parent||!await teamsAllowed(gate.user!,[actionTeam(parent)],true))return fail('Action d’origine inaccessible.',403)}if(!qualitySource.owners[next.service])return fail('Service inconnu.');if(next.teamId&&!await db.prepare('SELECT id FROM teams WHERE id=?').bind(next.teamId).first())return fail('Équipe inconnue.');if(next.pilotId&&!await db.prepare('SELECT id FROM users WHERE id=?').bind(next.pilotId).first())return fail('Pilote inconnu.');if(next.pilotId){const u=await db.prepare('SELECT display_name FROM users WHERE id=?').bind(next.pilotId).first<any>();next.pilot=u.display_name}if(next.gedId){const docs=await gedDocuments(),doc=docs.get(next.gedId);if(!doc)return fail('Document GED introuvable.');const response=await import('@/app/api/ged/route').then(m=>m.GET(new Request(new URL('/api/ged?id='+encodeURIComponent(next.gedId),req.url),{headers:req.headers})));if(!response.ok)return fail('Document GED non accessible.',403)}if(['gravity','exposure','afterGravity','afterExposure','criterion','effectiveEvidence','action','status'].some(k=>(next as any)[k]!==(previous as any)[k])){next.verifiedAt='';next.verifiedBy='';next.verificationNote=''}}
else if(b.operation==='verify'){const users=await gedUsers(),u=users.find(u=>u.id===gate.user!.id);if(!u?.qsse)return fail('La vérification d’efficacité est réservée au QSSE.',403);if(!['SOLDEE','CLOTUREE'].includes(previous.status)||priority(previous.gravity,previous.exposure)==='A COTER'||priority(previous.afterGravity,previous.afterExposure)==='A COTER'||!previous.criterion.trim()||!previous.effectiveEvidence.trim())return fail('Réalisez l’action et renseignez la cotation avant/après, le critère et les preuves d’efficacité.');if(typeof b.note!=='string'||!b.note.trim()||b.note.length>5000)return fail('Renseignez la conclusion du contrôle.');next.verifiedAt=now;next.verifiedBy=author;next.verificationNote=b.note;if(effectiveness(next)==='Non efficace')next.comment=[next.comment,'Contrôle QSSE : efficacité non atteinte. Nouvelle action à ouvrir avec analyse des causes.'].filter(Boolean).join('\n')}
else return fail('Opération inconnue.');next.revision=previous.revision+1;const mutation=previous.revision?db.prepare('UPDATE quality_actions SET data=?,revision=revision+1,updated_at=?,updated_by=? WHERE id=? AND revision=?').bind(JSON.stringify({...next,raw:undefined}),now,author,next.id,previous.revision):db.prepare('INSERT OR IGNORE INTO quality_actions (id,data,revision,updated_at,updated_by) VALUES (?,?,1,?,?)').bind(next.id,JSON.stringify({...next,raw:undefined}),now,author);const statements=[mutation];if(ticket)statements.push(db.prepare('INSERT INTO hub_tickets (id,data,revision,created_at,updated_at,author) SELECT ?,?,1,?,?,? WHERE changes()=1').bind(next.ticketId,JSON.stringify(ticket),now,now,author));statements.push(db.prepare('INSERT INTO quality_action_history (id,action_id,snapshot,saved_at,saved_by) SELECT ?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),next.id,JSON.stringify({operation:b.operation,before:{...previous,raw:undefined},after:{...next,raw:undefined}}),now,author));const result=await db.batch(statements);if(!result[0].meta.changes)return fail('Modification simultanée. Rechargez la fiche.',409);return ok({id:next.id,revision:next.revision,ticketId:next.ticketId})}catch(e){console.error(e);return fail('Enregistrement impossible. Votre saisie est conservée.',503)}}
