'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {AccountGate,type Account} from '@/components/account-gate';
import {Package,Search,ArrowDownToLine,ArrowUpFromLine,ClipboardCheck,TriangleAlert} from 'lucide-react';
import './stock.css';

type Product={code:string;family:string;name:string;specifics:string;source_row:number;quantity:number|null;minimum:number|null;location:string;revision:number};
type Movement={id:string;code:string;kind:string;delta:number;quantity:number;recipient:string;note:string;author:string;created_at:string};
type Data={products:Product[];movements:Movement[];source:string;sourceCount:number;duplicateRows:Record<string,number[]>};
export default function StockPage(){return <AccountGate>{account=><Stock account={account}/>}</AccountGate>}
function Stock({account}:{account:Account}){
const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[family,setFamily]=useState('Toutes les familles'),[code,setCode]=useState(''),[kind,setKind]=useState('inventaire'),[amount,setAmount]=useState(''),[recipient,setRecipient]=useState(''),[note,setNote]=useState('');
const load=useCallback(async()=>{try{const r=await fetch('/api/epi-stock');const d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}},[]);
useEffect(()=>{load()},[load]);
const families=useMemo(()=>['Toutes les familles',...new Set((data?.products||[]).map(p=>p.family))], [data]);
const filtered=(data?.products||[]).filter(p=>(family==='Toutes les familles'||p.family===family)&&[p.code,p.family,p.name,p.specifics].join(' ').toLocaleLowerCase('fr').includes(search.toLocaleLowerCase('fr')));
const selected=data?.products.find(p=>p.code===code);const counted=(data?.products||[]).filter(p=>p.quantity!==null);const low=counted.filter(p=>p.minimum!==null&&p.quantity!==null&&p.quantity<=p.minimum);
async function send(payload:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/epi-stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await load();setNotice(payload.action==='import'?'Catalogue importé. Renseignez le premier inventaire pour chaque référence suivie.':'Mouvement enregistré.');setAmount('');setRecipient('');setNote('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function submit(e:React.FormEvent){e.preventDefault();if(selected)send({code:selected.code,kind,amount:Number(amount),recipient,note})}
function saveSettings(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const form=new FormData(e.currentTarget);send({action:'settings',code:selected.code,revision:selected.revision,minimum:form.get('minimum'),location:form.get('location')})}
function csv(){if(!data)return;const rows=[['Code','Famille','Article','Spécificités','Stock','Seuil','Emplacement'],...filtered.map(p=>[p.code,p.family,p.name,p.specifics,p.quantity===null?'Non inventorié':String(p.quantity),p.minimum===null?'':String(p.minimum),p.location])];const content='\ufeff'+rows.map(row=>row.map(x=>'"'+(/^[=+@\-\t\r]/.test(x)?"'":'')+x.replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='polytechs-stock-epi.csv';a.click();URL.revokeObjectURL(url)}
return <main className="stock-page"><nav className="stock-breadcrumb"><a href="/unites?team=qsse">← Service QSSE</a><span>/</span><a href="/qse#EPI">Dotations EPI</a><span>/</span><strong>Stock magasin</strong></nav><header className="stock-hero"><div><span className="stock-eyebrow">POLYTECHS · PRÉVENTION</span><h1><Package size={31}/> Stock des EPI</h1><p>Le catalogue identifie les articles. L’inventaire et les mouvements établissent les quantités disponibles ; les dotations individuelles restent dans le registre EPI.</p></div><button className="outline" onClick={csv} disabled={!data?.products.length}>Exporter le stock CSV</button></header>
{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
{!data?<section className="stock-card">Chargement du stock…</section>:<><section className="stock-metrics"><article><strong>{data.products.length}</strong><span>références importées</span></article><article><strong>{counted.length}</strong><span>références inventoriées</span></article><article><strong>{data.products.length-counted.length}</strong><span>à inventorier</span></article><article className={low.length?'stock-warning':''}><strong>{low.length}</strong><span>au seuil ou en dessous</span></article></section>
{!data.products.length&&<section className="stock-card stock-onboarding"><h2>Importer la codification des EPI</h2><p>{data.source} · {data.sourceCount} codes uniques. Les quantités ne figurent pas dans le fichier et commenceront comme non inventoriées.</p>{account.role==='admin'&&<button className="primary" disabled={busy} onClick={()=>send({action:'import'})}>Importer le catalogue</button>}{account.role!=='admin'&&<p>Un administrateur doit lancer l’import initial.</p>}</section>}
{data.products.length>0&&<div className="stock-layout"><section className="stock-card"><div className="stock-section-heading"><div><h2>Catalogue & disponibilités</h2><p>{filtered.length} référence(s) · {data.source}</p></div></div><div className="stock-filters"><label><Search size={17}/><input aria-label="Rechercher un EPI" placeholder="Code, désignation, caractéristique…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Famille d’EPI" value={family} onChange={e=>setFamily(e.target.value)}>{families.map(f=><option key={f}>{f}</option>)}</select></div><div className="stock-list">{filtered.map(p=><button key={p.code} className={'stock-item '+(code===p.code?'selected':'')} onClick={()=>{setCode(p.code);setKind(p.quantity===null?'inventaire':'sortie');setAmount('')}}><span><b>{p.name}</b><small>{p.code} · {p.family}{p.specifics?' · '+p.specifics:''}</small></span><strong className={p.quantity===null?'stock-unknown':p.minimum!==null&&p.quantity<=p.minimum?'stock-alert':''}>{p.quantity===null?'À inventorier':p.quantity+' en stock'}</strong></button>)}{!filtered.length&&<p className="stock-empty">Aucune référence ne correspond à la recherche.</p>}</div></section>
<aside className="stock-card stock-detail">{selected?<><div className="stock-section-heading"><div><span className="stock-eyebrow">{selected.family}</span><h2>{selected.name}</h2><p>{selected.code} · ligne {selected.source_row} du catalogue</p></div></div>{selected.specifics&&<p className="stock-specifics">{selected.specifics}</p>}<div className="stock-balance"><span>Stock disponible</span><strong>{selected.quantity===null?'Non inventorié':selected.quantity}</strong>{selected.minimum!==null&&<small>Seuil d’alerte : {selected.minimum}</small>}{selected.location&&<small>Emplacement : {selected.location}</small>}</div>{account.role!=='reader'&&<><form onSubmit={submit} className="stock-form"><h3>Enregistrer un mouvement</h3><div className="stock-kind"><button type="button" aria-pressed={kind==='inventaire'} onClick={()=>setKind('inventaire')}><ClipboardCheck size={16}/> Inventaire</button><button type="button" aria-pressed={kind==='entree'} disabled={selected.quantity===null} onClick={()=>setKind('entree')}><ArrowDownToLine size={16}/> Entrée</button><button type="button" aria-pressed={kind==='sortie'} disabled={selected.quantity===null} onClick={()=>setKind('sortie')}><ArrowUpFromLine size={16}/> Sortie</button></div><label>{kind==='inventaire'?'Quantité comptée':'Quantité'}<input type="number" min={kind==='inventaire'?0:1} max="1000000" step="1" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>{kind==='sortie'&&<label>Bénéficiaire ou service<input required maxLength={150} value={recipient} onChange={e=>setRecipient(e.target.value)}/></label>}<label>Motif / référence de pièce<input maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex. réception, dotation, correction de comptage"/></label><button className="primary" disabled={busy}>{busy?'Enregistrement…':'Enregistrer le mouvement'}</button><p>Un inventaire remplace le solde compté et conserve l’écart dans l’historique. Les sorties ne peuvent pas rendre le stock négatif.</p></form><form key={selected.code+'-'+selected.revision} className="stock-form" onSubmit={saveSettings}><h3>Réapprovisionnement</h3><label>Seuil d’alerte<input name="minimum" type="number" min="0" max="1000000" step="1" defaultValue={selected.minimum??''} placeholder="Non défini"/></label><label>Emplacement<input name="location" maxLength={150} defaultValue={selected.location} placeholder="Magasin, armoire…"/></label><button className="outline" disabled={busy}>Enregistrer le seuil et l’emplacement</button></form></>}
<h3>Historique de la référence</h3><div className="stock-history">{data.movements.filter(m=>m.code===selected.code).map(m=><article key={m.id}><div><strong>{m.kind==='inventaire'?'Inventaire':m.kind==='entree'?'Entrée':'Sortie'} · {m.delta>0?'+':''}{m.delta}</strong><small>Solde {m.quantity} · {new Date(m.created_at).toLocaleString('fr-FR')}</small></div><p>{m.recipient||m.note||'—'}</p><small>{m.author}</small></article>)}{!data.movements.some(m=>m.code===selected.code)&&<p>Aucun mouvement enregistré.</p>}</div></>:<div className="stock-pick"><Package size={36}/><h2>Sélectionnez une référence</h2><p>Consultez le solde et l’historique, puis effectuez un inventaire, une entrée ou une sortie.</p></div>}</aside></div>}
<p className="stock-source"><TriangleAlert size={16}/> Le fichier comporte des codes répétés ({Object.keys(data.duplicateRows).join(', ')}) : ils sont regroupés par code. L’onglet historique « MàJ tableau 09-03-26 » n’a pas été fusionné avec la nouvelle codification. Aucun solde initial n’a été déduit du fichier.</p></>}</main>
}
