'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {AccountGate,type Account} from '@/components/account-gate';
import {Package,Search,ArrowDownToLine,ArrowUpFromLine,ClipboardCheck,TriangleAlert} from 'lucide-react';
import {Dotations} from './dotations';
import type {Product} from './types';
import './stock.css';

type Movement={id:string;code:string;kind:string;delta:number;quantity:number;recipient:string;note:string;author:string;created_at:string};
type Data={products:Product[];source:string;sourceCount:number;duplicateRows:Record<string,number[]>};
export default function EpiPage(){return <AccountGate>{account=><Epi account={account}/>}</AccountGate>}
function Epi({account}:{account:Account}){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[movements,setMovements]=useState<Movement[]>([]),[historyLoading,setHistoryLoading]=useState(false),[historyMore,setHistoryMore]=useState(false);
  const [view,setView]=useState<'stock'|'dotations'>(()=>typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('view')==='dotations'?'dotations':'stock'),[search,setSearch]=useState(''),[family,setFamily]=useState('Toutes les familles'),[focus,setFocus]=useState('Tous'),[listPage,setListPage]=useState(0),[code,setCode]=useState('');
  const historyRequest=useRef(0);
  const [kind,setKind]=useState('inventaire'),[amount,setAmount]=useState(''),[recipient,setRecipient]=useState(''),[note,setNote]=useState('');
  const load=useCallback(async()=>{try{const response=await fetch('/api/epi-stock');const result=await response.json() as Data&{error?:string};if(!response.ok)throw Error(result.error);setData(result);setError('')}catch(e){setError((e as Error).message)}},[]);
  useEffect(()=>{const controller=new AbortController();fetch('/api/epi-stock',{signal:controller.signal}).then(async response=>{const result=await response.json() as Data&{error?:string};if(!response.ok)throw Error(result.error);setData(result)}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message)});return()=>controller.abort()},[]);
  const loadMovements=useCallback(async(selectedCode:string,offset=0)=>{const request=++historyRequest.current;setHistoryLoading(true);try{const response=await fetch('/api/epi-stock?code='+encodeURIComponent(selectedCode)+'&offset='+offset);const result=await response.json() as {movements?:Movement[];hasMore?:boolean;error?:string};if(!response.ok)throw Error(result.error);if(request===historyRequest.current){setMovements(old=>offset?[...old,...(result.movements||[])]:result.movements||[]);setHistoryMore(!!result.hasMore)}}catch(e){if(request===historyRequest.current)setError((e as Error).message)}finally{if(request===historyRequest.current)setHistoryLoading(false)}},[]);
  function clearSelection(){historyRequest.current++;setCode('');setMovements([]);setHistoryMore(false);setHistoryLoading(false)}
  function selectProduct(product:Product){setCode(product.code);setKind(product.quantity===null?'inventaire':'sortie');setAmount('');setMovements([]);setHistoryMore(false);void loadMovements(product.code)}
  const families=useMemo(()=>[...new Set((data?.products||[]).map(p=>p.family))].sort((a,b)=>a.localeCompare(b,'fr')),[data]);
  const filtered=(data?.products||[]).filter(p=>(family==='Toutes les familles'||p.family===family)&&[p.code,p.family,p.name,p.specifics].join(' ').toLocaleLowerCase('fr').includes(search.toLocaleLowerCase('fr'))&&(focus==='Tous'||focus==='À inventorier'&&p.quantity===null||focus==='À confirmer'&&p.catalog_status==='À confirmer'||focus==='Seuil atteint'&&p.quantity!==null&&p.minimum!==null&&p.quantity<=p.minimum));
  const pageSize=12,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(listPage,totalPages-1),visible=filtered.slice(currentPage*pageSize,(currentPage+1)*pageSize);
  const selected=data?.products.find(p=>p.code===code),counted=(data?.products||[]).filter(p=>p.quantity!==null),low=counted.filter(p=>p.minimum!==null&&p.quantity!==null&&p.quantity<=p.minimum);
  function selectView(value:'stock'|'dotations'){setView(value);history.replaceState(null,'',value==='stock'?'/epi-stock':'/epi-stock?view=dotations')}
  function filterFamily(value:string){setFamily(value);setListPage(0);clearSelection()}
  function filterFocus(value:string){setFocus(value);setListPage(0);clearSelection()}
  async function send(payload:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/epi-stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error);await load();if(code)await loadMovements(code);setNotice(payload.action==='catalog'?'Statut du catalogue enregistré.':payload.action==='settings'?'Seuil et emplacement enregistrés.':'Mouvement enregistré.');setAmount('');setRecipient('');setNote('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function submit(event:React.FormEvent){event.preventDefault();if(selected)send({code:selected.code,kind,amount:Number(amount),recipient,note})}
  function saveSettings(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);send({action:'settings',code:selected.code,revision:selected.revision,minimum:form.get('minimum'),location:form.get('location')})}
  function csv(){if(!data)return;const rows=[['Code','Famille','Article','Spécificités','Source','Statut catalogue','Stock','Seuil','Emplacement'],...filtered.map(p=>[p.code,p.family,p.name,p.specifics,p.source_sheet,p.catalog_status,p.quantity===null?'Non inventorié':String(p.quantity),p.minimum===null?'':String(p.minimum),p.location])];const content='\ufeff'+rows.map(row=>row.map(x=>'"'+(/^[=+@\-\t\r]/.test(x)?"'":'')+x.replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='polytechs-stock-epi.csv';link.click();URL.revokeObjectURL(url)}
  return <main className="stock-page">
    <nav className="stock-breadcrumb"><a href="/unites?team=qsse">← Service QSSE</a><span>/</span><strong>EPI</strong></nav>
    <header className="stock-hero"><div><span className="stock-eyebrow">POLYTECHS · PRÉVENTION</span><h1><Package size={31}/> Espace EPI</h1><p>Références, stock magasin et dotations au même endroit.</p></div>{view==='stock'&&<button className="outline" onClick={csv} disabled={!data?.products.length}>Exporter le stock CSV</button>}</header>
    <div className="epi-tabs" role="tablist" aria-label="Espace EPI"><button role="tab" aria-selected={view==='stock'} onClick={()=>selectView('stock')}>Catalogue & stock</button><button role="tab" aria-selected={view==='dotations'} onClick={()=>selectView('dotations')}>Dotations</button></div>
    {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
    {!data?<section className="stock-card">Chargement des EPI…</section>:view==='dotations'?<Dotations account={account} products={data.products}/>:<>
      <section className="stock-metrics"><article><strong>{data.products.length}</strong><span>références</span></article><article><strong>{counted.length}</strong><span>inventoriées</span></article><article><strong>{data.products.length-counted.length}</strong><span>à inventorier</span></article><article className={low.length?'stock-warning':''}><strong>{low.length}</strong><span>au seuil ou en dessous</span></article></section>
      <div className="stock-family-grid"><button className={family==='Toutes les familles'?'active':''} onClick={()=>filterFamily('Toutes les familles')}><strong>Toutes</strong><small>{data.products.length}</small></button>{families.map(f=><button className={family===f?'active':''} key={f} onClick={()=>filterFamily(f)}><strong>{f}</strong><small>{data.products.filter(p=>p.family===f).length}</small></button>)}</div>
      <div className="stock-layout"><section className="stock-card"><div className="stock-section-heading"><div><h2>Références</h2><p>{filtered.length} résultat(s) · {family==='Toutes les familles'?'toutes les familles':family}</p></div></div>
        <div className="stock-filters"><label><Search size={17}/><input aria-label="Rechercher un EPI" placeholder="Code, article, taille…" value={search} onChange={e=>{setSearch(e.target.value);setListPage(0)}}/></label><select aria-label="Situation du stock" value={focus} onChange={e=>filterFocus(e.target.value)}>{['Tous','À inventorier','À confirmer','Seuil atteint'].map(x=><option key={x}>{x}</option>)}</select></div>
        <div className="stock-list">{visible.map(p=><button key={p.code} className={'stock-item '+(code===p.code?'selected':'')} onClick={()=>selectProduct(p)}><span><b>{p.name}</b><small>{p.code} · {p.specifics||p.family}</small></span><span className="stock-item-status"><strong className={p.quantity===null?'stock-unknown':p.minimum!==null&&p.quantity<=p.minimum?'stock-alert':''}>{p.quantity===null?'À inventorier':p.quantity+' en stock'}</strong>{p.catalog_status!=='Actif'&&<em>{p.catalog_status}</em>}</span></button>)}{!filtered.length&&<p className="stock-empty">Aucune référence ne correspond aux filtres.</p>}</div>
        {totalPages>1&&<nav className="stock-pagination" aria-label="Pages du catalogue"><button disabled={currentPage===0} onClick={()=>{setListPage(currentPage-1);clearSelection()}}>Précédent</button><span>Page {currentPage+1} / {totalPages}</span><button disabled={currentPage===totalPages-1} onClick={()=>{setListPage(currentPage+1);clearSelection()}}>Suivant</button></nav>}
      </section>
      <aside className="stock-card stock-detail">{selected?<><div className="stock-section-heading"><div><span className="stock-eyebrow">{selected.family}</span><h2>{selected.name}</h2><p>{selected.code} · {selected.source_sheet}, ligne {selected.source_row} · {selected.catalog_status}</p></div></div>{selected.specifics&&<p className="stock-specifics">{selected.specifics}</p>}
        {selected.catalog_status==='À confirmer'&&<p className="stock-pending">Cette référence provient seulement de l’ancien tableau. Vérifiez-la avant de la confirmer.</p>}
        {account.role==='admin'&&<div className="stock-catalog-actions"><button className="outline" disabled={busy||selected.catalog_status==='Actif'} onClick={()=>send({action:'catalog',code:selected.code,revision:selected.revision,status:'Actif'})}>Confirmer</button><button className="outline" disabled={busy||selected.catalog_status==='Inactif'} onClick={()=>send({action:'catalog',code:selected.code,revision:selected.revision,status:'Inactif'})}>Désactiver</button></div>}
        <div className="stock-balance"><span>Stock disponible</span><strong>{selected.quantity===null?'Non inventorié':selected.quantity}</strong>{selected.minimum!==null&&<small>Seuil d’alerte : {selected.minimum}</small>}{selected.location&&<small>Emplacement : {selected.location}</small>}</div>
        {account.role!=='reader'&&<><form onSubmit={submit} className="stock-form"><h3>Enregistrer un mouvement</h3><div className="stock-kind"><button type="button" aria-pressed={kind==='inventaire'} onClick={()=>setKind('inventaire')}><ClipboardCheck size={16}/> Inventaire</button><button type="button" aria-pressed={kind==='entree'} disabled={selected.quantity===null||selected.catalog_status==='Inactif'} onClick={()=>setKind('entree')}><ArrowDownToLine size={16}/> Entrée</button><button type="button" aria-pressed={kind==='sortie'} disabled={selected.quantity===null} onClick={()=>setKind('sortie')}><ArrowUpFromLine size={16}/> Sortie</button></div><label>{kind==='inventaire'?'Quantité comptée':'Quantité'}<input type="number" min={kind==='inventaire'?0:1} max="1000000" step="1" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>{kind==='sortie'&&<label>Bénéficiaire ou service<input required maxLength={150} value={recipient} onChange={e=>setRecipient(e.target.value)}/></label>}<label>Motif / référence de pièce<input maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}</button></form><form key={selected.code+'-'+selected.revision} className="stock-form" onSubmit={saveSettings}><h3>Réapprovisionnement</h3><label>Seuil d’alerte<input name="minimum" type="number" min="0" max="1000000" step="1" defaultValue={selected.minimum??''} placeholder="Non défini"/></label><label>Emplacement<input name="location" maxLength={150} defaultValue={selected.location} placeholder="Magasin, armoire…"/></label><button className="outline" disabled={busy}>Enregistrer</button></form></>}
        <h3>Historique de la référence</h3><div className="stock-history">{movements.map(m=><article key={m.id}><div><strong>{m.kind==='inventaire'?'Inventaire':m.kind==='entree'?'Entrée':'Sortie'} · {m.delta>0?'+':''}{m.delta}</strong><small>Solde {m.quantity} · {new Date(m.created_at).toLocaleString('fr-FR')}</small></div><p>{m.recipient||m.note||'—'}</p><small>{m.author}</small></article>)}{historyLoading?<p>Chargement de l’historique…</p>:!movements.length&&<p>Aucun mouvement enregistré.</p>}</div>{historyMore&&<button className="outline" disabled={historyLoading} onClick={()=>loadMovements(selected.code,movements.length)}>Charger les mouvements précédents</button>}
      </>:<div className="stock-pick"><Package size={36}/><h2>Choisissez un article</h2><p>Consultez son solde et ses mouvements, puis réalisez un inventaire, une entrée ou une sortie.</p></div>}</aside></div>
      <p className="stock-source"><TriangleAlert size={16}/> Les 72 références provenant uniquement de l’ancien tableau sont à confirmer. Aucun solde initial n’a été déduit du fichier.</p>
    </>}
  </main>;
}
