import {database,bucket} from '@/db/raw';
import {requireRole,checkOrigin} from '@/lib/access';
import {teamsAllowed,someTeamAllowed} from '@/lib/team-access';
import {gedDocuments,gedVersion} from '@/lib/ged-server';
import {documentTeams,participant,editableStatuses} from '@/lib/ged';
import {documentFileLimit,documentMime} from '@/lib/document-file';
const fail=(error:string,status=400)=>Response.json({error},{status});
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;const p=new URL(req.url).searchParams,file=await database().prepare('SELECT * FROM ged_files WHERE id=?').bind(p.get('id')||'').first<any>();if(!file)return fail('Fichier introuvable.',404);const version=await gedVersion(file.version_id);if(!version)return fail('Version introuvable.',404);const doc=(await gedDocuments()).get(version.document_id);if(!doc)return fail('Document introuvable.',404);if(documentTeams(doc).includes('rh')&&!await teamsAllowed(gate.user!,['rh']))return fail('Accès RH nécessaire.',403);const permitted=gate.user!.role==='admin'||participant(version,gate.user!.id)||version.status==='Approuvé'&&await someTeamAllowed(gate.user!,documentTeams(doc));if(!permitted)return fail('Accès au fichier non autorisé.',403);const blob=await bucket().get('ged/'+version.id+'/'+file.id);if(!blob)return fail('Fichier indisponible.',404);const inline=p.get('preview')==='1'&&['application/pdf','image/png','image/jpeg'].includes(file.mime);return new Response(blob.body,{headers:{'Content-Type':file.mime,'Content-Length':String(file.size),'Content-Disposition':(inline?'inline':'attachment')+"; filename*=UTF-8''"+encodeURIComponent(file.name),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}})}catch(e){console.error(e);return fail('Téléchargement indisponible.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Origine non autorisée.',403);const gate=await requireRole(req,'editor');if(gate.error)return gate.error;const db=database(),user=gate.user!,now=new Date().toISOString();
if(req.headers.get('content-type')?.includes('application/json')){const b=await req.json() as any;if(b.action!=='remove'||typeof b.versionId!=='string'||typeof b.fileId!=='string'||!Number.isInteger(b.revision))return fail('Demande invalide.');const v=await gedVersion(b.versionId);if(!v)return fail('Version introuvable.',404);const doc=(await gedDocuments()).get(v.document_id);if(!doc)return fail('Document introuvable.',404);if(documentTeams(doc).includes('rh')&&!await teamsAllowed(user,['rh'],true))return fail('Accès RH nécessaire.',403);if(!editableStatuses.includes(v.status)||(user.role!=='admin'&&v.data.authorId!==user.id))return fail('Les fichiers sont figés après envoi en relecture.',403);const f=await db.prepare('SELECT * FROM ged_files WHERE id=? AND version_id=?').bind(b.fileId,v.id).first<any>();if(!f)return fail('Fichier introuvable.',404);const result=await db.batch([db.prepare("UPDATE ged_versions SET revision=revision+1,updated_at=? WHERE id=? AND revision=? AND status IN ('Brouillon','À corriger')").bind(now,v.id,b.revision),db.prepare('DELETE FROM ged_files WHERE id=? AND version_id=? AND changes()=1').bind(f.id,v.id),db.prepare('INSERT INTO ged_events (id,document_id,version_id,action,note,snapshot,actor_id,actor,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),v.document_id,v.id,'Retrait de fichier',f.name,JSON.stringify(f),user.id,user.displayName,now)]);if(!result[0].meta.changes)return fail('La version a changé. Rechargez avant de réessayer.',409);try{await bucket().delete('ged/'+v.id+'/'+f.id)}catch(e){console.error('GED orphan cleanup',e)}return Response.json({removed:true})}
if(Number(req.headers.get('content-length')||0)>documentFileLimit+65536)return fail('Limite : 15 Mo par fichier.',413);const form=await req.formData(),versionId=form.get('versionId'),revision=Number(form.get('revision')),file=form.get('file');if(typeof versionId!=='string'||!Number.isInteger(revision)||!(file instanceof File)||!file.size||file.size>documentFileLimit||file.name.length>200)return fail('Choisissez un fichier de 15 Mo maximum.');const v=await gedVersion(versionId);if(!v)return fail('Enregistrez le brouillon avant de joindre le document.',404);const doc=(await gedDocuments()).get(v.document_id);if(!doc)return fail('Document introuvable.',404);if(documentTeams(doc).includes('rh')&&!await teamsAllowed(user,['rh'],true))return fail('Accès RH nécessaire.',403);if(!editableStatuses.includes(v.status)||(user.role!=='admin'&&v.data.authorId!==user.id))return fail('Les fichiers sont figés après envoi en relecture.',403);if(v.revision!==revision)return fail('La version a changé. Rechargez avant de réessayer.',409);const bytes=new Uint8Array(await file.arrayBuffer()),mime=documentMime(file.name,bytes);if(!mime)return fail('Formats acceptés : PDF, DOCX/XLSX sans macros ni objets incorporés, JPG et PNG. Convertissez les anciens DOC/XLS.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join(''),id=crypto.randomUUID(),key='ged/'+v.id+'/'+id,name=file.name.replace(/[\r\n\x00]/g,'');await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});try{const result=await db.batch([db.prepare("UPDATE ged_versions SET revision=revision+1,updated_at=? WHERE id=? AND revision=? AND status IN ('Brouillon','À corriger') AND (SELECT count(*) FROM ged_files WHERE version_id=?)<20").bind(now,v.id,revision,v.id),db.prepare('INSERT INTO ged_files (id,version_id,name,mime,size,sha256,author,created_at) SELECT ?,?,?,?,?,?,?,? WHERE changes()=1').bind(id,v.id,name,mime,file.size,hash,user.displayName,now),db.prepare('INSERT INTO ged_events (id,document_id,version_id,action,note,snapshot,actor_id,actor,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),v.document_id,v.id,'Ajout de fichier',name,JSON.stringify({id,name,mime,size:file.size,sha256:hash}),user.id,user.displayName,now)]);if(!result[0].meta.changes){await bucket().delete(key);return fail('Version modifiée entre-temps ou limite de 20 fichiers atteinte.',409)}}catch(e){await bucket().delete(key);throw e}return Response.json({id})
}catch(e){console.error(e);return fail('Ajout impossible. Vérifiez la liste des fichiers avant de réessayer.',503)}}
