import {database} from '@/db/raw';
import {requireRole,checkOrigin} from '@/lib/access';
import {accessibleTeams,someTeamAllowed,teamsAllowed} from '@/lib/team-access';
import {gedSource} from '@/lib/ged-private-source';
import {gedUsers,gedDocuments,gedVersion,parseVersion} from '@/lib/ged-server';
import {blankDocument,draftFrom,draftErrors,documentTeams,participant,transition,processes,editableStatuses,openStatuses,type GedDocument,type GedDraft} from '@/lib/ged';
const fail=(error:string,status=400)=>Response.json({error},{status}),ok=(data:unknown)=>Response.json(data,{headers:{'Cache-Control':'private, no-store'}});
const draftKeys=['ref','index','title','type','process','comment','changeReason','authorId','reviewerId','approverId','externalUrl'] as const;
function cleanDraft(value:any):GedDraft {return Object.fromEntries(draftKeys.map(k=>[k,value?.[k]])) as GedDraft}
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;const user=gate.user!,db=database(),p=new URL(req.url).searchParams,users=await gedUsers();if(p.get('scope')==='meta')return ok({users});if(p.get('scope')==='source-history'){if(user.role!=='admin')return fail('Accès administrateur nécessaire.',403);return ok({history:gedSource?.history||[]})}
const docs=await gedDocuments(),id=p.get('id'),versions=(await db.prepare('SELECT * FROM ged_versions ORDER BY created_at DESC').all()).results.map(parseVersion);
if(id){const document=docs.get(id);if(!document)return fail('Document introuvable.',404);const ownVersions=versions.filter(v=>v.document_id===id);if(!await someTeamAllowed(user,documentTeams(document))&&!ownVersions.some(v=>participant(v,user.id)))return fail('Accès au document non autorisé.',403);const visible=ownVersions.filter(v=>v.status==='Approuvé'||user.role==='admin'||participant(v,user.id));const files=visible.length?(await db.prepare('SELECT f.* FROM ged_files f JOIN ged_versions v ON v.id=f.version_id WHERE v.document_id=? ORDER BY f.created_at').bind(id).all()).results.filter((f:any)=>visible.some(v=>v.id===f.version_id)):[];const events=(await db.prepare('SELECT * FROM ged_events WHERE document_id=? ORDER BY created_at DESC LIMIT 100').bind(id).all()).results.filter((e:any)=>user.role==='admin'||visible.some(v=>v.id===e.version_id));return ok({document,versions:visible,files,events,headers:gedSource?.headers[document.sourceSheet]||{},users})}
const allowed=await accessibleTeams(user),rows=[...docs.values()].filter(d=>user.role==='admin'||documentTeams(d).some(t=>allowed.has(t))||versions.some(v=>v.document_id===d.id&&participant(v,user.id))).map(({raw,...d})=>{const pending=versions.find(v=>v.document_id===d.id&&openStatuses.includes(v.status)&&(user.role==='admin'||participant(v,user.id)));return {...d,pending:pending?{id:pending.id,status:pending.status,authorId:pending.data.authorId,reviewerId:pending.data.reviewerId,approverId:pending.data.approverId}:undefined}});return ok({documents:rows,source:gedSource?{name:gedSource.source,count:gedSource.records.length}:null});
}catch(e){console.error(e);return fail('Chargement de la GED impossible. Réessayez.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Origine non autorisée.',403);const gate=await requireRole(req,'editor');if(gate.error)return gate.error;const user=gate.user!,db=database(),b=await req.json() as any;if(!b||typeof b.action!=='string')return fail('Demande invalide.');const users=await gedUsers(),now=new Date().toISOString();
if(b.action==='profile'){if(user.role!=='admin')return fail('Accès administrateur nécessaire.',403);if(typeof b.userId!=='string'||typeof b.managerId!=='string'||typeof b.qsse!=='boolean'||!users.some(u=>u.id===b.userId)||b.managerId&&!users.some(u=>u.id===b.managerId&&u.role!=='reader')||b.userId===b.managerId)return fail('Choisissez un N+1 distinct, contributeur ou administrateur.');const mapping=new Map(users.map(u=>[u.id,u.managerId]));mapping.set(b.userId,b.managerId);let cursor=b.managerId;const visited=new Set([b.userId]);while(cursor){if(visited.has(cursor))return fail('Cette affectation crée une boucle dans la hiérarchie.');visited.add(cursor);cursor=mapping.get(cursor)||''}await db.batch([db.prepare('INSERT INTO ged_profiles (user_id,manager_id,qsse) VALUES (?,?,?) ON CONFLICT(user_id) DO UPDATE SET manager_id=excluded.manager_id,qsse=excluded.qsse').bind(b.userId,b.managerId||null,b.qsse?1:0),db.prepare('INSERT INTO ged_events (id,document_id,version_id,action,note,snapshot,actor_id,actor,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),'profile-'+b.userId,'','Configuration du circuit','',JSON.stringify({managerId:b.managerId,qsse:b.qsse}),user.id,user.displayName,now)]);return ok({saved:true})}
const docs=await gedDocuments();if(b.action==='create-version'){
if(typeof b.documentId!=='string'||b.documentId.length>100)return fail('Document invalide.');const existing=b.documentId?docs.get(b.documentId):null;if(b.documentId&&!existing)return fail('Document introuvable.',404);if(existing&&!await teamsAllowed(user,[processes[existing.process]?.team||'qsse'],true))return fail('Modification de ce service non autorisée.',403);const seed=existing||blankDocument();const data=cleanDraft(b.data||draftFrom(seed,user.id));const errors=draftErrors(data,users);if(errors.length)return fail(errors.join('\n'));if(user.role!=='admin'&&data.authorId!==user.id)return fail('Créez une version dont vous êtes l’auteur.',403);if(!await teamsAllowed(user,[processes[data.process]?.team||'qsse'],true))return fail('Modification de ce service non autorisée.',403);if(!existing&&[...docs.values()].some(d=>d.ref.trim().toLowerCase()===data.ref.trim().toLowerCase()))return fail('Cette référence existe déjà. Ouvrez sa fiche et créez une nouvelle version.',409);if(existing&&(await db.prepare("SELECT id FROM ged_versions WHERE document_id=? AND status IN ('Brouillon','À corriger','Relecture QSSE','Approbation N+1')").bind(existing.id).first()))return fail('Une version est déjà en préparation pour ce document.',409);
const id=existing?.id||crypto.randomUUID(),versionId=crypto.randomUUID(),document={...seed,id,...(!existing?{ref:data.ref,title:data.title,type:data.type,process:data.process}:{} )};const statements=[db.prepare('INSERT OR IGNORE INTO ged_documents (id,data,revision,published_version_id) VALUES (?,?,?,?)').bind(id,JSON.stringify({...document,raw:undefined,pending:undefined}),existing?.revision||1,existing?.publishedVersionId||''),db.prepare('INSERT INTO ged_versions (id,document_id,data,status,revision,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(versionId,id,JSON.stringify(data),'Brouillon',1,now,now),db.prepare('INSERT INTO ged_events (id,document_id,version_id,action,note,snapshot,actor_id,actor,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,versionId,'Création du brouillon','',JSON.stringify(data),user.id,user.displayName,now)];try{await db.batch(statements)}catch(e){if(String(e).includes('UNIQUE'))return fail('Une version vient d’être créée. Rechargez la fiche.',409);throw e}return ok({id,versionId})}
if(typeof b.versionId!=='string'||b.versionId.length>100||!Number.isInteger(b.revision))return fail('Version invalide.');const v=await gedVersion(b.versionId);if(!v)return fail('Version introuvable.',404);if(v.revision!==b.revision)return fail('Cette version a changé. Copiez votre saisie puis rechargez la fiche.',409);const doc=docs.get(v.document_id);if(!doc)return fail('Document introuvable.',404);if(user.role!=='admin'&&!participant(v,user.id))return fail('Accès à cette version non autorisé.',403);
if(b.action==='save-draft'){
if(!editableStatuses.includes(v.status)||(user.role!=='admin'&&v.data.authorId!==user.id))return fail('Seul un brouillon peut être modifié par son auteur.',403);const data=cleanDraft(b.data),errors=draftErrors(data,users);if(errors.length)return fail(errors.join('\n'));if(user.role!=='admin'&&data.authorId!==v.data.authorId)return fail('L’auteur ne peut pas être réattribué.',403);const result=await db.batch([db.prepare("UPDATE ged_versions SET data=?,revision=revision+1,updated_at=?,reviewed_by='',reviewed_at='',approved_by='',approved_at='' WHERE id=? AND revision=? AND status IN ('Brouillon','À corriger')").bind(JSON.stringify(data),now,v.id,v.revision),db.prepare('INSERT INTO ged_events (id,document_id,version_id,action,note,snapshot,actor_id,actor,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),doc.id,v.id,'Modification du brouillon',data.changeReason,JSON.stringify(data),user.id,user.displayName,now)]);if(!result[0].meta.changes)return fail('Modification concurrente. Rechargez la fiche.',409);return ok({id:doc.id})}
const note=typeof b.note==='string'&&b.note.length<=5000?b.note:'';const next=transition(v,b.action,user.id,note);if(!next)return fail(b.action==='reject'&&!note.trim()?'Précisez les corrections demandées.':'Cette décision ne vous est pas attribuée ou l’étape a déjà changé.',403);
if(b.action==='submit'){const errors=draftErrors(v.data,users,true);if(!await db.prepare('SELECT id FROM ged_files WHERE version_id=? LIMIT 1').bind(v.id).first())errors.push('Joignez le document de cette version avant la relecture.');if(doc.publishedVersionId){const old=await gedVersion(doc.publishedVersionId);if(old&&old.data.index.trim().toLowerCase()===v.data.index.trim().toLowerCase())errors.push('Utilisez un nouvel indice pour cette modification.')}if(errors.length)return fail(errors.join('\n'))}
if(b.action==='review'&&!users.some(u=>u.id===user.id&&u.qsse))return fail('La relecture est réservée au service QSSE.',403);
const reviewedBy=b.action==='review'?user.id:b.action==='reject'?'':v.reviewed_by,reviewedAt=b.action==='review'?now:b.action==='reject'?'':v.reviewed_at,approvedBy=b.action==='approve'?user.id:'',approvedAt=b.action==='approve'?now:'';
const statements=[db.prepare('UPDATE ged_versions SET status=?,revision=revision+1,updated_at=?,reviewed_by=?,reviewed_at=?,approved_by=?,approved_at=? WHERE id=? AND revision=? AND status=?').bind(next.status,now,reviewedBy,reviewedAt,approvedBy,approvedAt,v.id,v.revision,v.status),db.prepare('INSERT INTO ged_events (id,document_id,version_id,action,note,snapshot,actor_id,actor,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),doc.id,v.id,{'submit':'Envoi en relecture','review':'Relecture QSSE validée','approve':'Approbation N+1','reject':'Corrections demandées','abandon':'Brouillon abandonné'}[b.action as 'submit']||b.action,note,JSON.stringify({...v,data:v.data,status:next.status,reviewedBy,reviewedAt,approvedBy,approvedAt}),user.id,user.displayName,now)];
if(b.action==='approve'){const document:GedDocument={...doc,ref:v.data.ref,index:v.data.index,title:v.data.title,type:v.data.type,process:v.data.process,comment:v.data.comment,updated:now.slice(0,10),catalogStatus:'Actif',updateRequired:false,sourceArchive:false,issues:[],publishedVersionId:v.id};statements.push(db.prepare('UPDATE ged_documents SET data=?,published_version_id=?,revision=revision+1 WHERE id=? AND changes()=1').bind(JSON.stringify({...document,raw:undefined,pending:undefined}),v.id,doc.id))}
const target=b.action==='submit'?v.data.reviewerId:b.action==='review'?v.data.approverId:['reject','approve'].includes(b.action)?v.data.authorId:'';if(target)statements.push(db.prepare('INSERT INTO hub_notifications (id,user_id,title,href,seen,created_at) SELECT ?,?,?,?,0,? WHERE changes()=1').bind(crypto.randomUUID(),target,'GED · '+next.status+' · '+v.data.ref,'/ged?document='+encodeURIComponent(doc.id),now));const result=await db.batch(statements);if(!result[0].meta.changes)return fail('Une autre personne a traité cette étape. Rechargez la fiche.',409);return ok({id:doc.id,status:next.status});
}catch(e){console.error(e);return fail('Opération impossible. La saisie est conservée ; rechargez avant de réessayer.',503)}}
