import {database} from '@/db/raw';
import {checkOrigin,requireRole} from '@/lib/access';
import {actionStatuses,riskErrors,riskScore,riskStatuses,type Risk} from '@/lib/evrp';
import {evrpSource} from '@/lib/evrp-private-source';
import {dateValid} from '@/lib/workflows';

const reply=(error:string,status=400)=>Response.json({error},{status});
const parse=(row:any)=>({...row,data:JSON.parse(row.data)});
const limits=(value:unknown,max=5000)=>typeof value==='string'&&value.length<=max;
const date=(value:string)=>!value||dateValid(value);
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;const db=database(),url=new URL(req.url),scope=url.searchParams.get('scope')||'overview';
if(scope==='overview'){const [units,counts,actions,updates,candidateRows]=await Promise.all([db.prepare('SELECT * FROM evrp_units ORDER BY code').all(),db.prepare('SELECT unit_code,count(*) AS total,sum(CASE WHEN status="Validé" THEN 1 ELSE 0 END) AS validated FROM evrp_risks GROUP BY unit_code').all(),db.prepare('SELECT * FROM evrp_actions ORDER BY id').all(),db.prepare('SELECT * FROM evrp_revisions ORDER BY date DESC, id DESC').all(),db.prepare('SELECT id,unit_code,data,status FROM evrp_risks').all()]);const candidates=candidateRows.results.flatMap((row:any)=>{const risk:Risk=JSON.parse(row.data);return risk.applicable&&risk.planned?.trim()?[{id:row.id,unitCode:row.unit_code,factor:risk.factor,risk:risk.risk,planned:risk.planned,score:riskScore(risk),reviewNeeded:!!risk.reviewReasons.length&&row.status!=='Validé',status:row.status}]:[]});return Response.json({units:units.results.map((u:any)=>({...u,roles:JSON.parse(u.roles)})),counts:counts.results,actions:actions.results.map(parse),updates:updates.results,candidates,sourceAvailable:!!evrpSource,sourceCount:evrpSource?.risks.length||0})}
if(scope==='risks'){const unit=url.searchParams.get('unit')||'';if(!/^UT\d{1,2}$/.test(unit))return reply('Unité invalide.');const rows=await db.prepare('SELECT * FROM evrp_risks WHERE unit_code=? ORDER BY id').bind(unit).all();return Response.json({risks:rows.results.map((row:any)=>({...row,data:JSON.parse(row.data),original:JSON.parse(row.original)}))})}
if(scope==='history'){const id=url.searchParams.get('id')||'';if(!/^[A-Za-z0-9-]{5,60}$/.test(id))return reply('Fiche invalide.');const rows=await db.prepare('SELECT revision,snapshot,saved_at,saved_by FROM evrp_risk_history WHERE risk_id=? ORDER BY revision DESC').bind(id).all();return Response.json({history:rows.results})}
if(scope==='action-history'){const id=url.searchParams.get('id')||'';if(!/^[A-Za-z0-9-]{5,60}$/.test(id))return reply('Action invalide.');const rows=await db.prepare('SELECT revision,snapshot,saved_at,saved_by FROM evrp_action_history WHERE action_id=? ORDER BY revision DESC').bind(id).all();return Response.json({history:rows.results})}
if(scope==='export'){const [units,risks,actions,updates]=await Promise.all([db.prepare('SELECT * FROM evrp_units ORDER BY code').all(),db.prepare('SELECT * FROM evrp_risks ORDER BY unit_code,id').all(),db.prepare('SELECT * FROM evrp_actions ORDER BY id').all(),db.prepare('SELECT * FROM evrp_revisions ORDER BY date,id').all()]);return Response.json({exportedAt:new Date().toISOString(),method:'F × G × IM × ID',units:units.results.map((u:any)=>({...u,roles:JSON.parse(u.roles)})),risks:risks.results.map((r:any)=>({...r,data:JSON.parse(r.data),original:JSON.parse(r.original)})),actions:actions.results.map(parse),updates:updates.results},{headers:{'Cache-Control':'no-store','Content-Disposition':'attachment; filename="DUERP-Polytechs.json"'}})}
return reply('Vue inconnue.');}catch(e){console.error(e);return reply('Évaluation indisponible. Réessayez.',503)}}

export async function POST(req:Request){try{if(!checkOrigin(req))return reply('Requête non autorisée.',403);const gate=await requireRole(req,'editor');if(gate.error)return gate.error;const body=await req.json() as any;if(!body||typeof body!=='object')return reply('Saisie invalide.');const db=database(),now=new Date().toISOString(),author=gate.user!.displayName;
if(body.action==='risk'){const raw=body.data||{};if(!/^UT\d{1,2}$/.test(raw.unitCode||''))return reply('Unité de travail invalide.');const exists=await db.prepare('SELECT code FROM evrp_units WHERE code=?').bind(raw.unitCode).first();if(!exists)return reply('Unité de travail inconnue.');const previous=body.id?await db.prepare('SELECT * FROM evrp_risks WHERE id=?').bind(body.id).first<any>():null;if(body.id&&!previous)return reply('Fiche introuvable.',404);if(previous&&(previous.revision!==body.revision||previous.unit_code!==raw.unitCode))return reply('La fiche a changé. Rechargez-la avant de modifier.',409);
const fields=['factor','risk','exposure','existing','planned','reviewComment'] as const;for(const f of fields)if(!limits(raw[f]??'',f==='risk'||f==='factor'?250:5000))return reply('Un champ dépasse la limite autorisée.');const base:Risk=previous?JSON.parse(previous.data):{id:'',unitCode:raw.unitCode,factor:'',risk:'',applicable:true,exposure:'',existing:'',frequencyLabel:'',f:null,gravityLabel:'',g:null,masteryLabel:'',im:null,detectionLabel:'',detection:null,accidentDate:'',sourceScore:null,planned:'',sourceSheet:'Nouvelle évaluation',sourceRow:0,reviewReasons:[]};
const item:Risk={...base,...Object.fromEntries(fields.map(f=>[f,raw[f]||''])),applicable:raw.applicable===false?false:true,f:raw.f===null?null:Number(raw.f),g:raw.g===null?null:Number(raw.g),im:raw.im===null?null:Number(raw.im),detection:raw.detection===null?null:Number(raw.detection)};const status=body.status||'En cours';if(!riskStatuses.includes(status))return reply('Statut invalide.');const errors=riskErrors(item,status);if(errors.length)return reply(errors.join(' '));const encoded=JSON.stringify(item);
if(previous){const result=await db.batch([db.prepare('INSERT INTO evrp_risk_history (id,risk_id,revision,snapshot,saved_at,saved_by) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),body.id,previous.revision,previous.data,now,author),db.prepare('UPDATE evrp_risks SET data=?,status=?,revision=revision+1,updated_at=?,updated_by=? WHERE id=? AND revision=?').bind(encoded,status,now,author,body.id,previous.revision)]);if(!result[1].meta.changes)return reply('Modification concurrente. Rechargez la fiche.',409);return Response.json({id:body.id})}
const id=crypto.randomUUID();item.id=id;await db.prepare('INSERT INTO evrp_risks (id,unit_code,data,original,status,revision,updated_at,updated_by) VALUES (?,?,?,?,?,1,?,?)').bind(id,item.unitCode,JSON.stringify(item),JSON.stringify(item),status,now,author).run();return Response.json({id})}
if(body.action==='action'){const v=body.data||{};for(const k of ['unitCode','riskId','description','owner','due','status','effectiveness','notes','execution','indicator','resources','checker','start','finished','effectivenessResult','reportReason','costEstimate','priority'])if(!limits(v[k]??'',k==='description'||k==='notes'||k==='execution'||k==='resources'?5000:500))return reply('Champ invalide.');if(!/^UT\d{1,2}$/.test(v.unitCode||''))return reply('Unité invalide.');if(!actionStatuses.includes(v.status))return reply('Statut invalide.');if(!date(v.due||'')||!date(v.start||'')||!date(v.finished||''))return reply('Date invalide.');const programYear=Number(v.programYear||v.due?.slice(0,4)||v.registered?.slice(0,4)||now.slice(0,4));if(!Number.isInteger(programYear)||programYear<2020||programYear>2100)return reply('Année du programme invalide.');if(v.costEstimate&&(!/^\d{1,9}(?:[.,]\d{1,2})?$/.test(v.costEstimate)||Number(v.costEstimate.replace(',','.'))>999999999))return reply('Indiquez un coût estimatif positif en euros.');if(v.status==='Clôturée'&&(!v.effectiveness?.trim()||!v.effectivenessResult?.trim()||!v.owner?.trim()||!v.checker?.trim()||!v.finished))return reply('Pour clôturer : responsable, date de fin, critère, résultat et vérificateur sont requis.');const unit=await db.prepare('SELECT code FROM evrp_units WHERE code=?').bind(v.unitCode).first();if(!unit)return reply('Unité inconnue.');if(v.riskId){const risk=await db.prepare('SELECT unit_code FROM evrp_risks WHERE id=?').bind(v.riskId).first<{unit_code:string}>();if(!risk||risk.unit_code!==v.unitCode)return reply('Le risque lié doit appartenir à la même unité.')}const previous=body.id?await db.prepare('SELECT * FROM evrp_actions WHERE id=?').bind(body.id).first<any>():null;if(body.id&&!previous)return reply('Action introuvable.',404);if(previous&&(previous.revision!==body.revision||previous.unit_code!==v.unitCode))return reply('Action modifiée depuis son ouverture.',409);if(!v.description?.trim())return reply('Décrivez l’action.');const data=JSON.stringify({...previous?JSON.parse(previous.data):{},...v,programYear});if(previous){const result=await db.batch([db.prepare('INSERT INTO evrp_action_history (id,action_id,revision,snapshot,saved_at,saved_by) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),body.id,previous.revision,previous.data,now,author),db.prepare('UPDATE evrp_actions SET data=?,risk_id=?,revision=revision+1,updated_at=?,updated_by=? WHERE id=? AND revision=?').bind(data,v.riskId||'',now,author,body.id,previous.revision)]);if(!result[1].meta.changes)return reply('Modification concurrente.',409);return Response.json({id:body.id})}const id=crypto.randomUUID();await db.prepare('INSERT INTO evrp_actions (id,unit_code,risk_id,data,revision,updated_at,updated_by) VALUES (?,?,?,?,1,?,?)').bind(id,v.unitCode,v.riskId||'',data,now,author).run();return Response.json({id})}
if(body.action==='review'){if(!limits(body.description,2000)||!body.description.trim()||!date(body.date||''))return reply('Précisez la date et l’objet de la révision.');await db.prepare('INSERT INTO evrp_revisions (id,date,kind,description,author,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),body.date,'Révision',body.description.trim(),author,now).run();return Response.json({ok:true})}
return reply('Action inconnue.');}catch(e){console.error(e);return reply('Enregistrement impossible. Votre saisie reste affichée.',503)}}
