import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'polytechs-ged-')),sqlite=new DatabaseSync(':memory:');
function statement(sql,values=[]){return {bind(...args){return statement(sql,args)},async first(){return sqlite.prepare(sql).get(...values)||null},async all(){return {results:sqlite.prepare(sql).all(...values)}},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...values).changes)}}}}}
globalThis.gedTestDb={prepare:statement,async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const objects=new Map();globalThis.gedTestBucket={async put(key,data){objects.set(key,data)},async get(key){const body=objects.get(key);return body?{body}:null},async delete(key){objects.delete(key)}};
globalThis.gedTestUser={id:'author',displayName:'Auteur',role:'editor'};globalThis.gedTestAllowed=true;
function compile(name,source){for(const [from,to] of [['@/lib/hub','./hub.mjs'],['@/db/raw','./raw.mjs'],['@/lib/access','./access.mjs'],['@/lib/team-access','./teams.mjs'],['@/lib/ged-private-source','./source.mjs'],['@/lib/ged-server','./ged-server.mjs'],['@/lib/ged','./ged.mjs'],['@/lib/document-file','./document-file.mjs'],['./ged-private-source','./source.mjs'],['./ged','./ged.mjs']])source=source.replaceAll("'"+from+"'","'"+to+"'");fs.writeFileSync(path.join(dir,name+'.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText)}
try{
compile('hub',fs.readFileSync('lib/hub.ts','utf8'));compile('ged',fs.readFileSync('lib/ged.ts','utf8'));compile('document-file',fs.readFileSync('lib/document-file.ts','utf8'));
const {blankDocument,draftFrom,draftErrors}=await import(path.join(dir,'ged.mjs'));
const sourceDocument={...blankDocument(),id:'source-1',ref:'MO1-1500',index:'a',title:'Document du catalogue',catalogStatus:'Actif',sourceRow:12,sourceSheet:'LDA',raw:{D:'MO1-1500',F:'Document du catalogue'}};
fs.writeFileSync(path.join(dir,'source.mjs'),'export const gedSource='+JSON.stringify({source:'test.xlsx',records:[sourceDocument],history:[],headers:{}})+';');
fs.writeFileSync(path.join(dir,'raw.mjs'),'export const database=()=>globalThis.gedTestDb;export const bucket=()=>globalThis.gedTestBucket;');
fs.writeFileSync(path.join(dir,'access.mjs'),"export const checkOrigin=req=>req.headers.get('origin')===new URL(req.url).origin;export const requireRole=async(req,role='reader')=>role==='editor'&&globalThis.gedTestUser.role==='reader'?{error:Response.json({}, {status:403})}:{user:globalThis.gedTestUser};");
fs.writeFileSync(path.join(dir,'teams.mjs'),"export const teamsAllowed=async()=>globalThis.gedTestAllowed;export const someTeamAllowed=async()=>globalThis.gedTestAllowed;export const accessibleTeams=async()=>new Set(globalThis.gedTestAllowed?['qsse']:[]);");
compile('ged-server',fs.readFileSync('lib/ged-server.ts','utf8'));compile('route',fs.readFileSync('app/api/ged/route.ts','utf8'));compile('files',fs.readFileSync('app/api/ged-files/route.ts','utf8'));
sqlite.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT,display_name TEXT,role TEXT);CREATE TABLE team_members(user_id TEXT,team_id TEXT,level TEXT);CREATE TABLE records(id TEXT,title TEXT,kind TEXT,details TEXT,description TEXT,url TEXT,status TEXT);CREATE TABLE hub_notifications(id TEXT PRIMARY KEY,user_id TEXT,title TEXT,href TEXT,seen INTEGER,created_at TEXT);INSERT INTO users VALUES('author','author','Auteur','editor'),('reviewer','reviewer','Relecteur QSSE','editor'),('manager','manager','N+1','editor'),('admin','flavien','Administrateur','admin'),('reader','reader','Lecteur','reader');`);
sqlite.exec(fs.readFileSync('drizzle/0014_easy_sue_storm.sql','utf8').replaceAll('--> statement-breakpoint',''));
const api=await import(path.join(dir,'route.mjs')),files=await import(path.join(dir,'files.mjs'));
function actor(id,role='editor'){globalThis.gedTestUser={id,displayName:id,role}}
const post=body=>api.POST(new Request('https://example.test/api/ged',{method:'POST',headers:{origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify(body)}));
const get=id=>api.GET(new Request('https://example.test/api/ged'+(id?'?id='+id:'')));
const version=id=>{const r=sqlite.prepare('SELECT * FROM ged_versions WHERE id=?').get(id);return {...r,data:JSON.parse(r.data)}};
actor('admin','admin');assert.equal((await post({action:'profile',userId:'author',managerId:'manager',qsse:false})).status,200);assert.equal((await post({action:'profile',userId:'reviewer',managerId:'manager',qsse:true})).status,200);assert.equal((await post({action:'profile',userId:'manager',managerId:'author',qsse:false})).status,400);
actor('reader','reader');assert.equal((await post({action:'create-version',documentId:''})).status,403);
actor('author');const data={...draftFrom(sourceDocument,'author'),reviewerId:'reviewer',approverId:'manager',changeReason:'Intégration du document original'};
globalThis.gedTestAllowed=false;assert.equal((await post({action:'create-version',documentId:'source-1',data})).status,403);globalThis.gedTestAllowed=true;
const created=await post({action:'create-version',documentId:'source-1',data});assert.equal(created.status,200);const {versionId}=await created.json();let v=version(versionId);assert.equal((await post({action:'create-version',documentId:'source-1',data})).status,409);
assert.equal((await post({action:'submit',versionId,revision:v.revision})).status,400); // no document attached
const upload=async(id,revision,name='test.pdf',bytes='%PDF-1.7\nTest')=>{const f=new FormData();f.set('versionId',id);f.set('revision',String(revision));f.set('file',new File([bytes],name,{type:'application/pdf'}));return files.POST(new Request('https://example.test/api/ged-files',{method:'POST',headers:{origin:'https://example.test'},body:f}))};
assert.equal((await upload(versionId,v.revision,'fake.pdf','not a pdf')).status,400);const uploaded=await upload(versionId,v.revision);assert.equal(uploaded.status,200);const fileId=(await uploaded.json()).id;assert.equal(objects.size,1);assert.equal((await post({action:'submit',versionId,revision:v.revision})).status,409);v=version(versionId);
assert.equal((await post({action:'submit',versionId,revision:v.revision})).status,200);v=version(versionId);assert.equal(v.status,'Relecture QSSE');assert.equal((await upload(versionId,v.revision)).status,403);assert.equal((await post({action:'save-draft',versionId,revision:v.revision,data})).status,403);
actor('reader','reader');assert.equal((await files.GET(new Request('https://example.test/api/ged-files?id='+fileId))).status,403);const publicDetail=await (await get('source-1')).json();assert.equal(publicDetail.versions.length,0);assert.equal(publicDetail.files.length,0);
actor('manager');assert.equal((await post({action:'approve',versionId,revision:v.revision})).status,403);actor('reviewer');assert.equal((await post({action:'reject',versionId,revision:v.revision,note:''})).status,403);assert.equal((await post({action:'reject',versionId,revision:v.revision,note:'Préciser la consigne'})).status,200);v=version(versionId);assert.equal(v.status,'À corriger');
actor('author');assert.equal((await post({action:'save-draft',versionId,revision:v.revision,data:{...data,changeReason:'Consigne précisée'}})).status,200);v=version(versionId);assert.equal((await post({action:'submit',versionId,revision:v.revision})).status,200);v=version(versionId);
actor('reviewer');assert.equal((await files.GET(new Request('https://example.test/api/ged-files?id='+fileId))).status,200);assert.equal((await post({action:'review',versionId,revision:v.revision})).status,200);assert.equal((await post({action:'review',versionId,revision:v.revision})).status,409);v=version(versionId);assert.equal(v.reviewed_by,'reviewer');assert.equal((await post({action:'approve',versionId,revision:v.revision})).status,403);
actor('manager');assert.equal((await post({action:'approve',versionId,revision:v.revision})).status,200);v=version(versionId);assert.equal(v.status,'Approuvé');assert.equal(v.approved_by,'manager');assert.equal(sqlite.prepare('SELECT published_version_id FROM ged_documents WHERE id=?').get('source-1').published_version_id,versionId);
actor('reader','reader');assert.equal((await files.GET(new Request('https://example.test/api/ged-files?id='+fileId))).status,200);globalThis.gedTestAllowed=false;assert.equal((await files.GET(new Request('https://example.test/api/ged-files?id='+fileId))).status,403);globalThis.gedTestAllowed=true;
actor('author');assert.equal((await post({action:'save-draft',versionId,revision:v.revision,data})).status,403);const second=await post({action:'create-version',documentId:'source-1',data:{...data,index:'b',changeReason:'Amélioration'}});assert.equal(second.status,200);const secondId=(await second.json()).versionId;assert.equal(sqlite.prepare('SELECT published_version_id FROM ged_documents WHERE id=?').get('source-1').published_version_id,versionId);assert.equal((await upload(secondId,1)).status,200);let secondV=version(secondId);assert.equal((await post({action:'save-draft',versionId:secondId,revision:secondV.revision,data:{...data,index:'a'}})).status,200);secondV=version(secondId);assert.equal((await post({action:'submit',versionId:secondId,revision:secondV.revision})).status,400);assert.equal((await post({action:'abandon',versionId:secondId,revision:secondV.revision})).status,200);assert.equal(objects.size,2);
const users=[{id:'author',role:'editor',managerId:'manager',qsse:false},{id:'manager',role:'editor',managerId:'',qsse:true}];assert.ok(draftErrors({...data,reviewerId:'author'},users,true).length);assert.ok(sqlite.prepare("SELECT count(*) n FROM ged_events WHERE action='Approbation N+1'").get().n===1);assert.ok(sqlite.prepare('SELECT count(*) n FROM hub_notifications').get().n>=4);
if(fs.existsSync('private/ged-source.json')){const src=JSON.parse(fs.readFileSync('private/ged-source.json','utf8'));assert.equal(src.records.length,1319);assert.equal(src.records.filter(d=>d.sourceSheet==='LDA').length,795);assert.equal(src.records.filter(d=>d.sourceArchive).length,524);assert.equal(new Set(src.records.map(d=>d.id)).size,1319);assert.ok(src.records.some(d=>d.sourceArchive&&d.issues.some(i=>i.includes('marqué actif'))));}
console.log('GED : catalogue, droits, N+1, relecture QSSE, retours pour correction, fichiers figés, versions applicables et conflits vérifiés.');
}finally{sqlite.close();fs.rmSync(dir,{recursive:true,force:true})}
