import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import ts from 'typescript';import {DatabaseSync} from 'node:sqlite';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'polytechs-gmao-')),db=new DatabaseSync(':memory:');
function stmt(sql,args=[]){return {bind(...v){return stmt(sql,v)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}}}
globalThis.gmaoDb={prepare:stmt,async batch(ss){db.exec('BEGIN');try{const out=[];for(const s of ss)out.push(await s.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
const users={admin:{id:'admin',username:'admin',displayName:'Admin',role:'admin'},tech:{id:'tech',username:'tech',displayName:'Technicien',role:'editor'},requester:{id:'requester',username:'requester',displayName:'Demandeur',role:'editor'},other:{id:'other',username:'other',displayName:'Autre service',role:'editor'},reader:{id:'reader',displayName:'Lecteur',role:'reader'}};
globalThis.gmaoUser=users.admin;globalThis.gmaoOrigin=true;
const blobs=new Map();globalThis.gmaoBucket={async put(k,v){blobs.set(k,v)},async delete(k){blobs.delete(k)},async get(k){return blobs.has(k)?{body:blobs.get(k)}:null}};
function compile(name,filename){let s=fs.readFileSync(filename,'utf8');for(const [a,b] of [['@/lib/document-file','./document-file.mjs'],['@/db/raw','./raw.mjs'],['@/lib/access','./access.mjs'],['@/lib/team-access','./teams.mjs'],['@/lib/gmao-server','./gmao-server.mjs'],['@/lib/gmao','./gmao.mjs'],['@/lib/hub','./hub.mjs'],['@/app/api/ged/route','./ged.mjs'],['./team-access','./teams.mjs'],['./hub','./hub.mjs']])s=s.replaceAll("'"+a+"'","'"+b+"'");fs.writeFileSync(path.join(dir,name+'.mjs'),ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText)}
try{
fs.writeFileSync(path.join(dir,'raw.mjs'),'export const database=()=>globalThis.gmaoDb;export const bucket=()=>globalThis.gmaoBucket;');
fs.writeFileSync(path.join(dir,'access.mjs'),`export const checkOrigin=()=>globalThis.gmaoOrigin;export const requireRole=async(req,role)=>role==='editor'&&globalThis.gmaoUser.role==='reader'?{error:Response.json({error:'reader'},{status:403})}:{user:globalThis.gmaoUser};`);
fs.writeFileSync(path.join(dir,'ged.mjs'),`export const GET=async()=>Response.json({error:'inaccessible'},{status:404});`);
compile('document-file','lib/document-file.ts');compile('teams','lib/team-access.ts');compile('hub','lib/hub.ts');compile('gmao','lib/gmao.ts');compile('gmao-server','lib/gmao-server.ts');compile('route','app/api/gmao/route.ts');compile('hub-route','app/api/hub/route.ts');compile('file-route','app/api/ticket-files/route.ts');
db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE teams(id TEXT PRIMARY KEY,name TEXT,rank INTEGER,parent_id TEXT);CREATE TABLE team_access(team_id TEXT,restricted INTEGER);CREATE TABLE team_members(team_id TEXT,user_id TEXT,level TEXT);CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT,display_name TEXT,role TEXT);CREATE TABLE hub_tickets(id TEXT PRIMARY KEY,data TEXT,revision INTEGER,created_at TEXT,updated_at TEXT,author TEXT);CREATE TABLE hub_comments(id TEXT PRIMARY KEY,ticket_id TEXT,body TEXT,author_id TEXT,author TEXT,created_at TEXT);CREATE TABLE hub_notifications(id TEXT PRIMARY KEY,user_id TEXT,title TEXT,href TEXT,seen INTEGER,created_at TEXT);CREATE TABLE hub_files(id TEXT PRIMARY KEY,ticket_id TEXT,name TEXT,mime TEXT,size INTEGER,author TEXT,created_at TEXT);INSERT INTO teams VALUES('maintenance','Maintenance',2,'direction'),('production','Production',2,'direction'),('rd','R&D',2,'direction');INSERT INTO team_access VALUES('maintenance',1),('production',1),('rd',1);INSERT INTO team_members VALUES('maintenance','tech','contributor'),('production','requester','contributor'),('rd','other','contributor');`);
for(const u of Object.values(users))db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(u.id,u.username||u.id,u.displayName,u.role);
db.exec(fs.readFileSync('drizzle/0016_chubby_the_santerians.sql','utf8').replaceAll('--> statement-breakpoint',''));
const api=await import(path.join(dir,'route.mjs')),hub=await import(path.join(dir,'hub-route.mjs')),file=await import(path.join(dir,'file-route.mjs')),lib=await import(path.join(dir,'gmao.mjs'));
const post=(handler,b)=>handler.POST(new Request('https://example.test/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)}));
async function result(b,status=200){const r=await post(api,b),v=await r.json();assert.equal(r.status,status,JSON.stringify(v));return v}
const row=(kind,id)=>{const r=db.prepare('SELECT * FROM gmao_'+kind+' WHERE id=?').get(id);return {...r,data:JSON.parse(r.data)}};
async function editOrder(id,patch){const r=row('orders',id);return result({operation:'order',id,revision:r.revision,data:{...r.data,...patch}})}
async function step(id,to,status=200){return result({operation:'transition',id,revision:row('orders',id).revision,to,note:'Résultat contrôlé'},status)}
assert.deepEqual(lib.planDates({...lib.newPlan(),active:true,start:'2028-01-31'},'2028-01-01','2028-03-31'),['2028-01-31','2028-02-29','2028-03-31']);
globalThis.gmaoOrigin=false;await result({operation:'request'},403);globalThis.gmaoOrigin=true;globalThis.gmaoUser=users.reader;await result({operation:'request'},403);
globalThis.gmaoUser=users.requester;await result({operation:'asset',id:'',revision:0,data:lib.newAsset()},403);await result({operation:'request',data:{...lib.newOrder(),teamId:'rd',title:'Test',description:'Test'}},403);
const request=await result({operation:'request',data:{...lib.newOrder(),title:'Fuite sur pompe',description:'Fuite constatée',status:'Clôturée',requesterId:'admin'}}),id=request.id;
assert.equal(row('orders',id).data.status,'À qualifier');assert.equal(row('orders',id).data.requesterId,'requester');await step(id,'À planifier',403);
assert.equal((await post(hub,{action:'comment',ticketId:request.ticketId,body:'Photo à suivre',recipients:[]})).status,200);
const f=new FormData();f.set('ticketId',request.ticketId);f.set('file',new File(['%PDF-test'],'constat.pdf'));assert.equal((await file.POST(new Request('https://example.test/api',{method:'POST',body:f}))).status,200);
let t=db.prepare('SELECT * FROM hub_tickets WHERE id=?').get(request.ticketId);assert.equal((await post(hub,{action:'ticket',id:t.id,revision:t.revision,data:{...JSON.parse(t.data),status:'En cours'}})).status,409);
assert.equal((await (await hub.GET(new Request('https://example.test/api?scope=ticket&id='+t.id))).json()).gmaoContributor,true);
globalThis.gmaoUser=users.other;assert.equal((await api.GET(new Request('https://example.test/api?id='+id))).status,404);assert.equal((await post(hub,{action:'comment',ticketId:request.ticketId,body:'Interdit',recipients:[]})).status,403);
globalThis.gmaoUser=users.tech;await step(id,'À planifier');await step(id,'En cours',400);await editOrder(id,{technicianId:'tech',scheduled:'2026-10-02',safety:'Consigner et vérifier l’absence d’énergie'});assert.equal((await file.GET(new Request('https://example.test/api?id='+db.prepare('SELECT id FROM hub_files').get().id))).status,200);await step(id,'Planifiée');await step(id,'En cours');await step(id,'À vérifier',400);
await editOrder(id,{report:'Joint remplacé',result:'Contrôle sans fuite',hours:1.5,externalCost:null});await step(id,'À vérifier');
globalThis.gmaoUser=users.requester;await step(id,'Clôturée');assert.equal(row('orders',id).data.closedBy,'Demandeur');const closedTicket=db.prepare('SELECT * FROM hub_tickets WHERE id=?').get(t.id);assert.equal((await post(hub,{action:'ticket',id:closedTicket.id,revision:closedTicket.revision,data:{...JSON.parse(closedTicket.data),actions:[{id:'new-task',title:'Rouvrir sans GMAO',done:false,pilot:'tech',due:''}]}})).status,400);assert.equal(JSON.parse(db.prepare('SELECT data FROM hub_tickets WHERE id=?').get(t.id).data).status,'Clôturé');
globalThis.gmaoUser=users.tech;const locked=db.prepare('SELECT * FROM hub_tickets WHERE id=?').get(t.id);assert.equal((await post(hub,{action:'ticket',id:locked.id,revision:locked.revision,data:{...JSON.parse(locked.data),actions:[{id:'new-task',title:'Ajout après clôture',done:true,pilot:'tech',due:''}]}})).status,409);await result({operation:'reopen',id,revision:row('orders',id).revision,note:''},400);await result({operation:'reopen',id,revision:row('orders',id).revision,note:'Fuite revenue'});assert.equal(row('orders',id).data.closedAt,'');
const old=row('orders',id);await editOrder(id,{priority:'Haute'});await result({operation:'order',id,revision:old.revision,data:old.data},409);
const a=await result({operation:'asset',id:'',revision:0,data:{...lib.newAsset(),code:'P-01',name:'Pompe',teamId:'production'}});await result({operation:'asset',id:a.id,revision:1,data:{...row('assets',a.id).data,parentId:a.id}},400);await result({operation:'asset',id:'',revision:0,data:{...row('assets',a.id).data}},409);
const p=await result({operation:'plan',id:'',revision:0,data:{...lib.newPlan(),name:'Contrôle mensuel',assetId:a.id,start:'2026-10-01',technicianId:'tech',tasks:['Vérifier le joint','Vérifier les vibrations']}});
let generation=await result({operation:'generate',from:'2026-10-01',to:'2026-11-30'});assert.equal(generation.created,2);generation=await result({operation:'generate',from:'2026-10-01',to:'2026-11-30'});assert.equal(generation.created,0);assert.equal(generation.existing,2);await result({operation:'generate',from:'2026-10-01',to:'2027-01-01'},400);
await result({operation:'plan',id:p.id,revision:1,data:{...row('plans',p.id).data,start:'2026-10-02'}},400);const preventive=db.prepare('SELECT id FROM gmao_orders WHERE plan_id=? ORDER BY occurrence').get(p.id).id;await editOrder(preventive,{safety:'Consignation',report:'Contrôlé',result:'Conforme',hours:1});await step(preventive,'En cours');await step(preventive,'À vérifier',400);const checklist=row('orders',preventive).data.checklist.map(c=>({...c,done:true}));await editOrder(preventive,{checklist});await step(preventive,'À vérifier');
await result({operation:'part',id:'',revision:0,data:{...lib.newPart(),code:'J-01',name:'Joint'}},400);const part=await result({operation:'part',id:'',revision:0,quantity:2.5,data:{...lib.newPart(),code:'J-01',name:'Joint',minimum:1}});await result({operation:'stock',partId:part.id,revision:1,kind:'Sortie intervention',amount:3,orderId:id,note:'Test'},400);await result({operation:'stock',partId:part.id,revision:1,kind:'Sortie intervention',amount:.5,orderId:id,note:'Joint changé'});assert.equal(row('parts',part.id).quantity,2);assert.equal(db.prepare('SELECT unit_cost FROM gmao_movements WHERE order_id=?').get(id).unit_cost,null);await result({operation:'stock',partId:part.id,revision:1,kind:'Entrée',amount:1,note:'Livraison'},409);await result({operation:'stock',partId:part.id,revision:2,kind:'Ajustement',amount:0,note:'Inventaire : plus de stock'});assert.equal(row('parts',part.id).quantity,0);
await result({operation:'part',id:part.id,revision:3,data:{...row('parts',part.id).data,name:'Joint standard'},quantity:100});assert.equal(row('parts',part.id).quantity,0);
await step(preventive,'Clôturée');await result({operation:'stock',partId:part.id,revision:4,kind:'Sortie intervention',amount:1,orderId:preventive,note:'Test'},400);
assert.ok(db.prepare('SELECT count(*) n FROM gmao_history WHERE entity_id=?').get(id).n>5);assert.ok(db.prepare('SELECT count(*) n FROM hub_notifications WHERE user_id=?').get('requester').n>=2);
// A ticket edit racing between read and transaction must abort the GMAO mutation without losing the edit.
const origBatch=globalThis.gmaoDb.batch;let raced=false;globalThis.gmaoDb.batch=async ss=>{if(!raced){raced=true;db.prepare('UPDATE hub_tickets SET revision=revision+1 WHERE id=?').run(request.ticketId)}return origBatch(ss)};const before=row('orders',id);await result({operation:'order',id,revision:before.revision,data:{...before.data,title:'Tentative simultanée'}},409);assert.equal(row('orders',id).data.title,before.data.title);globalThis.gmaoDb.batch=origBatch;
console.log('GMAO : droits par service, demandes/tickets/fichiers, workflow et contrôle, historique, conflits concurrents, préventif sans doublons, fin de mois et stock fractionnaire vérifiés.');
}finally{db.close();fs.rmSync(dir,{recursive:true,force:true})}
