import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';import {pbkdf2Sync} from 'node:crypto';import ts from 'typescript';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'qse-security-')),db=new DatabaseSync(':memory:');
function stmt(sql,args=[]){return {bind(...v){return stmt(sql,v)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}}}
globalThis.securityDb={prepare:stmt,async batch(ss){db.exec('BEGIN');try{const out=[];for(const s of ss)out.push(await s.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};globalThis.securityTrust=true;
function compile(name,file){let s=fs.readFileSync(file,'utf8');if(name==='xlsx')s+='\nexport {zip};';for(const [a,b] of [['@/lib/gmao-server','./gmao-server.mjs'],['@/lib/quality-server','./quality-server.mjs'],['@/lib/quality-actions','./quality-actions.mjs'],['@/lib/hub','./hub.mjs'],['@/db/raw','./raw.mjs'],['@/lib/access','./access.mjs'],['./auth-config','./config.mjs'],['./team-access','./teams.mjs'],['@/lib/team-access','./teams.mjs'],['@/lib/record-access','./records-access.mjs'],['@/lib/workflows','./workflows.mjs'],['./hub','./hub.mjs'],['./modules','./modules.mjs'],['@/lib/evrp','./evrp.mjs'],['@/lib/evrp-private-source','./source.mjs'],['@/lib/epi-private-source','./catalog.mjs'],['@/lib/unit-dashboard','./unit-dashboard.mjs']])s=s.replaceAll("'"+a+"'","'"+b+"'");fs.writeFileSync(path.join(dir,name+'.mjs'),ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText)}
try{
fs.symlinkSync(path.resolve('node_modules'),path.join(dir,'node_modules'),'dir');
fs.writeFileSync(path.join(dir,'raw.mjs'),'export const database=()=>globalThis.securityDb;export const bucket=()=>{throw Error("Unexpected storage")};');fs.writeFileSync(path.join(dir,'config.mjs'),'export const trustSiteIdentity=()=>globalThis.securityTrust;');fs.writeFileSync(path.join(dir,'source.mjs'),'export const evrpSource=null;');fs.writeFileSync(path.join(dir,'catalog.mjs'),'export const epiCatalog={items:[],source:"",duplicateRows:[]};');
fs.writeFileSync(path.join(dir,'gmao-server.mjs'),'export const gmaoOrders=async()=>[];');fs.writeFileSync(path.join(dir,'quality-server.mjs'),'export const qualityActions=async()=>new Map();');
for(const [name,file] of [['work','app/api/work/route.ts'],['hub','lib/hub.ts'],['quality-actions','lib/quality-actions.ts'],['access','lib/access.ts'],['teams','lib/team-access.ts'],['records-access','lib/record-access.ts'],['auth','app/api/auth/route.ts'],['users','app/api/users/route.ts'],['files','lib/document-file.ts'],['xlsx','lib/xlsx-export.ts'],['modules','lib/modules.ts'],['workflows','lib/workflows.ts'],['records','app/api/records/route.ts'],['evrp','lib/evrp.ts'],['evrp-route','app/api/evrp/route.ts'],['epi','app/api/epi-stock/route.ts'],['unit-dashboard','lib/unit-dashboard.ts'],['boards','app/api/dashboards/route.ts']])compile(name,file);
// Apply the real additive security migration against existing accounts and teams.
db.exec(fs.readFileSync(fs.readdirSync('drizzle').filter(x=>x.startsWith('0003_')).map(x=>'drizzle/'+x)[0],'utf8'));
db.exec(`CREATE TABLE teams(id TEXT PRIMARY KEY,name TEXT,rank INTEGER);CREATE TABLE team_access(team_id TEXT PRIMARY KEY,restricted INTEGER);CREATE TABLE team_members(team_id TEXT,user_id TEXT,level TEXT);INSERT INTO teams VALUES('qsse','QSSE',2),('rh','RH',2),('production','Production',2);CREATE TABLE records(id TEXT PRIMARY KEY,title TEXT,kind TEXT,source_id TEXT,details TEXT,created TEXT);CREATE TABLE record_history(id TEXT,record_id TEXT,revision INTEGER,snapshot TEXT,saved_at TEXT);CREATE TABLE team_dashboards(id TEXT,team_id TEXT,unit_code TEXT,data TEXT,revision INTEGER,updated_at TEXT,updated_by TEXT);INSERT INTO team_dashboards VALUES('production-board','production','*','{"widgets":[]}',2,'','');`);
db.exec(fs.readFileSync('drizzle/0018_chemical_inhumans.sql','utf8'));
assert.equal(db.prepare("SELECT restricted FROM team_access WHERE team_id='qsse'").get().restricted,1);
const auth=await import(path.join(dir,'auth.mjs')),access=await import(path.join(dir,'access.mjs')),users=await import(path.join(dir,'users.mjs')),records=await import(path.join(dir,'records.mjs')),evrp=await import(path.join(dir,'evrp-route.mjs')),epi=await import(path.join(dir,'epi.mjs')),boards=await import(path.join(dir,'boards.mjs'));
const site={'oai-authenticated-user-id':'test-stable-identity','oai-authenticated-user-email':'admin@example.test'};
const req=(headers={})=>new Request('https://example.test/api',{headers});
const post=(api,body,headers={})=>api.POST(new Request('https://example.test/api',{method:'POST',headers:{origin:'https://example.test','content-type':'application/json',...headers},body:JSON.stringify(body)}));
assert.equal((await (await auth.GET(req(site))).json()).account,null);assert.equal(db.prepare('SELECT count(*) n FROM users').get().n,0,'Reading auth must never provision predictable admins');
const password='A test-only password 987!',salt='12'.repeat(16),oldHash='pbkdf2:100000:'+salt+':'+pbkdf2Sync(password,Buffer.from(salt,'hex'),100000,32,'sha256').toString('hex');
for(const [id,role] of [['admin','admin'],['editor','editor'],['reader','reader']])db.prepare('INSERT INTO users VALUES(?,?,?,?,?,0,?)').run(id,id,id,role,oldHash,'2026-01-01');
assert.equal(await access.currentUser(req(site)),null,'A trusted but unlinked identity grants no account');assert.equal(await access.currentUser(req({'oai-authenticated-user-email':'admin@example.test'})),null);
assert.equal((await post(auth,{action:'login',username:'admin',password},{origin:'https://evil.test'})).status,403);
const login=await post(auth,{action:'login',username:'admin',password},site);assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=None; Partitioned/);assert.match(db.prepare("SELECT password_hash FROM users WHERE id='admin'").get().password_hash,/^pbkdf2:600000:/);assert.equal((await access.currentUser(req(site))).role,'admin');
globalThis.securityTrust=false;assert.equal(await access.currentUser(req(site)),null);assert.equal((await access.currentUser(req({cookie}))).id,'admin');globalThis.securityTrust=true;
await post(auth,{action:'logout'}, {...site,cookie});assert.equal(await access.currentUser(req(site)),null);assert.equal(await access.currentUser(req({cookie})),null);
// Cloudflare's WebCrypto iteration cap must use a compatible 600k fallback.
const derive=crypto.subtle.deriveBits;crypto.subtle.deriveBits=async()=>{throw new Error('PBKDF2 iteration counts above 100000 are not supported')};try{assert.equal(await access.checkPassword(password,db.prepare("SELECT password_hash FROM users WHERE id='admin'").get().password_hash),true)}finally{crypto.subtle.deriveBits=derive}
for(let i=0;i<5;i++)assert.equal((await post(auth,{action:'login',username:'unknown',password:'bad'})).status,401);assert.equal((await post(auth,{action:'login',username:'unknown',password:'bad'})).status,429);
const editorLogin=await post(auth,{action:'login',username:'editor',password},site),editorCookie=editorLogin.headers.get('set-cookie').split(';')[0];
assert.equal((await evrp.GET(req({cookie:editorCookie}))).status,403);assert.equal((await epi.GET(req({cookie:editorCookie}))).status,403);assert.equal((await post(evrp,{}, {cookie:editorCookie})).status,403);assert.equal((await post(epi,{}, {cookie:editorCookie})).status,403);
const b=await boards.GET(new Request('https://example.test/api?id=production-board',{headers:{cookie:editorCookie}}));assert.equal(b.status,200);assert.deepEqual((await b.json()).risks,[],'No sensitive SQL query or risk data when QSSE is denied');
db.exec(`INSERT INTO records VALUES('health','Health secret','Accidents du travail','','{}','2026'),('derived','Derived health','Action','health','{}','2026'),('normal','Ordinary QSE','Action','','{}','2026');`);
assert.equal((await (await records.GET(req({cookie:editorCookie}))).json()).records.length,0);
db.exec(`CREATE TABLE evrp_actions(id TEXT,unit_code TEXT,risk_id TEXT,data TEXT,updated_at TEXT);CREATE TABLE hub_tickets(id TEXT,data TEXT,updated_at TEXT);CREATE TABLE hub_routines(id TEXT,data TEXT,updated_at TEXT);CREATE TABLE hub_runs(routine_id TEXT,date TEXT,data TEXT);INSERT INTO evrp_actions VALUES('risk-action','UT1','risk','{"description":"Risk secret"}','');`);
const work=await import(path.join(dir,'work.mjs'));assert.deepEqual((await (await work.GET(req({cookie:editorCookie}))).json()).items,[]);
db.exec("UPDATE team_access SET restricted=0 WHERE team_id='qsse'");const aggregate=(await (await work.GET(req({cookie:editorCookie}))).json()).items;assert.ok(aggregate.some(i=>i.id==='record:normal'));assert.ok(!aggregate.some(i=>i.id==='record:derived'),'Aggregate must not reveal actions derived from an AT, even in an open QSSE service');db.exec("UPDATE team_access SET restricted=1 WHERE team_id='qsse'");
db.exec("INSERT INTO team_members VALUES('qsse','editor','viewer')");
const readable=(await (await records.GET(req({cookie:editorCookie}))).json()).records;assert.equal(readable.length,3);
const {recordAccess}=await import(path.join(dir,'records-access.mjs'));const all=db.prepare('SELECT * FROM records').all();assert.equal((await recordAccess({id:'editor',role:'editor'},all,true))(all[0]),false);db.exec("UPDATE team_members SET level='contributor'");assert.equal((await recordAccess({id:'editor',role:'editor'},all,true))(all[0]),true);assert.equal((await recordAccess({id:'reader',role:'reader'},all))(all[0]),false);assert.equal((await recordAccess({id:'editor',role:'editor'},all))({sourceId:'missing'}),false);
const adminLogin=await post(auth,{action:'login',username:'admin',password}),adminCookie=adminLogin.headers.get('set-cookie').split(';')[0];assert.equal((await post(users,{action:'role',id:'editor',role:'reader'},{cookie:adminCookie})).status,200);assert.equal(await access.currentUser(req({cookie:editorCookie})),null);assert.equal(await access.currentUser(req(site)),null,'Role changes revoke both authentication transports');
const before=db.prepare('SELECT count(*) n FROM users').get().n;await auth.GET(req());assert.equal(db.prepare('SELECT count(*) n FROM users').get().n,before);
const {documentMime}=await import(path.join(dir,'files.mjs')),{workbook,zip}=await import(path.join(dir,'xlsx.mjs'));const xlsx=workbook([{name:'Safe',rows:[['Test'],['value']]}]);assert.match(documentMime('test.xlsx',xlsx),/spreadsheetml/);assert.equal(documentMime('fake.xlsx',new Uint8Array([80,75,3,4,0,0])), '');assert.equal(documentMime('old.xls',new Uint8Array([208,207,17,224,161,177,26,225])), '');assert.equal(documentMime('fake.docx',xlsx),'');const malformed=xlsx.slice();new DataView(malformed.buffer).setUint32(malformed.length-6,0xffffffff,true);assert.equal(documentMime('bad.xlsx',malformed),'');
const parts=[['[Content_Types].xml','<Types/>'],['_rels/.rels','<Relationships/>'],['word/document.xml','<document/>']];assert.match(documentMime('valid.docx',zip(parts)),/wordprocessingml/);assert.equal(documentMime('macro.docx',zip([...parts,['word/vbaProject.bin','test']])),'');assert.equal(documentMime('traversal.docx',zip([...parts,['../escape','test']])),'');const bomb=zip(parts);const v=new DataView(bomb.buffer),start=v.getUint32(bomb.length-6,true);v.setUint32(start+24,0x7fffffff,true);assert.equal(documentMime('bomb.docx',bomb),'');
assert.ok(db.prepare('SELECT count(*) n FROM security_events').get().n>0);
console.log('Security: password migration/fallback, no bootstrap or email bypass, identity trust, logout/revocation, throttling, AT inheritance, QSSE API/export/dashboard isolation, Office validation passed.');
}finally{db.close();fs.rmSync(dir,{recursive:true,force:true});delete globalThis.securityDb;delete globalThis.securityTrust}
