import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
import {execFileSync} from 'node:child_process';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'polytechs-smi-')),sql=new DatabaseSync(':memory:');
function statement(q,args=[]){return {bind(...a){return statement(q,a)},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:Number(sql.prepare(q).run(...args).changes)}}}}}
globalThis.smiDB={prepare:statement,async batch(ss){sql.exec('BEGIN');try{const out=[];for(const s of ss)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.smiUser={id:'admin',displayName:'Admin',role:'admin'};
const mappings={'@/lib/ged-private-source':'source','@/db/raw':'raw','@/lib/access':'access','@/lib/team-access':'teams','@/lib/ged-server':'ged-server','@/lib/ged':'ged','@/lib/smi-server':'smi-server','@/lib/smi':'smi','@/lib/hub':'hub','@/lib/xlsx-export':'xlsx','@/app/api/ged/route':'ged-route','@/app/api/work/route':'work','./ged-private-source':'source','./ged':'ged','./team-access':'teams','./ged-server':'ged-server','./smi':'smi','./smi-seed':'smi-seed','./hub':'hub'};
function compile(name,file){let src=fs.readFileSync(file,'utf8');for(const [key,value] of Object.entries(mappings))src=src.replaceAll("'"+key+"'","'./"+value+".mjs'");fs.writeFileSync(path.join(dir,name+'.mjs'),ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText)}
try{
fs.writeFileSync(path.join(dir,'raw.mjs'),'export const database=()=>globalThis.smiDB;');
fs.writeFileSync(path.join(dir,'access.mjs'),`export const checkOrigin=req=>req.headers.get('origin')===new URL(req.url).origin;export const requireRole=async(req,role='reader')=>!globalThis.smiUser?{error:Response.json({}, {status:401})}:role==='editor'&&globalThis.smiUser.role==='reader'?{error:Response.json({}, {status:403})}:{user:globalThis.smiUser};`);
fs.writeFileSync(path.join(dir,'work.mjs'),`export const GET=async()=>Response.json({items:[{id:'ticket-1',source:'Ticket',title:'Écart de test',status:'Ouvert',href:'/tickets?ticket=ticket-1',due:'2027-01-01'}]});`);
for(const [name,file] of Object.entries({'ged':'lib/ged.ts','hub':'lib/hub.ts','teams':'lib/team-access.ts','ged-server':'lib/ged-server.ts','ged-route':'app/api/ged/route.ts','smi':'lib/smi.ts','smi-seed':'lib/smi-seed.ts','smi-server':'lib/smi-server.ts','route':'app/api/smi/route.ts','xlsx':'lib/xlsx-export.ts','export':'app/api/smi/export/route.ts'}))compile(name,file);
const {blankDocument,draftFrom}=await import(path.join(dir,'ged.mjs'));
const source={...blankDocument(),id:'source',ref:'GED-01',title:'Procédure GED',process:'M2',catalogStatus:'Actif',sourceSheet:'LDA'};
fs.writeFileSync(path.join(dir,'source.mjs'),'export const gedSource='+JSON.stringify({records:[source],headers:{}})+';');
sql.exec(`PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT,display_name TEXT,role TEXT);CREATE TABLE teams(id TEXT PRIMARY KEY,name TEXT,rank INTEGER);CREATE TABLE team_members(user_id TEXT,team_id TEXT,level TEXT);CREATE TABLE team_access(team_id TEXT,restricted INTEGER);CREATE TABLE records(id TEXT,title TEXT,kind TEXT,details TEXT,description TEXT,url TEXT,status TEXT);CREATE TABLE hub_notifications(id TEXT PRIMARY KEY,user_id TEXT,title TEXT,href TEXT,seen INTEGER,created_at TEXT);CREATE TABLE hub_routines(id TEXT,data TEXT);CREATE TABLE hub_runs(id TEXT,routine_id TEXT,date TEXT,data TEXT);INSERT INTO users VALUES('admin','admin','Admin','admin'),('author','author','Auteur','editor'),('reader','reader','Lecteur','reader'),('reviewer','reviewer','QSSE','editor'),('manager','manager','Manager','editor');INSERT INTO teams VALUES('qsse','QSSE',2),('production','Production',2);INSERT INTO team_access VALUES('qsse',1);INSERT INTO team_members VALUES('author','qsse','contributor'),('reader','qsse','viewer');`);
for(const file of ['0014_easy_sue_storm.sql','0017_last_jocasta.sql'])sql.exec(fs.readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));
const api=await import(path.join(dir,'route.mjs')),ged=await import(path.join(dir,'ged-route.mjs')),xlsx=await import(path.join(dir,'export.mjs')),{coverage,smiView,emptyFilters,exportMatrix}=await import(path.join(dir,'smi.mjs'));
const request=(body,url='/api/smi',origin='https://example.test')=>new Request('https://example.test'+url,{method:body?'POST':'GET',headers:{origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const post=b=>api.POST(request(b)),data=async()=>{const r=await api.GET(request());assert.equal(r.status,200);return r.json()};
let d=await data();assert.equal(d.standards.length,3);assert.equal(d.requirements.length,72);assert.equal(d.documents.length,1);assert.equal(d.links.length,3);assert.ok(d.links.every(l=>l.confirmed===0));assert.equal(sql.prepare('SELECT count(*) n FROM ged_documents').get().n,0);assert.equal(coverage(d.links[0].requirement_id,d.links,d.documents),0);
const reqs=d.links.map(l=>l.requirement_id),setLink=(rid,revision,confirmed)=>post({operation:'link',documentId:'source',requirementId:rid,revision,confirmed,note:'Preuve vérifiée'});
assert.equal((await api.POST(request({operation:'link'},'/api/smi','https://foreign.test'))).status,403);
globalThis.smiUser={id:'reader',displayName:'Lecteur',role:'reader'};assert.equal((await setLink(reqs[0],0,1)).status,403);assert.equal((await data()).documents[0].canEdit,false);
globalThis.smiUser={id:'outsider',displayName:'Autre service',role:'editor'};assert.equal((await data()).documents.length,0);assert.equal((await api.GET(request(null,'/api/smi?document=source'))).status,404);assert.equal((await setLink(reqs[0],0,1)).status,404);
globalThis.smiUser={id:'author',displayName:'Auteur',role:'editor'};
assert.equal((await setLink(reqs[0],0,1)).status,200);assert.equal((await setLink(reqs[0],0,1)).status,409);assert.equal(sql.prepare('SELECT count(*) n FROM ged_documents').get().n,1);
assert.equal((await setLink(reqs[0],1,-1)).status,200);d=await data();assert.ok(!d.links.some(l=>l.requirement_id===reqs[0]));assert.equal(d.removedLinks[0].revision,2);assert.equal((await setLink(reqs[0],2,1)).status,200);
for(const rid of reqs.slice(1))assert.equal((await setLink(rid,0,1)).status,200);
d=await data();assert.equal(d.documents[0].norms.length,3);const detail=await api.GET(request(null,'/api/smi?document=source'));assert.equal(detail.status,200);assert.equal((await detail.json()).ged.document.id,'source');assert.equal(sql.prepare('SELECT count(*) n FROM ged_documents').get().n,1);assert.equal(coverage(reqs[0],d.links,d.documents),50);
const draft={...draftFrom(source,'author'),ref:'NEW-01',title:'Formation test',reviewerId:'reviewer',approverId:'manager',index:'1',changeReason:'Création',nextReview:'2027-04-01'};
assert.equal((await post({operation:'create-document',data:{...draft,nextReview:'2027-02-31'},requirements:reqs})).status,400);
assert.equal((await post({operation:'create-document',data:draft,requirements:['unknown']})).status,400);assert.equal(sql.prepare('SELECT count(*) n FROM ged_documents').get().n,1);
const created=await post({operation:'create-document',data:draft,requirements:reqs});assert.equal(created.status,200);const newDoc=await created.json();assert.equal(sql.prepare('SELECT count(*) n FROM smi_document_links WHERE document_id=?').get(newDoc.id).n,3);assert.equal(sql.prepare('SELECT count(*) n FROM ged_documents').get().n,2);
assert.equal((await post({operation:'create-document',data:draft,requirements:reqs})).status,409);
const v=sql.prepare('SELECT * FROM ged_versions WHERE id=?').get(newDoc.versionId);assert.equal((await ged.POST(request({action:'save-draft',versionId:v.id,revision:v.revision,data:{...draft,title:'Formation actualisée'}},'/api/ged'))).status,200);
d=await data();assert.equal(d.documents.find(x=>x.id===newDoc.id).title,'Formation actualisée');assert.equal(d.documents.find(x=>x.id===newDoc.id).nextReview,'2027-04-01');
// Publish a fixture version; the full approval/file circuit is separately exercised by tests/ged.mjs.
sql.prepare("UPDATE ged_versions SET status='Approuvé' WHERE id=?").run(v.id);sql.prepare('UPDATE ged_documents SET published_version_id=? WHERE id=?').run(v.id,newDoc.id);sql.prepare('INSERT INTO ged_files VALUES(?,?,?,?,?,?,?,?)').run('file',v.id,'preuve.pdf','application/pdf',10,'sha','author','2026-01-01');
d=await data();const ready=d.documents.find(x=>x.id===newDoc.id);assert.equal(ready.status,'Validé');assert.equal(coverage(reqs[0],d.links,d.documents),75);
const filtered=smiView(d,{...emptyFilters,status:'Validé'});assert.ok(filtered.some(g=>g.percent===75));assert.ok(smiView(d,{...emptyFilters,search:'formation ACTUALISEE'}).some(g=>g.documents.some(x=>x.id===newDoc.id)));assert.ok(smiView(d,{...emptyFilters,search:'NEW-01'}).length);assert.ok(smiView(d,{...emptyFilters,search:'QSSE'}).length);assert.equal(smiView(d,{...emptyFilters,search:'introuvableabcdef'}).length,0);assert.ok(smiView(d,{...emptyFilters,standard:'C'}).every(g=>g.requirements.length>1));assert.ok(smiView(d,{...emptyFilters,chapter:'7',type:ready.type,team:'qsse'}).every(g=>g.chapter===7));
const q=d.standards.find(s=>s.badge==='Q');assert.ok(smiView(d,{...emptyFilters,standard:q.id}).every(g=>g.requirements.every(r=>r.standard_id===q.id)));assert.ok(exportMatrix(d,emptyFilters).length>72);
assert.equal((await ged.POST(request({action:'document-metadata',documentId:newDoc.id,revision:ready.revision,nextReview:'2020-01-01',catalogStatus:'Actif',note:'Révision dépassée'},'/api/ged'))).status,200);d=await data();assert.equal(d.documents.find(x=>x.id===newDoc.id).status,'En révision');
let current=d.documents.find(x=>x.id===newDoc.id);assert.equal((await ged.POST(request({action:'document-metadata',documentId:newDoc.id,revision:current.revision,nextReview:'2027-04-01',catalogStatus:'Obsolète',note:'Archivé'},'/api/ged'))).status,200);d=await data();assert.equal(d.documents.find(x=>x.id===newDoc.id).status,'Obsolète / Archivé');assert.equal(coverage(reqs[0],d.links,d.documents),25);
assert.equal((await post({operation:'standard',id:q.id,revision:q.revision,data:q})).status,403);
globalThis.smiUser={id:'admin',displayName:'Admin',role:'admin'};assert.equal((await post({operation:'standard',id:q.id,revision:q.revision,data:{...q,active:false}})).status,200);assert.equal((await post({operation:'standard',id:q.id,revision:q.revision,data:q})).status,409);d=await data();assert.ok(smiView(d,emptyFilters).every(g=>g.requirements.every(r=>r.standard_id!==q.id)));assert.equal(d.standards.find(s=>s.id===q.id).revision,2);
const ev={operation:'evidence',id:'',revision:0,requirementId:reqs[1],kind:'gap',targetId:'ticket-1',note:'Audit interne'};const er=await post(ev);assert.equal(er.status,200);assert.equal((await post(ev)).status,409);const links=await (await api.GET(request(null,'/api/smi?scope=audit'))).json();assert.equal(links.relations.length,1);
const exported=await xlsx.GET(request(null,'/api/smi/export?chapter=7'));assert.equal(exported.status,200);assert.match(exported.headers.get('Content-Type'),/spreadsheetml/);const file=path.join(dir,'matrix.xlsx');fs.writeFileSync(file,Buffer.from(await exported.arrayBuffer()));
execFileSync('python',['-c',`import openpyxl,sys\nw=openpyxl.load_workbook(sys.argv[1]);assert len(w.sheetnames)==2;assert w.worksheets[0]['A1'].value=='Chapitre';assert w.worksheets[0].max_row>1;assert not any(c.data_type=='f' for s in w for row in s for c in row);assert w.worksheets[0].freeze_panes=='A2'`,file]);
globalThis.smiUser=null;assert.equal((await api.GET(request())).status,401);assert.equal((await xlsx.GET(request())).status,401);
sql.exec(fs.readFileSync('scripts/rollback-smi.sql','utf8'));assert.equal(sql.prepare('SELECT count(*) n FROM ged_documents').get().n,2);assert.equal(sql.prepare("SELECT count(*) n FROM sqlite_master WHERE type='table' AND name LIKE 'smi_%'").get().n,0);
console.log('SMI : 72 exigences, droits réels par service, liens multiples sans duplication, conflits, retrait/rétablissement, GED synchronisée, statuts, filtres/recherche, couverture, audit, export Excel et retour arrière vérifiés.');
}finally{sql.close();fs.rmSync(dir,{recursive:true,force:true})}
