'use client';
import {useEffect,useMemo,useState} from 'react';
import {AccountGate,type Account} from '@/components/account-gate';
import {ListPagination,useListPage} from '@/components/list-pagination';
import {HubFrame,hubRequest} from '@/components/hub-layout';
import type {WorkItem} from '@/app/api/work/route';

export default function Page(){return <AccountGate>{account=><Work account={account}/>}</AccountGate>}
function Work({account}:{account:Account}){
  const [items,setItems]=useState<WorkItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState<'mine'|'all'>('mine'),[status,setStatus]=useState('open'),[query,setQuery]=useState('');
  async function load(){setLoading(true);try{const d=await hubRequest('/api/work');setItems(d.items);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const mine=(item:WorkItem)=>item.pilotId===account.id;
  const unresolved=items.filter(i=>!i.closed&&!!i.pilot&&!i.pilotId);const personal=items.filter(mine),unassigned=items.filter(i=>!i.pilot&&!i.pilotId&&!i.closed),late=personal.filter(i=>!i.closed&&i.due&&i.due<today);
  const visible=useMemo(()=>items.filter(i=>(view==='all'||mine(i))&&(status==='all'||status==='open'&&!i.closed||status==='late'&&!i.closed&&!!i.due&&i.due<today||status==='verify'&&i.status==='À vérifier'||status==='unassigned'&&!i.closed&&!i.pilot&&!i.pilotId||status==='unresolved'&&!i.closed&&!!i.pilot&&!i.pilotId)&&(i.title+' '+i.source+' '+i.category+' '+i.pilot).toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))).sort((a,b)=>Number(a.closed)-Number(b.closed)||(a.due||'9999').localeCompare(b.due||'9999')),[items,view,status,query,account.id,account.displayName,today]);
  const list=useListPage(visible,[view,status,query].join('|'));
  return <HubFrame active="Mon travail"><div className="hub-heading"><div><h1>Mes actions</h1><p>Les actions et audits à suivre, réunis depuis les tickets, le DUERP, les fiches QSE et le plan consolidé.</p></div><div className="board-tools"><a className="outline" href="/plan-actions">Plan d’actions consolidé</a><a className="primary" href="/tickets?new=1">Signaler / ouvrir un ticket</a><button className="outline" onClick={load}>Actualiser</button></div></div>
    {error&&<p role="alert" className="error">{error}</p>}{loading?<p role="status">Chargement des actions…</p>:<><div className="work-summary"><button onClick={()=>{setView('mine');setStatus('open')}}><strong>{personal.filter(i=>!i.closed).length}</strong><span>mes tâches ouvertes</span></button><button onClick={()=>{setView('mine');setStatus('late')}}><strong>{late.length}</strong><span>mes retards</span></button><button onClick={()=>{setView('all');setStatus('unassigned')}}><strong>{unassigned.length}</strong><span>sans pilote</span></button></div><div className="work-filters"><label>Vue<select value={view} onChange={e=>setView(e.target.value as 'mine'|'all')}><option value="mine">Mes actions</option><option value="all">Toutes les actions</option></select></label><label>État<select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Ouvertes</option><option value="late">En retard</option><option value="verify">À vérifier</option><option value="unassigned">Sans pilote</option><option value="unresolved">Affectation à confirmer</option><option value="all">Toutes</option></select></label><label>Rechercher<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Action, origine, pilote…"/></label></div><p className="work-hint">Une ligne par action ou audit prévu. Les dossiers restent dans leur module d’origine ; le lien ouvre la fiche à traiter. Les actions sont rattachées au compte de leur pilote. Les anciens noms ne sont rapprochés que lorsqu’ils correspondent à un seul compte ; les homonymes restent à confirmer depuis la fiche.</p><p className="work-hint">{unresolved.length>0&&<button className="outline" onClick={()=>{setView('all');setStatus('unresolved')}}>{unresolved.length} affectation(s) nominative(s) à confirmer</button>}</p><div className="work-list">{list.rows.map(i=><a href={i.href} key={i.id} className={'work-row'+(!i.closed&&i.due&&i.due<today?' work-late':'')}><div><span className="work-source">{i.source}{i.unitCode?' · '+i.unitCode:''}</span><strong>{i.title}</strong><small>{i.origin} · {i.category}</small></div><div><span>{i.status}</span><small>{i.pilot||'Pilote à désigner'}</small></div><time>{i.due?new Date(i.due+'T12:00:00').toLocaleDateString('fr-FR'):'Échéance à définir'}</time></a>)}{!visible.length&&<p className="hub-empty">Aucune action pour cette sélection. {view==='mine'?'Consultez « Toutes les actions » ou attribuez un pilote.':''}</p>}</div><ListPagination page={list.page} pages={list.pages} total={visible.length} onChange={list.setPage}/></>}
  </HubFrame>
}
