import {database} from '@/db/raw';
import {requireRole,checkOrigin} from '@/lib/access';
import {teamsAllowed} from '@/lib/team-access';
import {wasteSource} from '@/lib/waste-private-source';
import {blankWaste,wasteIssues,validateWaste,type WasteRecord} from '@/lib/waste';
async function allRecords(){const db=database(),records=new Map<string,WasteRecord>((wasteSource?.records||[]).map(r=>[r.id,{...r,issues:wasteIssues(r)}]));
const [legacy,overrides]=await Promise.all([db.prepare("SELECT * FROM records WHERE kind='Gestion des déchets'").all(),db.prepare('SELECT * FROM waste_records').all()]);
for(const x of legacy.results as any[]){const d=JSON.parse(x.details||'{}'),q=d.quantity===''||d.quantity===undefined?null:Number(d.quantity);const r:WasteRecord={...blankWaste(),id:'legacy-'+x.id,date:d.date||'',dateSource:d.date||'',type:x.title,family:'Autres',code:d.code||'',quantity:Number.isFinite(q)?q:null,unit:'kg',danger:['Oui','Non'].includes(d.dangerous)?d.dangerous:'À vérifier',status:x.status==='Prévu'?'Prévu':'Enlevé',collector:d.collector||'',destination:d.destination||'',treatment:d.treatment||'',bsd:d.bsd||'',notes:x.description||'',owner:x.owner||'',documentUrl:x.url||'',raw:{'Ancienne fiche':x.id,'Statut antérieur':x.status}};records.set(r.id,{...r,issues:wasteIssues(r)})}
for(const x of overrides.results as any[]){const stored=JSON.parse(x.data),original=records.get(x.id);const r={...stored,id:x.id,revision:x.revision,updatedAt:x.updated_at,updatedBy:x.updated_by,raw:original?.raw,sourceRow:original?.sourceRow||0,dateSource:original?.dateSource||''};records.set(x.id,{...r,issues:wasteIssues(r)})}return records}
const noStore={'Cache-Control':'private, no-store'};
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;if(!await teamsAllowed(gate.user!,['qsse']))return Response.json({error:'Accès QSSE nécessaire.'},{status:403});const p=new URL(req.url).searchParams,id=p.get('id');
if(p.get('reference'))return Response.json({reference:wasteSource?.adrReference||[]},{headers:noStore});
const records=await allRecords();if(id){const record=records.get(id);if(!record)return Response.json({error:'Enlèvement introuvable.'},{status:404});const history=(await database().prepare('SELECT snapshot,saved_at,saved_by FROM waste_history WHERE record_id=? ORDER BY saved_at DESC LIMIT 30').bind(id).all()).results;return Response.json({record,history,headers:wasteSource?.headers||[]},{headers:noStore})}
return Response.json({records:[...records.values()].map(({raw,...r})=>r),source:wasteSource?{name:wasteSource.source,count:wasteSource.records.length}:null},{headers:noStore})
}catch(e){console.error(e);return Response.json({error:'Le registre est indisponible. Réessayez.'},{status:503})}}
export async function POST(req:Request){try{if(!checkOrigin(req))return Response.json({error:'Requête non autorisée.'},{status:403});const gate=await requireRole(req,'editor');if(gate.error)return gate.error;if(!await teamsAllowed(gate.user!,['qsse'],true))return Response.json({error:'Droit de modification QSSE nécessaire.'},{status:403});const b=await req.json() as WasteRecord;if(!b||typeof b!=='object'||Array.isArray(b))return Response.json({error:'Fiche invalide.'},{status:400});
for(const k of ['id','date','type','family','code','status','unit','danger','collector','destination','treatment','bsd','owner','notes','documentUrl'] as const)if(typeof b[k]!=='string'||b[k].length>(k==='notes'?5000:500))return Response.json({error:'Champ invalide : '+k},{status:400});if(typeof b.excluded!=='boolean'||typeof b.client!=='boolean'||!Number.isInteger(b.revision)||b.revision<0)return Response.json({error:'Fiche invalide.'},{status:400});const errors=validateWaste(b);if(errors.length)return Response.json({error:errors.join('\n')},{status:400});
const records=await allRecords(),previous=b.id?records.get(b.id):null;if(b.id&&!previous)return Response.json({error:'Enlèvement introuvable.'},{status:404});if(previous&&previous.revision!==b.revision)return Response.json({error:'La fiche a changé. Copiez votre saisie puis rouvrez la dernière version.'},{status:409});
const id=previous?.id||crypto.randomUUID(),now=new Date().toISOString(),r:WasteRecord={...blankWaste(),...Object.fromEntries(['date','type','family','code','status','unit','danger','collector','destination','treatment','bsd','owner','notes','documentUrl','quantity','estimate','excluded','client'].map(k=>[k,(b as any)[k]])),id,revision:b.revision+1};r.type=r.type.trim();r.issues=wasteIssues(r);const db=database();let mutation;
if(previous&&previous.revision>0)mutation=db.prepare('UPDATE waste_records SET data=?,revision=revision+1,updated_at=?,updated_by=? WHERE id=? AND revision=?').bind(JSON.stringify(r),now,gate.user!.displayName,id,b.revision);
else mutation=db.prepare('INSERT OR IGNORE INTO waste_records (id,data,revision,updated_at,updated_by) VALUES (?,?,?,?,?)').bind(id,JSON.stringify(r),1,now,gate.user!.displayName);
const statements=[mutation];if(previous)statements.push(db.prepare('INSERT INTO waste_history (id,record_id,snapshot,saved_at,saved_by) SELECT ?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),id,JSON.stringify({...previous,raw:undefined}),now,gate.user!.displayName));const result=await db.batch(statements);if(!result[0].meta.changes)return Response.json({error:'Une autre personne a modifié cette fiche. Copiez votre saisie puis rechargez-la.'},{status:409});return Response.json({id});
}catch(e){console.error(e);return Response.json({error:'Enregistrement impossible. Votre saisie est conservée.'},{status:503})}}
