import {database} from '@/db/raw';
import {checkOrigin,requireRole} from '@/lib/access';
import {ticketError,routineError,communicationError,occurrenceDates,validDate,type Routine} from '@/lib/hub';
const fail=(error:string,status=400)=>Response.json({error},{status});
const ok=(v:unknown)=>Response.json(v,{headers:{'Cache-Control':'no-store'}});
const parse=(r:any)=>({...r,data:JSON.parse(r.data)});
const tables={ticket:'hub_tickets',routine:'hub_routines',communication:'hub_communications'} as const;
async function recipients(ids:unknown){if(!Array.isArray(ids)||ids.length>100||ids.some(id=>typeof id!=='string')||new Set(ids).size!==ids.length)return false;const users=(await database().prepare('SELECT id FROM users').all()).results;return ids.every(id=>users.some(u=>u.id===id))}
async function notify(ids:string[],title:string,href:string){if(!ids.length)return '';try{const db=database();await db.batch([...new Set(ids)].map(id=>db.prepare('INSERT INTO hub_notifications (id,user_id,title,href,seen,created_at) VALUES (?,?,?,?,0,?)').bind(crypto.randomUUID(),id,title,href,new Date().toISOString())));return ''}catch(e){console.error(e);return 'Enregistrement réussi, mais les notifications n’ont pas pu être créées. Utilisez « Notifier » pour réessayer.'}}
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;const db=database(),q=new URL(req.url).searchParams,scope=q.get('scope')||'meta';
if(scope==='meta'){const [teams,users]=await Promise.all([db.prepare('SELECT id,name,rank,parent_id FROM teams ORDER BY rank,name').all(),db.prepare('SELECT id,display_name FROM users ORDER BY display_name').all()]);return ok({teams:teams.results,users:users.results})}
if(scope==='notifications'){const [rows,count]=await Promise.all([db.prepare('SELECT * FROM hub_notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(gate.user!.id).all(),db.prepare('SELECT count(*) AS total FROM hub_notifications WHERE user_id=? AND seen=0').bind(gate.user!.id).first()]);return ok({notifications:rows.results,unread:count?.total||0})}
if(scope==='ticket'){const row=await db.prepare('SELECT * FROM hub_tickets WHERE id=?').bind(q.get('id')||'').first();if(!row)return fail('Ticket introuvable.',404);const [comments,files]=await Promise.all([db.prepare('SELECT * FROM hub_comments WHERE ticket_id=? ORDER BY created_at,id').bind(row.id).all(),db.prepare('SELECT * FROM hub_files WHERE ticket_id=? ORDER BY created_at,id').bind(row.id).all()]);return ok({ticket:parse(row),comments:comments.results,files:files.results})}
if(scope==='run'){const id=q.get('id')||'',date=q.get('date')||'';if(!validDate(date))return fail('Date invalide.');const routine=await db.prepare('SELECT * FROM hub_routines WHERE id=?').bind(id).first<any>();if(!routine)return fail('Routine introuvable.',404);const run=await db.prepare('SELECT * FROM hub_runs WHERE id=?').bind(id+':'+date).first();return ok({routine:parse(routine),run:run?parse(run):null})}
if(scope==='routines'){const from=q.get('from')||'',to=q.get('to')||'';if(!validDate(from)||!validDate(to)||to<from||Date.parse(to)-Date.parse(from)>93*86400000)return fail('Choisissez une période de 93 jours maximum.');const [rows,runs]=await Promise.all([db.prepare('SELECT * FROM hub_routines ORDER BY updated_at DESC').all(),db.prepare('SELECT * FROM hub_runs WHERE date>=? AND date<=?').bind(from,to).all()]);return ok({routines:rows.results.map(parse),runs:runs.results.map(parse)})}
if(scope==='tickets'||scope==='communications'){const table=scope==='tickets'?'hub_tickets':'hub_communications';const rows=await db.prepare(`SELECT * FROM ${table} ORDER BY updated_at DESC LIMIT 501`).all();return ok({rows:rows.results.slice(0,500).map(parse),truncated:rows.results.length>500})}return fail('Vue inconnue.');}catch(e){console.error(e);return fail('Données indisponibles. Réessayez.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Origine non autorisée.',403);const gate=await requireRole(req);if(gate.error)return gate.error;const b:any=await req.json();if(!b||typeof b!=='object')return fail('Saisie invalide.');const db=database(),now=new Date().toISOString(),author=gate.user!.displayName;
if(b.action==='read'){if(typeof b.id!=='string')return fail('Notification invalide.');await db.prepare('UPDATE hub_notifications SET seen=1 WHERE id=? AND user_id=?').bind(b.id,gate.user!.id).run();return ok({ok:true})}
if(gate.user!.role==='reader')return fail('Votre rôle permet uniquement la consultation.',403);
if(b.action==='comment'||b.action==='notify'){if(typeof b.ticketId!=='string'||!await recipients(b.recipients||[]))return fail('Destinataires invalides.');const ticket=await db.prepare('SELECT data FROM hub_tickets WHERE id=?').bind(b.ticketId).first<any>();if(!ticket)return fail('Ticket introuvable.',404);const data=JSON.parse(ticket.data);if(b.action==='comment'){if(typeof b.body!=='string'||!b.body.trim()||b.body.length>10000)return fail('Rédigez un commentaire (10 000 caractères maximum).');await db.prepare('INSERT INTO hub_comments (id,ticket_id,body,author_id,author,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),b.ticketId,b.body.trim(),gate.user!.id,author,now).run()}else if(!b.recipients?.length)return fail('Choisissez au moins un responsable.');const warning=await notify(b.recipients||[],(b.action==='comment'?'Commentaire de '+author+' · ':'Ticket à suivre · ')+data.title,'/tickets?id='+encodeURIComponent(b.ticketId));return ok({ok:true,warning})}
if(b.action==='run'){if(typeof b.routineId!=='string'||!validDate(b.date)||!Number.isInteger(b.revision)||b.revision<0)return fail('Occurrence invalide.');const row=await db.prepare('SELECT data FROM hub_routines WHERE id=?').bind(b.routineId).first<any>();if(!row)return fail('Routine introuvable.',404);const routine:Routine=JSON.parse(row.data);if(!occurrenceDates(routine,b.date,b.date).includes(b.date))return fail('Cette date ne correspond pas à une occurrence active.');const v=b.data;if(!v||!Array.isArray(v.answers)||v.answers.length!==routine.questions.length||typeof v.notes!=='string'||v.notes.length>10000||typeof v.completed!=='boolean'||new Set(v.answers.map((a:any)=>a.id)).size!==v.answers.length)return fail('Compte rendu invalide.');for(const a of v.answers){const q=routine.questions.find(q=>q.id===a.id);if(!q||!['À faire','Conforme','Non conforme','Non applicable'].includes(a.result)||typeof a.comment!=='string'||a.comment.length>3000)return fail('Point de contrôle invalide.');a.label=q.label}if(v.completed&&v.answers.some((a:any)=>a.result==='À faire'))return fail('Évaluez tous les points avant de terminer l’audit.');const id=b.routineId+':'+b.date;const result=b.revision===0?await db.prepare('INSERT OR IGNORE INTO hub_runs (id,routine_id,date,data,revision,author,updated_at) VALUES (?,?,?,?,1,?,?)').bind(id,b.routineId,b.date,JSON.stringify(v),author,now).run():await db.prepare('UPDATE hub_runs SET data=?,revision=revision+1,author=?,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(v),author,now,id,b.revision).run();if(!result.meta.changes)return fail('Compte rendu modifié. Rechargez avant de réessayer.',409);return ok({id,revision:b.revision+1})}
if(!Object.hasOwn(tables,b.action))return fail('Action inconnue.');const kind=b.action as keyof typeof tables,v=b.data;const error=kind==='ticket'?ticketError(v):kind==='routine'?routineError(v):communicationError(v);if(error)return fail(error);if(b.id&&(typeof b.id!=='string'||!Number.isInteger(b.revision)||b.revision<1))return fail('Révision invalide.');const teamIds=[...v.teams,...(kind==='communication'?[v.sourceTeam]:[])];const teams=(await db.prepare('SELECT id FROM teams').all()).results;if(teamIds.some(id=>!teams.some(t=>t.id===id)))return fail('Équipe inconnue.');const userIds=kind==='ticket'?[v.pilot,...v.responsibles,...v.actions.map((a:any)=>a.pilot)].filter(Boolean):kind==='routine'?[v.pilot].filter(Boolean):[];if(!await recipients([...new Set(userIds)]))return fail('Pilote ou responsable inconnu.');if(kind==='ticket'&&v.source){const source=await db.prepare('SELECT data FROM hub_routines WHERE id=?').bind(v.source.routineId).first<any>();if(!source||!occurrenceDates(JSON.parse(source.data),v.source.date,v.source.date).length)return fail('Routine d’origine introuvable.');}
const id=b.id||crypto.randomUUID(),table=tables[kind];if(b.id){if(kind==='routine'){const previous=await db.prepare('SELECT data FROM hub_routines WHERE id=?').bind(id).first<any>();if(previous&&await db.prepare('SELECT id FROM hub_runs WHERE routine_id=? LIMIT 1').bind(id).first()){const old=JSON.parse(previous.data);if(['start','time','repeat','interval','end','questions'].some(k=>JSON.stringify(old[k])!==JSON.stringify(v[k])))return fail('Cette routine possède des comptes rendus. Créez une nouvelle routine pour changer son calendrier ou sa grille ; vous pouvez suspendre celle-ci.')}}const result=await db.prepare(`UPDATE ${table} SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?`).bind(JSON.stringify(v),now,id,b.revision).run();if(!result.meta.changes)return fail('Cette fiche a changé. Fermez puis rechargez-la ; votre saisie est conservée.',409)}else if(kind==='routine')await db.prepare('INSERT INTO hub_routines (id,data,revision,updated_at) VALUES (?,?,1,?)').bind(id,JSON.stringify(v),now).run();else await db.prepare(`INSERT INTO ${table} (id,data,revision,created_at,updated_at,author) VALUES (?,?,1,?,?,?)`).bind(id,JSON.stringify(v),now,now,author).run();const warning=kind==='ticket'?await notify([...new Set([v.pilot,...v.responsibles,...v.actions.map((a:any)=>a.pilot)].filter(Boolean))] as string[],(b.id?'Ticket mis à jour · ':'Nouveau ticket · ')+v.title,'/tickets?id='+encodeURIComponent(id)):'';return ok({id,revision:(b.revision||0)+1,warning});}catch(e){console.error(e);return fail('Enregistrement impossible. Votre saisie est conservée.',503)}}
