import {gmaoTicketContributor,gmaoTicketReader} from '@/lib/gmao-server';
import {database} from '@/db/raw';
import {checkOrigin,requireRole} from '@/lib/access';
import {ticketError,routineError,communicationError,occurrenceDates,validDate,type Routine} from '@/lib/hub';
import {teamContentVisible,accessibleTeams,someTeamAllowed,teamsAllowed} from '@/lib/team-access';
const fail=(error:string,status=400)=>Response.json({error},{status});
const ok=(v:unknown)=>Response.json(v,{headers:{'Cache-Control':'no-store'}});
const parse=(r:any)=>({...r,data:JSON.parse(r.data)});
const tables={ticket:'hub_tickets',routine:'hub_routines',communication:'hub_communications'} as const;
async function recipients(ids:unknown){if(!Array.isArray(ids)||ids.length>100||ids.some(id=>typeof id!=='string')||new Set(ids).size!==ids.length)return false;const users=(await database().prepare('SELECT id FROM users').all()).results;return ids.every(id=>users.some(u=>u.id===id))}
async function notify(ids:string[],title:string,href:string){if(!ids.length)return '';try{const db=database();await db.batch([...new Set(ids)].map(id=>db.prepare('INSERT INTO hub_notifications (id,user_id,title,href,seen,created_at) VALUES (?,?,?,?,0,?)').bind(crypto.randomUUID(),id,title,href,new Date().toISOString())));return ''}catch(e){console.error(e);return 'Enregistrement réussi, mais les notifications n’ont pas pu être créées. Utilisez « Notifier » pour réessayer.'}}
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;const db=database(),q=new URL(req.url).searchParams,scope=q.get('scope')||'meta',contextTeam=q.get('team')||'';if(contextTeam&&['tickets','ticket','communications','routines','run','overview-stats'].includes(scope)&&!(await accessibleTeams(gate.user!)).has(contextTeam))return fail('Accès à cette équipe non autorisé.',403);
if(scope==='meta'){const [teams,users]=await Promise.all([db.prepare('SELECT id,name,rank,parent_id FROM teams ORDER BY rank,name').all(),db.prepare('SELECT id,display_name FROM users ORDER BY display_name').all()]);const allowed=await accessibleTeams(gate.user!),editable=await accessibleTeams(gate.user!,true);return ok({teams:teams.results.filter((t:any)=>allowed.has(t.id)),editableTeams:[...editable],contributingTeams:[...await accessibleTeams(gate.user!,true,'contribute')],managedTeams:[...await accessibleTeams(gate.user!,true,'manage')],users:users.results})}
if(scope==='notifications'){const [rows,count]=await Promise.all([db.prepare('SELECT * FROM hub_notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(gate.user!.id).all(),db.prepare('SELECT count(*) AS total FROM hub_notifications WHERE user_id=? AND seen=0').bind(gate.user!.id).first()]);const allowed=await accessibleTeams(gate.user!);const ticketRows=await db.prepare('SELECT id,data FROM hub_tickets').all();const ticketTeams=new Map((ticketRows.results as any[]).map(r=>[r.id,JSON.parse(r.data).teams||[]]));const visible:any[]=[];for(const n of rows.results as any[]){const url=new URL(n.href,'https://local.invalid');let canRead=false;if(url.pathname==='/tickets'){const ids=ticketTeams.get(url.searchParams.get('id')||'') as string[]|undefined;canRead=!!ids&&teamContentVisible(allowed,ids,gate.user!.role==='admin')}else if(url.pathname==='/ged'){const id=url.searchParams.get('document');if(id){const {GET}=await import('@/app/api/ged/route');canRead=(await GET(new Request(new URL('/api/ged?id='+encodeURIComponent(id),req.url),{headers:req.headers}))).ok}}else if(url.pathname==='/maintenance'){const id=url.searchParams.get('order');if(id){const {GET}=await import('@/app/api/gmao/route');canRead=(await GET(new Request(new URL('/api/gmao?kind=order&id='+encodeURIComponent(id),req.url),{headers:req.headers}))).ok}}if(canRead)visible.push(n)};return ok({notifications:visible,unread:visible.filter((n:any)=>!n.seen).length})}
if(scope==='overview-stats'){const team=q.get('team')||'';if(!team||!await db.prepare('SELECT id FROM teams WHERE id=?').bind(team).first())return fail('Équipe inconnue.');const allowed=await accessibleTeams(gate.user!);if(!allowed.has(team))return fail('Accès à cette équipe non autorisé.',403);const scopeIds=[team];const rows=await db.prepare('SELECT id,data,created_at,updated_at FROM hub_tickets ORDER BY updated_at DESC').all();const counts:Record<string,{open:number;closed:number;total:number}>=Object.create(null),recent:any[]=[];for(const r of rows.results as any[]){const item=JSON.parse(r.data);if(!Array.isArray(item.teams)||!teamContentVisible(allowed,item.teams,gate.user!.role==='admin')||!item.teams.some((id:string)=>scopeIds.includes(id)))continue;const category=String(item.category||'Autre');const entry=counts[category]||{open:0,closed:0,total:0};entry.total++;entry[item.status==='Clôturé'?'closed':'open']++;counts[category]=entry;if(recent.length<150)recent.push({id:r.id,title:item.title,category,status:item.status,due:item.due,updated_at:r.updated_at})}return ok({counts,recent,shown:recent.length,updatedAt:new Date().toISOString()})}
if(scope==='ticket'){const row=await db.prepare('SELECT * FROM hub_tickets WHERE id=?').bind(q.get('id')||'').first();if(!row)return fail('Ticket introuvable.',404);if(contextTeam&&!JSON.parse((row as any).data).teams?.includes(contextTeam))return fail('Ce ticket ne concerne pas cette équipe.',404);if(!await someTeamAllowed(gate.user!,JSON.parse((row as any).data).teams||[])&&!await gmaoTicketReader(gate.user!,String(row.id)))return fail('Accès au ticket non autorisé.',403);const [comments,files]=await Promise.all([db.prepare('SELECT * FROM hub_comments WHERE ticket_id=? ORDER BY created_at,id').bind(row.id).all(),db.prepare('SELECT * FROM hub_files WHERE ticket_id=? ORDER BY created_at,id').bind(row.id).all()]);return ok({ticket:parse(row),comments:comments.results,files:files.results,gmaoContributor:await gmaoTicketContributor(gate.user!,String(row.id)),gmaoDataContributor:await gmaoTicketContributor(gate.user!,String(row.id),'contribute')})}
if(scope==='run'){const id=q.get('id')||'',date=q.get('date')||'';if(!validDate(date))return fail('Date invalide.');const routine=await db.prepare('SELECT * FROM hub_routines WHERE id=?').bind(id).first<any>();if(!routine)return fail('Routine introuvable.',404);if(contextTeam&&!JSON.parse(routine.data).teams?.includes(contextTeam))return fail('Cette routine ne concerne pas cette équipe.',404);if(!await someTeamAllowed(gate.user!,JSON.parse(routine.data).teams||[]))return fail('Accès à la routine non autorisé.',403);const run=await db.prepare('SELECT * FROM hub_runs WHERE id=?').bind(id+':'+date).first();return ok({routine:parse(routine),run:run?parse(run):null})}
if(scope==='routines'){const from=q.get('from')||'',to=q.get('to')||'';if(!validDate(from)||!validDate(to)||to<from||Date.parse(to)-Date.parse(from)>93*86400000)return fail('Choisissez une période de 93 jours maximum.');const [rows,runs]=await Promise.all([db.prepare('SELECT * FROM hub_routines ORDER BY updated_at DESC').all(),db.prepare('SELECT * FROM hub_runs WHERE date>=? AND date<=?').bind(from,to).all()]);const allowed=await accessibleTeams(gate.user!);const visible=rows.results.map(parse).filter((r:any)=>(!contextTeam||r.data.teams?.includes(contextTeam))&&teamContentVisible(allowed,r.data.teams||[],gate.user!.role==='admin'));const ids=new Set(visible.map((r:any)=>r.id));return ok({routines:visible,runs:runs.results.map(parse).filter((r:any)=>ids.has(r.routine_id))})}
if(scope==='tickets'||scope==='communications'){
 const table=scope==='tickets'?'hub_tickets':'hub_communications',archive=q.get('archive')==='1';
 const clauses:string[]=[],params:(string|number)[]=[],allowed=await accessibleTeams(gate.user!);
 if(gate.user!.role!=='admin'){
  const ids=[...allowed];if(!ids.length)return ok({rows:[],total:0,page:0,pages:1,truncated:false});
  clauses.push(`EXISTS (SELECT 1 FROM json_each(data,'$.teams') WHERE value IN (${ids.map(()=>'?').join(',')}))`);params.push(...ids);
  if(!allowed.has('rh'))clauses.push("NOT EXISTS (SELECT 1 FROM json_each(data,'$.teams') WHERE value='rh')");
 }
 if(scope==='tickets'){clauses.push("(COALESCE(json_extract(data,'$.archivedAt'),'')!='')=?");params.push(archive?1:0)}
 if(contextTeam){clauses.push("EXISTS (SELECT 1 FROM json_each(data,'$.teams') WHERE value=?)");params.push(contextTeam)}
 const normalize=(v:string)=>v.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase('fr');
 const term=normalize(q.get('search')||''),category=q.get('category'),status=q.get('status'),pilot=q.get('pilot'),source=q.get('source'),focus=q.get('focus'),mine=q.get('mine')==='1';
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const stats={open:0,late:0,verify:0,mine:0};let total=0,offset=0;const requested=Math.max(0,Math.floor(Number(q.get('page'))||0)),size=q.has('page')?15:500;const visible:any[]=[];
 const sort=q.get('sort'),order=sort==='title'?"json_extract(data,'$.title') COLLATE NOCASE ASC,id ASC":sort==='due'?(archive?"json_extract(data,'$.archivedAt') DESC,id ASC":"COALESCE(NULLIF(json_extract(data,'$.due'),''),'9999') ASC,id ASC"):"updated_at DESC,id ASC";
 // Bounded batches: authorization is applied before scanning, filtering and pagination.
 while(true){const batch=await db.prepare(`SELECT * FROM ${table} ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY ${order} LIMIT 500 OFFSET ?`).bind(...params,offset).all();
 for(const raw of batch.results){const r=parse(raw),v=r.data;if(!teamContentVisible(allowed,v.teams||[],gate.user!.role==='admin'))continue;
 const isMine=v.pilot===gate.user!.id||v.responsibles?.includes(gate.user!.id)||v.actions?.some((a:any)=>a.pilot===gate.user!.id),late=!!v.due&&v.due<today&&v.status!=='Clôturé';
 if(mine&&!isMine)continue;
 if(scope==='tickets'){if(v.status!=='Clôturé')stats.open++;if(late)stats.late++;if(v.status==='À vérifier')stats.verify++;if(isMine)stats.mine++}
 if(category&&v.category!==category||status&&v.status!==status||source&&v.sourceTeam!==source||pilot&&v.pilot!==pilot&&!v.actions?.some((a:any)=>a.pilot===pilot))continue;
 if(!archive&&(focus==='open'&&v.status==='Clôturé'||focus==='late'&&!late||focus==='verify'&&v.status!=='À vérifier'||focus==='mine'&&!isMine))continue;
 if(term&&!normalize(v.title+' '+(v.description||v.body||'')).includes(term))continue;
 if(total>=requested*size&&visible.length<size)visible.push(r);total++;
 }if(batch.results.length<500)break;offset+=500;
 }
 return ok({rows:visible,total,page:requested,pages:Math.max(1,Math.ceil(total/size)),stats,truncated:!q.has('page')&&total>size});
 }return fail('Vue inconnue.');}catch(e){console.error(e);return fail('Données indisponibles. Réessayez.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Origine non autorisée.',403);const gate=await requireRole(req);if(gate.error)return gate.error;const b:any=await req.json();if(!b||typeof b!=='object')return fail('Saisie invalide.');const db=database(),now=new Date().toISOString(),author=gate.user!.displayName;
if(b.action==='read'){if(typeof b.id!=='string')return fail('Notification invalide.');await db.prepare('UPDATE hub_notifications SET seen=1 WHERE id=? AND user_id=?').bind(b.id,gate.user!.id).run();return ok({ok:true})}
if(gate.user!.role==='reader')return fail('Votre rôle permet uniquement la consultation.',403);
if(b.action==='archive-ticket'){if(typeof b.id!=='string'||typeof b.archive!=='boolean'||!Number.isInteger(b.revision))return fail('Archivage invalide.');const row=await db.prepare('SELECT data,revision FROM hub_tickets WHERE id=?').bind(b.id).first<any>();if(!row)return fail('Ticket introuvable.',404);const ticket=JSON.parse(row.data);if(!await teamsAllowed(gate.user!,ticket.teams||[],true))return fail('Archivage non autorisé pour ces équipes.',403);if(row.revision!==b.revision)return fail('Ce ticket a changé. Rechargez avant de l’archiver.',409);if(b.archive&&ticket.status!=='Clôturé')return fail('Clôturez le ticket avant de l’archiver.');if(!!ticket.archivedAt===b.archive)return ok({id:b.id,revision:row.revision});ticket.archivedAt=b.archive?now:'';ticket.archivedBy=b.archive?author:'';const result=await db.batch([db.prepare('UPDATE hub_tickets SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(ticket),now,b.id,b.revision),db.prepare('INSERT INTO hub_comments (id,ticket_id,body,author_id,author,created_at) SELECT ?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),b.id,b.archive?'Ticket archivé.':'Ticket restauré depuis les archives.',gate.user!.id,author,now)]);if(!result[0].meta.changes)return fail('Modification simultanée. Rechargez le ticket.',409);return ok({id:b.id,revision:row.revision+1})}

if(b.action==='comment'||b.action==='notify'){if(typeof b.ticketId!=='string'||!await recipients(b.recipients||[]))return fail('Destinataires invalides.');const ticket=await db.prepare('SELECT data FROM hub_tickets WHERE id=?').bind(b.ticketId).first<any>();if(!ticket)return fail('Ticket introuvable.',404);const data=JSON.parse(ticket.data);if(data.archivedAt)return fail('Restaurez le ticket avant de le modifier.',403);if(!await teamsAllowed(gate.user!,data.teams||[],true,'contribute')&&!await gmaoTicketContributor(gate.user!,b.ticketId,'contribute'))return fail('Modification de ce ticket non autorisée.',403);if(b.action==='comment'){if(typeof b.body!=='string'||!b.body.trim()||b.body.length>10000)return fail('Rédigez un commentaire (10 000 caractères maximum).');const added=await db.prepare(`INSERT INTO hub_comments (id,ticket_id,body,author_id,author,created_at) SELECT ?,?,?,?,?,? WHERE COALESCE((SELECT json_extract(data,'$.archivedAt') FROM hub_tickets WHERE id=?),'')=''`).bind(crypto.randomUUID(),b.ticketId,b.body.trim(),gate.user!.id,author,now,b.ticketId).run();if(!added.meta.changes)return fail('Le ticket a été archivé. Restaurez-le avant de commenter.',409)}else if(!b.recipients?.length)return fail('Choisissez au moins un responsable.');const warning=await notify(b.recipients||[],(b.action==='comment'?'Commentaire de '+author+' · ':'Ticket à suivre · ')+data.title,'/tickets?id='+encodeURIComponent(b.ticketId));return ok({ok:true,warning})}
if(b.action==='run'){if(typeof b.routineId!=='string'||!validDate(b.date)||!Number.isInteger(b.revision)||b.revision<0)return fail('Occurrence invalide.');const row=await db.prepare('SELECT data FROM hub_routines WHERE id=?').bind(b.routineId).first<any>();if(!row)return fail('Routine introuvable.',404);const routine:Routine=JSON.parse(row.data);if(!await teamsAllowed(gate.user!,routine.teams,true,'contribute'))return fail('Modification de cette routine non autorisée.',403);if(!occurrenceDates(routine,b.date,b.date).includes(b.date))return fail('Cette date ne correspond pas à une occurrence active.');const v=b.data;if(!v||!Array.isArray(v.answers)||v.answers.length!==routine.questions.length||typeof v.notes!=='string'||v.notes.length>10000||typeof v.completed!=='boolean'||new Set(v.answers.map((a:any)=>a.id)).size!==v.answers.length)return fail('Compte rendu invalide.');for(const a of v.answers){const q=routine.questions.find(q=>q.id===a.id);if(!q||!['À faire','Conforme','Non conforme','Non applicable'].includes(a.result)||typeof a.comment!=='string'||a.comment.length>3000)return fail('Point de contrôle invalide.');a.label=q.label}if(v.completed&&v.answers.some((a:any)=>a.result==='À faire'))return fail('Évaluez tous les points avant de terminer l’audit.');const id=b.routineId+':'+b.date;const result=b.revision===0?await db.prepare('INSERT OR IGNORE INTO hub_runs (id,routine_id,date,data,revision,author,updated_at) VALUES (?,?,?,?,1,?,?)').bind(id,b.routineId,b.date,JSON.stringify(v),author,now).run():await db.prepare('UPDATE hub_runs SET data=?,revision=revision+1,author=?,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(v),author,now,id,b.revision).run();if(!result.meta.changes)return fail('Compte rendu modifié. Rechargez avant de réessayer.',409);return ok({id,revision:b.revision+1})}
if(!Object.hasOwn(tables,b.action))return fail('Action inconnue.');const kind=b.action as keyof typeof tables,v=b.data;const error=kind==='ticket'?ticketError(v):kind==='routine'?routineError(v):communicationError(v);if(error)return fail(error);if(b.id&&(typeof b.id!=='string'||!Number.isInteger(b.revision)||b.revision<1))return fail('Révision invalide.');let linked:any=null;if(kind==='ticket'&&b.id){const r=await db.prepare('SELECT data FROM hub_tickets WHERE id=?').bind(b.id).first<any>();if(r){const t=JSON.parse(r.data);if(t.gmaoOrderId){linked=t;if(t.status==='Clôturé'&&JSON.stringify(t.actions)!==JSON.stringify(v.actions))return fail('Rouvrez l’intervention dans la GMAO avant de modifier ses sous-actions.',409);if(['title','category','description','teams','pilot','due','status'].some(k=>JSON.stringify(t[k])!==JSON.stringify(v[k])))return fail('Modifiez la demande, l’attribution et l’état depuis la GMAO.',409);}}}let dataEntry=false;if(kind==='ticket'&&b.id&&!await teamsAllowed(gate.user!,v.teams,true)&&(await teamsAllowed(gate.user!,v.teams,true,'contribute')||!!linked&&await gmaoTicketContributor(gate.user!,b.id,'contribute'))){const original=await db.prepare('SELECT data FROM hub_tickets WHERE id=?').bind(b.id).first<any>();if(original){const old=JSON.parse(original.data);const expected={...old,actions:old.actions.map((a:any)=>({...a,done:v.actions.find((x:any)=>x.id===a.id)?.done??a.done}))};if(JSON.stringify(expected)!==JSON.stringify(v))return fail('Un utilisateur peut renseigner la réalisation des actions, sans modifier le ticket ni ses affectations.',403);dataEntry=true}}const delegated=dataEntry||!!linked&&await gmaoTicketContributor(gate.user!,b.id);const teamIds=[...v.teams,...(kind==='communication'?[v.sourceTeam]:[])];const teams=(await db.prepare('SELECT id FROM teams').all()).results;if(teamIds.some(id=>!teams.some(t=>t.id===id)))return fail('Équipe inconnue.');if(!await teamsAllowed(gate.user!,teamIds,true)&&!delegated)return fail('Modification de ces équipes non autorisée.',403);const userIds=kind==='ticket'?[v.pilot,...v.responsibles,...v.actions.map((a:any)=>a.pilot)].filter(Boolean):kind==='routine'?[v.pilot].filter(Boolean):[];if(!await recipients([...new Set(userIds)]))return fail('Pilote ou responsable inconnu.');if(kind==='ticket'&&v.source){const source=await db.prepare('SELECT data FROM hub_routines WHERE id=?').bind(v.source.routineId).first<any>();if(!source||!occurrenceDates(JSON.parse(source.data),v.source.date,v.source.date).length)return fail('Routine d’origine introuvable.');}
if(kind==='ticket'&&!b.id){delete v.archivedAt;delete v.archivedBy;delete v.qualityActionId;delete v.gmaoOrderId}const id=b.id||crypto.randomUUID(),table=tables[kind];if(b.id){const previousAccess=await db.prepare(`SELECT data FROM ${table} WHERE id=?`).bind(id).first<any>();if(previousAccess&&kind==='ticket'){const stored=JSON.parse(previousAccess.data);if(stored.archivedAt)return fail('Restaurez le ticket avant de le modifier.',403);v.archivedAt=stored.archivedAt||'';v.archivedBy=stored.archivedBy||'';v.qualityActionId=stored.qualityActionId||'';v.gmaoOrderId=stored.gmaoOrderId||''}if(!previousAccess||!await teamsAllowed(gate.user!,JSON.parse(previousAccess.data).teams||[],true)&&!delegated)return fail('Modification de cette fiche non autorisée.',403);if(kind==='routine'){const previous=await db.prepare('SELECT data FROM hub_routines WHERE id=?').bind(id).first<any>();if(previous&&await db.prepare('SELECT id FROM hub_runs WHERE routine_id=? LIMIT 1').bind(id).first()){const old=JSON.parse(previous.data);if(['start','time','repeat','interval','end','questions'].some(k=>JSON.stringify(old[k])!==JSON.stringify(v[k])))return fail('Cette routine possède des comptes rendus. Créez une nouvelle routine pour changer son calendrier ou sa grille ; vous pouvez suspendre celle-ci.')}}const result=await db.prepare(`UPDATE ${table} SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?`).bind(JSON.stringify(v),now,id,b.revision).run();if(!result.meta.changes)return fail('Cette fiche a changé. Fermez puis rechargez-la ; votre saisie est conservée.',409)}else if(kind==='routine')await db.prepare('INSERT INTO hub_routines (id,data,revision,updated_at) VALUES (?,?,1,?)').bind(id,JSON.stringify(v),now).run();else await db.prepare(`INSERT INTO ${table} (id,data,revision,created_at,updated_at,author) VALUES (?,?,1,?,?,?)`).bind(id,JSON.stringify(v),now,now,author).run();const warning=kind==='ticket'?await notify([...new Set([v.pilot,...v.responsibles,...v.actions.map((a:any)=>a.pilot)].filter(Boolean))] as string[],(b.id?'Ticket mis à jour · ':'Nouveau ticket · ')+v.title,'/tickets?id='+encodeURIComponent(id)):'';return ok({id,revision:(b.revision||0)+1,warning});}catch(e){console.error(e);return fail('Enregistrement impossible. Votre saisie est conservée.',503)}}
