import {database} from '@/db/raw';
import {account,bootstrap,checkOrigin,checkPassword,clearCookie,currentUser,endSession,hashPassword,issueSession,userByName} from '@/lib/access';

const fail=(error:string,status=400)=>Response.json({error},{status});
export async function GET(req:Request){try{await bootstrap();return Response.json({account:await currentUser(req)})}catch(e){console.error(e);return fail('Service de connexion indisponible.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Requête non autorisée.',403);const body=await req.json() as Record<string,unknown>;const action=body.action;
if(action==='login'){const username=String(body.username||'').trim().toLowerCase(),password=String(body.password||'');if(!/^[a-z0-9._-]{3,40}$/.test(username)||password.length>256)return fail('Identifiant ou mot de passe incorrect.',401);await bootstrap();const db=database(),attempt=await db.prepare('SELECT failures,blocked_until FROM login_attempts WHERE username=?').bind(username).first<{failures:number;blocked_until:number}>();if(attempt&&attempt.blocked_until>Date.now())return fail('Trop de tentatives. Réessayez dans 15 minutes.',429);const user=await userByName(username);if(!user||!await checkPassword(password,user.password_hash)){const failures=(attempt?.failures||0)+1;await db.prepare('INSERT INTO login_attempts (username,failures,blocked_until) VALUES (?,?,?) ON CONFLICT(username) DO UPDATE SET failures=excluded.failures,blocked_until=excluded.blocked_until').bind(username,failures,failures>=5?Date.now()+15*60*1000:0).run();return fail('Identifiant ou mot de passe incorrect.',401)}await db.prepare('DELETE FROM login_attempts WHERE username=?').bind(username).run();const response=Response.json({account:account(user)});response.headers.set('Set-Cookie',await issueSession(user.id));return response}
if(action==='logout'){await endSession(req);const response=Response.json({ok:true});response.headers.set('Set-Cookie',clearCookie);return response}
if(action==='password'){const user=await currentUser(req);if(!user)return fail('Connexion nécessaire.',401);const oldPassword=String(body.oldPassword||''),newPassword=String(body.newPassword||'');if(newPassword.length<12||newPassword.length>256||newPassword.toLowerCase()===user.username)return fail('Choisissez un mot de passe de 12 caractères minimum, différent de votre identifiant.');const row=await userByName(user.username);if(!row||!await checkPassword(oldPassword,row.password_hash))return fail('Mot de passe actuel incorrect.',401);await database().batch([database().prepare('UPDATE users SET password_hash=?,must_change_password=0 WHERE id=?').bind(await hashPassword(newPassword),user.id),database().prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id)]);const response=Response.json({account:{...user,mustChangePassword:false}});response.headers.set('Set-Cookie',await issueSession(user.id));return response}
return fail('Action inconnue.');}catch(e){console.error(e);return fail('Opération impossible. Réessayez.',503)}}
