import {database} from '@/db/raw';
import {account,needsRehash,linkSiteIdentity,throttle,clearThrottle,securityEvent,checkOrigin,checkPassword,clearCookie,currentUser,endSession,hashPassword,issueSession,userByName} from '@/lib/access';

const fail=(error:string,status=400)=>Response.json({error},{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(req:Request){try{return Response.json({account:await currentUser(req)},{headers:{'Cache-Control':'private, no-store'}})}catch(e){console.error(e);return fail('Service de connexion indisponible.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Requête non autorisée.',403);const body=await req.json() as Record<string,unknown>;if(!body||typeof body!=='object')return fail('Demande invalide.');const action=body.action;
if(action==='login'){const username=String(body.username||'').trim().toLowerCase(),password=String(body.password||'');if(!/^[a-z0-9._-]{3,40}$/.test(username)||password.length>256)return fail('Identifiant ou mot de passe incorrect.',401);const db=database();if(await throttle('login:'+username))return fail('Trop de tentatives. Réessayez dans 15 minutes.',429);const user=await userByName(username);if(!user||!await checkPassword(password,user.password_hash)){await securityEvent('login_failed','',username);return fail('Identifiant ou mot de passe incorrect.',401)}await clearThrottle('login:'+username);if(needsRehash(user.password_hash))await db.prepare('UPDATE users SET password_hash=? WHERE id=? AND password_hash=?').bind(await hashPassword(password),user.id,user.password_hash).run();await linkSiteIdentity(req,user.id);await securityEvent('login',user.id);const response=Response.json({account:account(user)});response.headers.set('Cache-Control','private, no-store');response.headers.set('Set-Cookie',await issueSession(user.id));return response}
if(action==='logout'){await endSession(req);const response=Response.json({ok:true});response.headers.set('Cache-Control','private, no-store');response.headers.set('Set-Cookie',clearCookie);return response}
if(action==='password'){const user=await currentUser(req);if(!user)return fail('Connexion nécessaire.',401);const oldPassword=String(body.oldPassword||''),newPassword=String(body.newPassword||'');if(newPassword.length<12||newPassword.length>256||newPassword.toLowerCase()===user.username)return fail('Choisissez un mot de passe de 12 caractères minimum, différent de votre identifiant.');const row=await userByName(user.username);if(await throttle('password:'+user.id))return fail('Trop de tentatives. Réessayez dans 15 minutes.',429);if(!row||!await checkPassword(oldPassword,row.password_hash))return fail('Mot de passe actuel incorrect.',401);await database().batch([database().prepare('UPDATE users SET password_hash=?,must_change_password=0 WHERE id=?').bind(await hashPassword(newPassword),user.id),database().prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id),database().prepare('DELETE FROM site_identities WHERE user_id=?').bind(user.id)]);await clearThrottle('password:'+user.id);await linkSiteIdentity(req,user.id);await securityEvent('password_changed',user.id);const response=Response.json({account:{...user,mustChangePassword:false}});response.headers.set('Cache-Control','private, no-store');response.headers.set('Set-Cookie',await issueSession(user.id));return response}
return fail('Action inconnue.');}catch(e){console.error(e);return fail('Opération impossible. Réessayez.',503)}}
