import {database} from '@/db/raw';
import {checkOrigin,requireRole} from '@/lib/access';
import {boardError} from '@/lib/unit-dashboard';
import {accessibleTeams,teamsAllowed} from '@/lib/team-access';
const fail=(error:string,status=400)=>Response.json({error},{status});
const response=(data:unknown)=>Response.json(data,{headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;const db=database(),q=new URL(req.url).searchParams,id=q.get('id')||(q.get('unit')?'legacy-'+q.get('unit'):'');if(!id){const [teams,boards]=await Promise.all([db.prepare('SELECT * FROM teams ORDER BY rank,name').all(),db.prepare("SELECT id,team_id,unit_code,json_extract(data,'$.title') AS title FROM team_dashboards WHERE id NOT LIKE 'legacy-%' ORDER BY title,id").all()]);const allowed=await accessibleTeams(gate.user!);const canWrite=await accessibleTeams(gate.user!,true);return response({teams:teams.results.filter(t=>allowed.has(String(t.id))),boards:boards.results.filter((b:any)=>allowed.has(b.team_id)),editableTeams:[...canWrite]})}const row=await db.prepare('SELECT * FROM team_dashboards WHERE id=?').bind(id).first<any>();if(!row)return fail('Tableau introuvable.',404);if(!await teamsAllowed(gate.user!,[row.team_id]))return fail('Accès à cette équipe non autorisé.',403);const team=await db.prepare('SELECT * FROM teams WHERE id=?').bind(row.team_id).first();const board=JSON.parse(row.data);if(row.id.startsWith('board-')&&row.revision===1&&!row.updated_at&&board.widgets?.length===2&&board.widgets.every((w:any)=>['note','indicator'].includes(w.id)&&!w.text&&!w.value&&!w.target))board.widgets=[];const code=await teamsAllowed(gate.user!,['qsse'])?row.unit_code:'';const units=code==='*'?(await db.prepare('SELECT * FROM evrp_units ORDER BY code').all()).results:code?[await db.prepare('SELECT * FROM evrp_units WHERE code=?').bind(code).first()].filter(Boolean):[];const query=(table:string,fields:string)=>!code?Promise.resolve({results:[]}):code==='*'?db.prepare(`SELECT ${fields} FROM ${table}`).all():db.prepare(`SELECT ${fields} FROM ${table} WHERE unit_code=?`).bind(code).all();const [risks,actions]=await Promise.all([query('evrp_risks','id,data,status'),query('evrp_actions','id,data')]);return response({id:row.id,canContribute:await teamsAllowed(gate.user!,[row.team_id],true,'contribute'),team,scope:code,unit:{code:code==='*'?'Toutes les unités':code,name:code==='*'?'Site Polytechs':(units[0] as any)?.name||'Aucun périmètre DUERP associé',roles:units.flatMap((u:any)=>JSON.parse(u.roles).map((r:any)=>({...r,job:(code==='*'?u.code+' · ':'')+r.job})))},board,revision:row.revision,updatedAt:row.updated_at,updatedBy:row.updated_by,risks:risks.results.map((r:any)=>({...r,data:JSON.parse(r.data)})),actions:actions.results.map((a:any)=>({...JSON.parse(a.data),id:a.id}))})}catch(e){console.error(e);return fail('Tableau de bord indisponible.',503)}}
export async function POST(req:Request){try{if(!checkOrigin(req))return fail('Origine non autorisée.',403);const gate=await requireRole(req,'editor');if(gate.error)return gate.error;const b:any=await req.json();if(!b||typeof b!=='object')return fail('Saisie invalide.');const db=database();
if(b.action==='indicator-values'){
 if(typeof b.id!=='string'||!Number.isInteger(b.revision)||!Array.isArray(b.values)||b.values.length>60)return fail('Saisie invalide.');
 const row=await db.prepare('SELECT * FROM team_dashboards WHERE id=?').bind(b.id).first<any>();if(!row)return fail('Tableau introuvable.',404);
 if(!await teamsAllowed(gate.user!,[row.team_id],true,'contribute'))return fail('Saisie non autorisée.',403);
 const board=JSON.parse(row.data);const seen=new Set();for(const entry of b.values){if(!entry||typeof entry.id!=='string'||seen.has(entry.id))return fail('Indicateur invalide.');seen.add(entry.id);const w=board.widgets.find((w:any)=>w.id===entry.id&&w.type==='indicator');if(!w)return fail('Indicateur introuvable.');if(typeof entry.value!=='string'||typeof entry.date!=='string'||typeof entry.text!=='string')return fail('Saisie invalide.');w.value=entry.value;w.date=entry.date;w.text=entry.text;}
 const error=boardError(board);if(error)return fail(error);const saved=await db.prepare('UPDATE team_dashboards SET data=?,revision=revision+1,updated_at=?,updated_by=? WHERE id=? AND revision=?').bind(JSON.stringify(board),new Date().toISOString(),gate.user!.displayName,b.id,b.revision).run();if(!saved.meta.changes)return fail('Tableau modifié. Fermez et actualisez avant de réessayer.',409);return response({ok:true});
}
if(b.action==='team'){if(gate.user!.role!=='admin')return fail('Seul un administrateur peut organiser les équipes.',403);if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100||![1,2].includes(b.rank))return fail('Nom et rang de l’équipe invalides.');if(b.rank===2&&b.id&&b.parentId===b.id)return fail('Une équipe ne peut pas être sa propre parente.');if(b.rank===2&&!(typeof b.parentId==='string'&&await db.prepare('SELECT id FROM teams WHERE id=? AND rank=1').bind(b.parentId).first()))return fail('Choisissez une équipe parente de rang 1.');if(b.id){if(typeof b.id!=='string'||!Number.isInteger(b.revision))return fail('Révision invalide.');if(b.rank===2&&await db.prepare('SELECT id FROM teams WHERE parent_id=?').bind(b.id).first())return fail('Cette équipe possède des services de rang 2 : conservez son rang 1.');const r=await db.prepare('UPDATE teams SET name=?,rank=?,parent_id=?,revision=revision+1 WHERE id=? AND revision=?').bind(b.name.trim(),b.rank,b.rank===2?b.parentId:null,b.id,b.revision).run();if(!r.meta.changes)return fail('Équipe modifiée depuis son ouverture. Actualisez.',409);return response({id:b.id})}const id=crypto.randomUUID();await db.prepare('INSERT INTO teams (id,name,rank,parent_id,revision) VALUES (?,?,?,?,1)').bind(id,b.name.trim(),b.rank,b.rank===2?b.parentId:null).run();return response({id})}
if(!['create','save'].includes(b.action)||typeof b.teamId!=='string'||typeof b.scope!=='string')return fail('Saisie invalide.');const error=boardError(b.board);if(error)return fail(error);if(!await db.prepare('SELECT id FROM teams WHERE id=?').bind(b.teamId).first())return fail('Équipe introuvable.',404);if(!await teamsAllowed(gate.user!,[b.teamId],true))return fail('Modification de cette équipe non autorisée.',403);if(b.scope&&!await teamsAllowed(gate.user!,['qsse']))return fail('Accès QSSE nécessaire pour un périmètre DUERP.',403);if(b.scope!==''&&b.scope!=='*'&&!await db.prepare('SELECT code FROM evrp_units WHERE code=?').bind(b.scope).first())return fail('Périmètre DUERP invalide.');const now=new Date().toISOString(),author=gate.user!.displayName;
if(b.action==='create'){const id=crypto.randomUUID();await db.prepare('INSERT INTO team_dashboards (id,team_id,unit_code,data,revision,updated_at,updated_by) VALUES (?,?,?,?,1,?,?)').bind(id,b.teamId,b.scope,JSON.stringify(b.board),now,author).run();return response({id})}
if(typeof b.id!=='string'||!Number.isInteger(b.revision)||b.revision<1)return fail('Révision invalide.');const old=await db.prepare('SELECT team_id FROM team_dashboards WHERE id=?').bind(b.id).first<any>();if(!old||!await teamsAllowed(gate.user!,[old.team_id],true))return fail('Modification de ce tableau non autorisée.',403);const result=await db.prepare('UPDATE team_dashboards SET team_id=?,unit_code=?,data=?,revision=revision+1,updated_at=?,updated_by=? WHERE id=? AND revision=?').bind(b.teamId,b.scope,JSON.stringify(b.board),now,author,b.id,b.revision).run();if(!result.meta.changes)return fail('Ce tableau a été modifié. Votre saisie est conservée ; annulez puis actualisez pour récupérer la dernière version.',409);return response({revision:b.revision+1,updatedAt:now,updatedBy:author})}catch(e){console.error(e);return fail('Enregistrement impossible. Votre saisie est conservée.',503)}}
