'use client';
import {useEffect,useState} from 'react';
export type Account={id:string;username:string;displayName:string;role:'admin'|'editor'|'reader';mustChangePassword:boolean};
async function auth(body:Record<string,string>){const res=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data:any=await res.json();if(!res.ok)throw Error(data.error||'Connexion impossible.');return data}
export function AccountGate({children}:{children:(account:Account,logout:()=>void)=>React.ReactNode}){const [account,setAccount]=useState<Account|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{fetch('/api/auth').then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);setAccount(d.account)}).catch(e=>setError(e.message)).finally(()=>setReady(true))},[]);
async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const data=account?.mustChangePassword?await auth({action:'password',oldPassword:password,newPassword}):await auth({action:'login',username,password});setAccount(data.account);setPassword('');setNewPassword('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function logout(){try{await auth({action:'logout'})}finally{setAccount(null);setPassword('');setNewPassword('')}}
if(!ready)return <div className="login-page"><p role="status">Ouverture de l’espace QSE…</p></div>;
if(account&&!account.mustChangePassword)return <>{children(account,logout)}</>;
return <main className="login-page"><section className="login-card"><img src="/polytechs-logo.png" width="180" height="100" alt="Polytechs"/><span className="brand-sub">ESPACE QSE</span><h1>{account?'Sécuriser votre compte':'Connexion'}</h1><p>{account?'Choisissez un nouveau mot de passe avant d’accéder aux fiches QSE.':'Saisissez votre identifiant et votre mot de passe pour accéder aux registres.'}</p><form onSubmit={submit}>{!account&&<label>Identifiant<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required autoFocus/></label>}<label>{account?'Mot de passe actuel':'Mot de passe'}<input type="password" autoComplete={account?'current-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{account&&<label>Nouveau mot de passe <small>(12 caractères minimum)</small><input type="password" autoComplete="new-password" minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></label>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Veuillez patienter…':account?'Enregistrer le mot de passe':'Se connecter'}</button></form>{account&&<button className="text-link" onClick={logout}>Changer de compte</button>}</section></main>}

const labels={admin:'Administrateur · accès complet',editor:'Contributeur · lecture et modification',reader:'Lecteur · consultation'};
type User={id:string;username:string;display_name:string;role:Account['role'];must_change_password:number};
export function AccountPanel({account}:{account:Account}){const [users,setUsers]=useState<User[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<Account['role']>('reader');
async function load(){try{const r=await fetch('/api/users');const d:any=await r.json();if(!r.ok)throw Error(d.error);setUsers(d.users)}catch(e){setError((e as Error).message)}}
useEffect(()=>{load()},[]);
async function send(body:Record<string,string>){setError('');setNotice('');try{const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setNotice('Compte mis à jour.');return true}catch(e){setError((e as Error).message);return false}}
async function create(e:React.FormEvent){e.preventDefault();if(await send({action:'create',username,displayName,password,role})){setUsername('');setDisplayName('');setPassword('')}}
return <section className="panel accounts-panel"><h2>Utilisateurs et droits</h2><p>Les administrateurs gèrent les comptes et les fiches. Les contributeurs modifient les fiches. Les lecteurs peuvent consulter et exporter.</p>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}<div className="accounts-list">{users.map(user=><div key={user.id} className="account-row"><div><strong>{user.display_name}</strong><small>{user.username} · {user.must_change_password?'Mot de passe initial à modifier':'Compte actif'}</small></div><select aria-label={'Rôle de '+user.display_name} value={user.role} disabled={user.id===account.id} onChange={e=>send({action:'role',id:user.id,role:e.target.value})}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>)}</div><h3>Ajouter un utilisateur</h3><form className="account-create" onSubmit={create}><label>Nom<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required maxLength={100}/></label><label>Identifiant<input value={username} onChange={e=>setUsername(e.target.value)} pattern="[a-zA-Z0-9._-]{3,40}" required/></label><label>Mot de passe initial<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/></label><label>Rôle<select value={role} onChange={e=>setRole(e.target.value as Account['role'])}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button className="primary">Créer le compte</button></form><p>Le nouvel utilisateur devra choisir son propre mot de passe à sa première connexion.</p></section>}
