'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Bell,LayoutDashboard,Ticket,CalendarDays,Megaphone,ArrowLeft} from 'lucide-react';
import {TeamTree} from '@/components/team-navigation';
export type Meta={teams:{id:string;name:string;rank:number;parent_id:string|null}[];editableTeams?:string[];users:{id:string;display_name:string}[]};
export async function hubRequest(path:string,body?:unknown){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d:any=await r.json();if(!r.ok)throw Error(d.error||'Opération indisponible.');return d}
export function useHubMeta(){const [meta,setMeta]=useState<Meta>({teams:[],users:[]}),[error,setError]=useState('');useEffect(()=>{let live=true;hubRequest('/api/hub').then(d=>{if(live)setMeta(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);return {meta,error}}
export function WorkspaceNav({active,disabled=false}:{active:string;disabled?:boolean}){const [notifications,setNotifications]=useState<any[]>([]),[unread,setUnread]=useState(0),[error,setError]=useState('');async function load(){try{const d=await hubRequest('/api/hub?scope=notifications');setNotifications(d.notifications);setUnread(d.unread);setError('')}catch{setError('Notifications indisponibles.')}}useEffect(()=>{load();const id=setInterval(load,60000);return()=>clearInterval(id)},[]);return <header className="hub-topbar"><nav aria-label="Navigation principale">{[['Dashboard','/unites',LayoutDashboard],['Mon travail','/work',LayoutDashboard],['Tickets','/tickets',Ticket],['Routines','/routines',CalendarDays],['Communication','/communication',Megaphone]].map(([name,href,Icon]:any)=><a key={name} href={disabled?undefined:href} aria-disabled={disabled} aria-current={active===name?'page':undefined}><Icon size={17}/>{name}</a>)}</nav><details className="hub-bell" onToggle={e=>{if(e.currentTarget.open)load()}}><summary aria-label={'Notifications : '+unread+' non lues'}><Bell size={19}/>{unread>0&&<b>{unread}</b>}</summary><div className="hub-notification-panel"><h3>Notifications internes</h3>{error&&<p role="alert">{error}</p>}{!notifications.length&&!error&&<p>Aucune notification.</p>}{notifications.map(n=><a className={n.seen?'':'unread'} key={n.id} href={disabled?undefined:n.href} onClick={async e=>{e.preventDefault();if(disabled)return;try{await hubRequest('/api/hub',{action:'read',id:n.id});location.href=n.href}catch{setError('Impossible de marquer cette notification comme lue.')}}}><strong>{n.title}</strong><small>{new Date(n.created_at).toLocaleString('fr-FR')}</small></a>)}</div></details></header>}
export function HubFrame({active,children}:{active:string;children:ReactNode}){const [tree,setTree]=useState<any>(null);useEffect(()=>{let live=true;hubRequest('/api/dashboards').then(d=>{if(live)setTree(d)}).catch(()=>{});return()=>{live=false}},[]);return <div className="team-workspace hub-workspace"><aside className="team-sidebar"><a className="team-brand" href="/unites"><img src="/polytechs-logo.png" alt="Polytechs"/></a><a className="team-home" href="/qse"><ArrowLeft size={16}/> Modules QSE</a><p className="navlabel">ÉQUIPES</p>{tree?<TeamTree teams={tree.teams} boards={tree.boards}/>:<a href="/unites">Ouvrir les équipes</a>}</aside><div className="hub-main"><WorkspaceNav active={active}/><main className="hub-content">{children}</main></div></div>}
export function TeamPicker({meta,value,onChange,disabled=false,label='Équipes concernées'}:{meta:Meta;value:string[];onChange:(v:string[])=>void;disabled?:boolean;label?:string}){return <fieldset className="hub-team-picker" disabled={disabled}><legend>{label}</legend>{meta.teams.filter(t=>!meta.editableTeams||meta.editableTeams.includes(t.id)).map(t=><label key={t.id}><input type="checkbox" checked={value.includes(t.id)} onChange={e=>onChange(e.target.checked?[...value,t.id]:value.filter(id=>id!==t.id))}/>{t.name}</label>)}</fieldset>}
export function UserPicker({meta,value,onChange,disabled=false,label='Pilote'}:{meta:Meta;value:string;onChange:(v:string)=>void;disabled?:boolean;label?:string}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}><option value="">À désigner</option>{meta.users.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label>}
