'use client';
import {useEffect,useState,useSyncExternalStore,type ReactNode} from 'react';
import {Bell,LayoutDashboard,Ticket,CalendarDays,Megaphone,ListChecks,Layers,Settings2} from 'lucide-react';
import {TeamTree,type Team,type BoardLink} from '@/components/team-navigation';
import {ServiceSidebar} from '@/components/service-sidebar';
import {serviceHref} from '@/lib/navigation';
import {teamVisual} from '@/lib/ticket-visuals';
import {TeamMark} from '@/components/ticket-visuals';
import {TicketSearchPicker} from '@/components/ticket-search-picker';
import {TeamAccessPanel} from '@/components/team-access-panel';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ProfileMenu} from '@/components/profile';
export type Meta={teams:{id:string;name:string;rank:number;parent_id:string|null}[];editableTeams?:string[];contributingTeams?:string[];managedTeams?:string[];users:{id:string;display_name:string}[]};
export {hubRequest} from '@/lib/hub-request';
import {hubRequest} from '@/lib/hub-request';
export function useHubMeta(){const [meta,setMeta]=useState<Meta>({teams:[],users:[]}),[error,setError]=useState('');useEffect(()=>{let live=true;hubRequest('/api/hub').then(d=>{if(live)setMeta(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);return {meta,error}}
const navigation=[{name:'SMI',href:'/smi',Icon:Layers},{name:'Dashboard',href:'/unites',Icon:LayoutDashboard},{name:'Tickets',href:'/tickets',Icon:Ticket},{name:'Routines',href:'/routines',Icon:CalendarDays},{name:'Communication',href:'/communication',Icon:Megaphone}];
function subscribeService(onChange:()=>void){window.addEventListener('popstate',onChange);window.addEventListener('polytechs-service',onChange);return()=>{window.removeEventListener('popstate',onChange);window.removeEventListener('polytechs-service',onChange)}}
export function useServiceFilter():[string,(value:string)=>void]{const team=useSyncExternalStore(subscribeService,()=>new URLSearchParams(location.search).get('team')||'',()=>'');return [team,value=>{history.replaceState(null,'',serviceHref(location.pathname+location.search,value));window.dispatchEvent(new Event('polytechs-service'))}]}
type Notification={id:string;title:string;href:string;seen:number;created_at:string};
export function WorkspaceNav({active,disabled=false,teamId,teamName}:{active:string;disabled?:boolean;teamId?:string;teamName?:string}){
const {meta:permissionMeta}=useHubMeta();const [settingsOpen,setSettingsOpen]=useState(false);const [context]=useServiceFilter(),[notifications,setNotifications]=useState<Notification[]>([]),[unread,setUnread]=useState(0),[error,setError]=useState('');
async function load(){try{const d=await hubRequest('/api/hub?scope=notifications');setNotifications(d.notifications);setUnread(d.unread);setError('')}catch{setError('Notifications indisponibles.')}}
useEffect(()=>{const id=setInterval(load,60000);fetch('/api/hub?scope=notifications').then(async response=>{const d=await response.json() as {notifications:Notification[];unread:number};if(!response.ok)throw Error();setNotifications(d.notifications);setUnread(d.unread)}).catch(()=>setError('Notifications indisponibles.'));return()=>clearInterval(id)},[]);
return <><div className="workspace-team-heading"><small>{teamId??context?'ESPACE ÉQUIPE':'ESPACE PERSONNEL ET TRANSVERSAL'}</small><strong data-no-translate>{teamName||permissionMeta.teams.find(t=>t.id===(teamId??context))?.name||(teamId??context?'Équipe':'Polytechs')}</strong>{permissionMeta.managedTeams?.includes(teamId??context)&&<button className="outline team-settings-trigger" disabled={disabled} onClick={()=>setSettingsOpen(true)}><Settings2 size={16}/> Membres et paramètres</button>}</div><Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="team-settings-dialog"><DialogTitle>Paramètres de l’équipe</DialogTitle><DialogDescription>Gérer les membres et leurs droits dans cette équipe.</DialogDescription><TeamAccessPanel teamId={teamId??context}/></DialogContent></Dialog><header className="hub-topbar"><nav aria-label="Navigation principale">{navigation.map(({name,href,Icon})=><a key={name} href={disabled?undefined:serviceHref(href,name==='Mon travail'?'':teamId??context)} aria-disabled={disabled} aria-current={active===name?'page':undefined}><Icon size={17}/>{name}</a>)}</nav><div className="hub-topbar-actions"><details className="hub-bell" onToggle={e=>{if(e.currentTarget.open)load()}}><summary aria-label={'Notifications : '+unread+' non lues'}><Bell size={19}/>{unread>0&&<b>{unread}</b>}</summary><div className="hub-notification-panel"><h3>Notifications internes</h3>{error&&<p role="alert">{error}</p>}{!notifications.length&&!error&&<p>Aucune notification.</p>}{notifications.map(n=><a className={n.seen?'':'unread'} key={n.id} href={disabled?undefined:n.href} onClick={async e=>{e.preventDefault();if(disabled)return;try{await hubRequest('/api/hub',{action:'read',id:n.id});location.href=n.href}catch{setError('Impossible de marquer cette notification comme lue.')}}}><strong>{n.title}</strong><small>{new Date(n.created_at).toLocaleString(document.documentElement.lang||'fr')}</small></a>)}</div></details><ProfileMenu/></div></header></>}
export function HubFrame({active,children,className='',teamId}:{active:string;children:ReactNode;className?:string;teamId?:string}){const [context]=useServiceFilter();const effectiveTeam=teamId??context;const [tree,setTree]=useState<{teams:Team[];boards:BoardLink[]}|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;hubRequest('/api/dashboards').then(d=>{if(live)setTree(d)}).catch(()=>{if(live)setError('Les services ne sont pas disponibles.')});return()=>{live=false}},[]);return <div className={'team-workspace hub-workspace '+className}><a className="skip-link" href="#workspace-content">Aller au contenu</a><ServiceSidebar><p className="navlabel">SERVICES ET MODULES</p>{tree?<TeamTree teams={tree.teams} boards={tree.boards}/>:<div className="service-nav-state"><p role={error?'alert':'status'}>{error||'Chargement des services…'}</p><a href="/unites">Ouvrir les services</a></div>}</ServiceSidebar><div className="hub-main"><WorkspaceNav active={active} teamId={effectiveTeam} teamName={tree?.teams.find(t=>t.id===effectiveTeam)?.name}/><main id="workspace-content" tabIndex={-1} className="hub-content">{children}</main></div></div>}
export function TeamPicker({meta,value,onChange,disabled=false,label='Équipes concernées',visual=false}:{meta:Meta;value:string[];onChange:(v:string[])=>void;disabled?:boolean;label?:string;visual?:boolean}){if(visual)return <TicketSearchPicker label={label} options={meta.teams.filter(t=>disabled||!meta.editableTeams||meta.editableTeams.includes(t.id))} value={value} onChange={onChange} disabled={disabled}/>;return <fieldset className={'hub-team-picker'+(visual?' ticket-team-picker':'')} disabled={disabled}><legend>{label}</legend>{meta.teams.filter(t=>disabled||!meta.editableTeams||meta.editableTeams.includes(t.id)).map(t=><label key={t.id} data-team-family={visual?teamVisual(t.id).family:undefined}><input type="checkbox" checked={value.includes(t.id)} onChange={e=>onChange(e.target.checked?[...value,t.id]:value.filter(id=>id!==t.id))}/>{visual?<TeamMark id={t.id} name={t.name}/>:<span>{t.name}</span>}</label>)}</fieldset>}
export function UserPicker({meta,value,onChange,disabled=false,label='Pilote'}:{meta:Meta;value:string;onChange:(v:string)=>void;disabled?:boolean;label?:string}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}><option value="">À désigner</option>{meta.users.map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></label>}
