'use client';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {createContext,useContext,useEffect,useRef,useState,useCallback,type ReactNode} from 'react';
import {Camera,LogOut,UserRound,X} from 'lucide-react';
import type {Account} from './account-gate';
import {applyLocale,languages,watchLocale,translate,type Locale} from '@/lib/interface-locale';

type Profile={locale:Locale;photoUrl:string};
type Context={account:Account;logout:()=>void;profile:Profile;setProfile:(profile:Profile)=>void;ready:boolean;loadError:string;reload:()=>void};
const ProfileContext=createContext<Context|null>(null);
const initial:Profile={locale:'fr',photoUrl:''};
export function ProfileProvider({account,logout,children}:{account:Account;logout:()=>void;children:ReactNode}){
 const [profile,setProfile]=useState<Profile>(initial),[ready,setReady]=useState(false),[loadError,setLoadError]=useState(''),[reloadKey,setReloadKey]=useState(0);
 const reload=useCallback(()=>setReloadKey(n=>n+1),[]);
 useEffect(()=>{const controller=new AbortController();setReady(false);setLoadError('');fetch('/api/profile',{cache:'no-store',signal:controller.signal}).then(async r=>{const p=await r.json() as Profile&{error?:string};if(!r.ok)throw Error(p.error);if(!controller.signal.aborted){setProfile({locale:p.locale,photoUrl:p.photoUrl});setReady(true)}}).catch(()=>{if(!controller.signal.aborted)setLoadError('Profil indisponible.')});return()=>controller.abort()},[account.id,reloadKey]);
 useEffect(()=>watchLocale(profile.locale),[profile.locale]);
 return <ProfileContext.Provider value={{account,logout,profile,setProfile,ready,loadError,reload}}>{children}</ProfileContext.Provider>
}
function Avatar({url,name}:{url:string;name:string}){return url?<img src={url} alt="" className="profile-avatar"/>:<span className="profile-avatar profile-initials" aria-hidden="true">{name.trim().split(/\s+/).slice(0,2).map(n=>n[0]?.toUpperCase()).join('')||<UserRound size={18}/>}</span>}
async function preparePhoto(file:File){const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const context=canvas.getContext('2d');if(!context)throw Error('Image illisible.');const size=Math.min(image.naturalWidth,image.naturalHeight);context.drawImage(image,(image.naturalWidth-size)/2,(image.naturalHeight-size)/2,size,size,0,0,512,512);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.85));if(!blob)throw Error('Image illisible.');return new File([blob],'photo.jpg',{type:'image/jpeg'})}finally{URL.revokeObjectURL(url)}}
export function ProfileMenu(){const ctx=useContext(ProfileContext),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),ref=useRef<HTMLDivElement>(null);

 if(!ctx)return null;
 const {account,profile,setProfile,logout,ready,loadError,reload}=ctx;
 async function request(method:'POST'|'PUT'|'DELETE',body?:string|File){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/profile',{method,headers:body instanceof File?{'Content-Type':body.type}:body?{'Content-Type':'application/json'}:undefined,body});const data=await response.json() as Profile&{error?:string};if(!response.ok)throw Error(data.error||'Opération impossible.');setProfile({locale:data.locale,photoUrl:data.photoUrl});return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function changeLanguage(locale:Locale){const previous=profile;setProfile({...previous,locale});applyLocale(locale);const response=await request('POST',JSON.stringify({locale}));if(!response)setProfile(previous);else setNotice('Langue enregistrée.')}
 async function changePhoto(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12_000_000){setError('Choisissez une image JPEG, PNG ou WebP de 12 Mo maximum.');return}setBusy(true);setError('');try{if(await request('PUT',await preparePhoto(file)))setNotice('Photo enregistrée.')}catch{setError('Impossible de lire cette image.')}finally{setBusy(false)}}
 async function removePhoto(){if(await request('DELETE'))setNotice('Photo supprimée.')}
 return <div className="profile-control" ref={ref}><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button type="button" className="profile-trigger" onClick={()=>{setError('');setNotice('')}} aria-expanded={open} aria-haspopup="dialog" aria-label={translate('Mon profil',profile.locale)}><Avatar url={profile.photoUrl} name={account.displayName}/></button></PopoverTrigger><PopoverContent align="end" sideOffset={10} aria-label={translate('Mon profil',profile.locale)} className="profile-popover"><div className="profile-heading"><strong>Mon profil</strong><button type="button" onClick={()=>setOpen(false)} aria-label={translate('Fermer',profile.locale)}><X size={17}/></button></div><div className="profile-identity"><Avatar url={profile.photoUrl} name={account.displayName}/><div data-no-translate><strong>{account.displayName}</strong><small>{account.username}</small></div></div><div className="profile-photo-actions"><label className="profile-upload"><Camera size={16}/> Changer la photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!ready} onChange={e=>{void changePhoto(e.target.files?.[0]);e.target.value=''}}/></label>{profile.photoUrl&&<button type="button" disabled={busy||!ready} onClick={removePhoto}>Supprimer la photo</button>}</div><p className="profile-hint">JPEG, PNG ou WebP · 12 Mo maximum · cadrage carré automatique</p><div className="profile-language"><label htmlFor="profile-language">Langue du site</label><select id="profile-language" value={profile.locale} disabled={busy||!ready} onChange={e=>void changeLanguage(e.target.value as Locale)}>{Object.entries(languages).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><p>Choisissez votre langue. Elle sera conservée pour vos prochaines connexions.</p></div>{loadError&&<p role="alert" className="profile-error">{loadError} <button onClick={reload}>Réessayer</button></p>}{!ready&&!loadError&&<p role="status">Chargement…</p>}{error&&<p role="alert" className="profile-error">{error}</p>}{notice&&<p role="status" className="profile-success">{notice}</p>}<button type="button" className="profile-signout" onClick={()=>{setOpen(false);void logout()}}><LogOut size={16}/> Déconnexion</button></PopoverContent></Popover></div>
}
