'use client';
import {useEffect,useState} from 'react';
import {LayoutDashboard,Users} from 'lucide-react';
export type Team={id:string;name:string;rank:number;parent_id:string|null;revision:number};
export type BoardLink={id:string;team_id:string;title:string;unit_code:string};
export function TeamTree({teams,boards,selected,disabled,onSelect,onTeam}:{teams:Team[];boards:BoardLink[];selected?:string;disabled?:boolean;onSelect?:(id:string)=>void;onTeam?:(team:Team)=>void}){
function teamNode(t:Team){return <div className={'team-node rank-'+t.rank} key={t.id}><details open><summary><Users size={16}/><span>{t.name}</span><small>Rang {t.rank}</small></summary><div className="team-boards">{boards.filter(b=>b.team_id===t.id).map(b=>onSelect?<button key={b.id} disabled={disabled} aria-current={selected===b.id?'page':undefined} onClick={()=>onSelect(b.id)}><LayoutDashboard size={14}/><span>{b.title}</span></button>:<a key={b.id} href={'/unites?board='+encodeURIComponent(b.id)}><LayoutDashboard size={14}/><span>{b.title}</span></a>)}{onTeam&&<button disabled={disabled} className="team-open" onClick={()=>onTeam(t)}>Ouvrir l’équipe</button>}{!boards.some(b=>b.team_id===t.id)&&<small className="team-no-board">Aucun tableau</small>}</div>{teams.filter(c=>c.parent_id===t.id&&c.rank===2).map(teamNode)}</details></div>}
return <nav className="team-tree" aria-label="Équipes et tableaux de bord">{teams.filter(t=>t.rank===1).map(teamNode)}</nav>}
export function HomeTeamNavigation(){const [data,setData]=useState<{teams:Team[];boards:BoardLink[]}|null>(null),[error,setError]=useState(false);useEffect(()=>{const c=new AbortController();fetch('/api/dashboards',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error();setData(await r.json())}).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>c.abort()},[]);return <div className="home-team-navigation"><p className="navlabel">ÉQUIPES ET TABLEAUX</p>{data?<TeamTree teams={data.teams} boards={data.boards}/>:<a href="/unites">{error?'Ouvrir les équipes':'Chargement des équipes…'}</a>}</div>}
