'use client';
import {useEffect,useState} from 'react';
type Data={teams:{id:string;name:string;rank:number}[];users:{id:string;display_name:string;role:string}[];settings:{team_id:string;restricted:number}[];members:{team_id:string;user_id:string;level:string}[]};
export function TeamAccessPanel(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  async function load(){try{const r=await fetch('/api/team-access'),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}}
  useEffect(()=>{load()},[]);
  async function save(body:unknown){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/team-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setNotice('Droits enregistrés.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="team-access-panel"><h3>Droits par équipe</h3><p>Ce réglage protège les tableaux, tickets, routines et communications associés à l’équipe. Les administrateurs conservent l’accès. « Consultation » permet de lire ; « Contribution » permet de modifier si le rôle global l’autorise. Les fiches QSE et le DUERP suivent encore les rôles globaux.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}{!data&&!error&&<p>Chargement des équipes…</p>}{data?.teams.map(t=>{const restricted=!!data.settings.find(s=>s.team_id===t.id)?.restricted;return <details key={t.id} className="team-access-group"><summary>{t.name} · rang {t.rank} · {restricted?'Restreinte':'Ouverte'}</summary><label className="team-access-switch"><input type="checkbox" checked={restricted} disabled={busy} onChange={e=>save({action:'restrict',teamId:t.id,restricted:e.target.checked})}/> Restreindre cette équipe aux membres désignés</label><div className="team-access-users">{data.users.filter(u=>u.role!=='admin').map(u=><label key={u.id}>{u.display_name}<small>Rôle global : {u.role}</small><select disabled={busy} value={data.members.find(m=>m.team_id===t.id&&m.user_id===u.id)?.level||'none'} onChange={e=>save({action:'member',teamId:t.id,userId:u.id,level:e.target.value})}><option value="none">Aucun accès si restreinte</option><option value="viewer">Consultation</option><option value="contributor" disabled={u.role==='reader'}>Contribution</option></select></label>)}</div></details>})}</section>
}
