export const frequency=[{value:1,label:'Exceptionnelle'},{value:3,label:'Occasionnelle'},{value:7,label:'Régulière'},{value:10,label:'Permanente'}];
export const gravity=[{value:1,label:'Sans arrêt'},{value:3,label:'Avec arrêt'},{value:7,label:'Incapacité permanente'},{value:10,label:'Décès'}];
export const mastery=[{value:1,label:'Aucune protection'},{value:.5,label:'Humaine'},{value:.35,label:'Organisationnelle'},{value:.2,label:'Collective ou technique'}];
export const detection=[{value:1,label:'Aucun premier soin'},{value:1.3,label:'Un premier soin'},{value:1.5,label:'Plusieurs premiers soins ou un AT sans arrêt'},{value:2,label:'Plusieurs AT sans arrêt ou un AT avec arrêt'}];
export type Risk={id:string;unitCode:string;factor:string;risk:string;applicable:boolean;exposure:string;existing:string;frequencyLabel:string;f:number|null;gravityLabel:string;g:number|null;masteryLabel:string;im:number|null;detectionLabel:string;detection:number|null;accidentDate:string;sourceScore:number|null;planned:string;sourceSheet:string;sourceRow:number;reviewReasons:string[];reviewComment?:string;};
export function riskScore(r:Pick<Risk,'f'|'g'|'im'|'detection'|'applicable'>){if(!r.applicable||r.f===null||r.g===null||r.im===null||r.detection===null)return null;return Math.round(r.f*r.g*r.im*r.detection*100)/100}
// Plages du format conditionnel de « Synthèse risques professionnels ».
// À 20 et 40, la règle orange du classeur prime sur la plage précédente.
export function riskBand(score:number|null){if(score===null)return {key:'unknown',label:'À coter'};if(score<8)return {key:'green',label:'Vert · inférieur à 8'};if(score<20)return {key:'yellow',label:'Jaune · 8 à moins de 20'};if(score<=40)return {key:'orange',label:'Orange · 20 à 40'};return {key:'red',label:'Rouge · supérieur à 40'}}
export function riskErrors(r:Risk,status:string){const errors:string[]=[];if(!r.factor.trim()||!r.risk.trim())errors.push('Précisez le danger et le risque.');if(!r.unitCode)errors.push('Choisissez une unité de travail.');for(const [key,scale] of [['f',frequency],['g',gravity],['im',mastery],['detection',detection]] as const){const n=r[key];if(r.applicable&&n!==null&&!scale.some(x=>x.value===n))errors.push('Valeur de cotation non prévue : '+key)}if(status==='Validé'&&r.applicable){if(riskScore(r)===null)errors.push('Complétez les quatre indices avant la validation.');if(!r.exposure.trim())errors.push('Décrivez la situation d’exposition avant validation.');if(r.reviewReasons.length&&!r.reviewComment?.trim())errors.push('Documentez la vérification des anomalies du classeur.')}return errors}
export const riskStatuses=['À vérifier','En cours','Validé'] as const;
export const actionStatuses=['À définir','À faire','En cours','À vérifier','Clôturée'] as const;
