export type GedDocument={id:string;revision:number;ref:string;index:string;title:string;type:string;process:string;order:string;scopes:string[];created:string;updated:string;catalogStatus:string;updateRequired:boolean;sourceConform:string;comment:string;sourceSheet:string;sourceRow:number;sourceArchive:boolean;issues:string[];publishedVersionId:string;raw?:Record<string,string>;pending?:{id:string;status:string;authorId:string;reviewerId:string;approverId:string}};
export type GedDraft={ref:string;index:string;title:string;type:string;process:string;comment:string;changeReason:string;authorId:string;reviewerId:string;approverId:string;externalUrl:string};
export type GedVersion={id:string;document_id:string;data:GedDraft;status:string;revision:number;created_at:string;updated_at:string;reviewed_by:string;reviewed_at:string;approved_by:string;approved_at:string};
export type GedUser={id:string;display_name:string;role:string;managerId:string;qsse:boolean};
export const processes:Record<string,{name:string;team:string}>={M1:{name:'Direction',team:'direction'},M2:{name:'QSSE',team:'qsse'},R1:{name:'Commercial',team:'commercial'},R2:{name:'Planification',team:'planification'},R3:{name:'R&D',team:'rd'},R4:{name:'Fabrication',team:'production'},R5:{name:'Contrôle',team:'laboratoire'},R6:{name:'Logistique',team:'logistique'},S1:{name:'Travaux neufs',team:'travaux-neufs'},S2:{name:'Achats',team:'achats'},S3:{name:'Ressources humaines',team:'rh'},S4:{name:'Procédés',team:'procedes'},S5:{name:'Maintenance',team:'maintenance'},S6:{name:'Informatique',team:'informatique'}};
export const documentTypes=['Procédure','Imprimé','Mode opératoire','Liste','Manuel','Politique','Instruction','Cartographie','F. Contrôle','F. Formulation'];
export const openStatuses=['Brouillon','À corriger','Relecture QSSE','Approbation N+1'];
export const editableStatuses=['Brouillon','À corriger'];
export const scopeNames:Record<string,string>={G:'Direction',H:'Achats',I:'Administratif',J:'Commercial',K:'Ordonnancement',L:'Procédés',M:'Contrôle',N:'Qualité',O:'Maintenance',P:'Logistique',Q:'Fabrication',R:'Conception',S:'Environnement',T:'Communication',U:'Sécurité',V:'Informatique',W:'Travaux neufs',X:'Finances'};
export const scopeTeams:Record<string,string>={G:'direction',H:'achats',I:'rh',J:'commercial',K:'planification',L:'procedes',M:'laboratoire',N:'qsse',O:'maintenance',P:'logistique',Q:'production',R:'rd',S:'qsse',T:'qsse',U:'qsse',V:'informatique',W:'travaux-neufs',X:'direction'};
export function documentTeams(d:GedDocument){return [...new Set([processes[d.process]?.team||'qsse',...d.scopes.map(s=>scopeTeams[s]).filter(Boolean)])]}
export function draftFrom(d:GedDocument,authorId:string):GedDraft{return {ref:d.ref,index:d.index,title:d.title,type:d.type||'Procédure',process:d.process,comment:d.comment,changeReason:'',authorId,reviewerId:'',approverId:'',externalUrl:''}}
export function blankDocument():GedDocument{return {id:'',revision:0,ref:'',index:'a',title:'',type:'Procédure',process:'M2',order:'',scopes:[],created:'',updated:'',catalogStatus:'Brouillon',updateRequired:false,sourceConform:'',comment:'',sourceSheet:'',sourceRow:0,sourceArchive:false,issues:[],publishedVersionId:''}}
export function draftErrors(d:GedDraft,users:GedUser[],complete=false){const errors:string[]=[];for(const key of ['ref','index','title','type','process','comment','changeReason','authorId','reviewerId','approverId','externalUrl'] as const)if(typeof d[key]!=='string'||d[key].length>(['comment','changeReason'].includes(key)?5000:500))errors.push('Champ invalide : '+key);if(errors.length)return errors;if(!d.title.trim()||!d.ref.trim())errors.push('Renseignez la référence et le titre.');const author=users.find(u=>u.id===d.authorId&&u.role!=='reader');if(!author)errors.push('Choisissez un auteur contributeur ou administrateur.');if(d.externalUrl&&!/^https?:\/\//i.test(d.externalUrl))errors.push('Le lien doit commencer par https:// ou http://.');if(complete){if(!d.index.trim())errors.push('Renseignez l’indice de cette version.');if(!d.changeReason.trim())errors.push('Décrivez la création ou la modification.');if(!users.some(u=>u.id===d.reviewerId&&u.qsse&&u.role!=='reader'))errors.push('Désignez un relecteur du service QSSE.');if(!author?.managerId||author.managerId!==d.approverId)errors.push('Le N+1 de l’auteur doit être renseigné dans les paramètres de la GED.');if(!users.some(u=>u.id===d.approverId&&u.role!=='reader'))errors.push('Le N+1 doit pouvoir approuver des documents.');if(d.reviewerId===d.authorId||d.approverId===d.authorId)errors.push('L’auteur ne peut pas relire ou approuver sa propre version.')}return errors}
export function participant(v:GedVersion,userId:string){return [v.data.authorId,v.data.reviewerId,v.data.approverId].includes(userId)}
export function transition(v:GedVersion,action:string,userId:string,note:string){if(action==='submit'&&editableStatuses.includes(v.status)&&v.data.authorId===userId)return {status:'Relecture QSSE'};if(action==='review'&&v.status==='Relecture QSSE'&&v.data.reviewerId===userId)return {status:'Approbation N+1'};if(action==='approve'&&v.status==='Approbation N+1'&&v.data.approverId===userId&&v.reviewed_by)return {status:'Approuvé'};if(action==='reject'&&note.trim()&&((v.status==='Relecture QSSE'&&v.data.reviewerId===userId)||(v.status==='Approbation N+1'&&v.data.approverId===userId)))return {status:'À corriger'};if(action==='abandon'&&editableStatuses.includes(v.status)&&v.data.authorId===userId)return {status:'Abandonné'};return null}
