import {validDate,occurrenceDates,type Routine} from './hub';
export const orderStatuses=['À qualifier','À planifier','Planifiée','En cours','En attente','À vérifier','Clôturée','Annulée'];
export const orderPriorities=['Critique','Haute','Normale','Basse'];
export const orderTypes=['Correctif','Préventif','Amélioration','Contrôle'];
export const assetStatuses=['En service','À surveiller','Hors service','Retiré'];
export type GmaoAsset={code:string;name:string;teamId:string;location:string;family:string;parentId:string;manufacturer:string;model:string;serial:string;criticality:string;status:string;notes:string;gedId:string};
export type GmaoOrder={title:string;assetId:string;teamId:string;type:string;priority:string;description:string;location:string;status:string;technicianId:string;due:string;scheduled:string;requesterId:string;requester:string;ticketId:string;planId:string;occurrence:string;checklist:{id:string;label:string;done:boolean}[];safety:string;report:string;hours:number|null;externalCost:number|null;downtimeHours:number|null;result:string;completedAt:string;closedAt:string;closedBy:string;waitReason:string};
export type GmaoPlan={name:string;assetId:string;start:string;repeat:'weekly'|'monthly';interval:number;end:string;technicianId:string;priority:string;estimatedHours:number|null;instructions:string;tasks:string[];active:boolean};
export type GmaoPart={code:string;name:string;location:string;unit:string;minimum:number;unitCost:number|null;active:boolean};
export type GmaoRow<T>={id:string;data:T;revision:number;created_at?:string;updated_at?:string;quantity?:number};
export const newAsset=():GmaoAsset=>({code:'',name:'',teamId:'production',location:'',family:'',parentId:'',manufacturer:'',model:'',serial:'',criticality:'Normale',status:'En service',notes:'',gedId:''});
export const newOrder=():GmaoOrder=>({title:'',assetId:'',teamId:'production',type:'Correctif',priority:'Normale',description:'',location:'',status:'À qualifier',technicianId:'',due:'',scheduled:'',requesterId:'',requester:'',ticketId:'',planId:'',occurrence:'',checklist:[],safety:'',report:'',hours:null,externalCost:null,downtimeHours:null,result:'',completedAt:'',closedAt:'',closedBy:'',waitReason:''});
export const newPlan=():GmaoPlan=>({name:'',assetId:'',start:'',repeat:'monthly',interval:1,end:'',technicianId:'',priority:'Normale',estimatedHours:null,instructions:'',tasks:[''],active:true});
export const newPart=():GmaoPart=>({code:'',name:'',location:'',unit:'pièce',minimum:0,unitCost:null,active:true});
const string=(s:unknown,max=1000,required=false)=>typeof s==='string'&&s.length<=max&&(!required||!!s.trim());
const amount=(x:unknown)=>x===null||typeof x==='number'&&Number.isFinite(x)&&x>=0&&x<=100000000;
const date=(x:unknown)=>x===''||validDate(x);
export function assetError(a:GmaoAsset){return !a||!string(a.code,80,true)||!string(a.name,200,true)||!string(a.teamId,100,true)||!['location','family','parentId','manufacturer','model','serial','notes','gedId'].every(k=>string((a as any)[k],k==='notes'?5000:500))||!orderPriorities.includes(a.criticality)||!assetStatuses.includes(a.status)?'Vérifiez le code, le nom, le service et l’état de l’équipement.':''}
export function orderError(o:GmaoOrder){if(!o||!string(o.title,200,true)||!string(o.description,10000,true)||!string(o.assetId,100)||!string(o.teamId,100,true)||!string(o.location,500)||!orderTypes.includes(o.type)||!orderPriorities.includes(o.priority)||!orderStatuses.includes(o.status)||!date(o.due)||!date(o.scheduled)||!string(o.technicianId,100))return 'Renseignez le titre, le constat, le service et des dates valides.';for(const k of ['safety','report','result','waitReason'] as const)if(!string(o[k],5000))return 'Texte invalide : '+k;for(const k of ['hours','externalCost','downtimeHours'] as const)if(!amount(o[k]))return 'Les temps et coûts doivent être positifs.';if(!Array.isArray(o.checklist)||o.checklist.length>50||o.checklist.some(t=>!string(t.id,100,true)||!string(t.label,500,true)||typeof t.done!=='boolean')||new Set(o.checklist.map(t=>t.id)).size!==o.checklist.length)return 'Liste de contrôle invalide.';return ''}
export function planError(p:GmaoPlan){return !p||!string(p.name,200,true)||!string(p.assetId,100,true)||!validDate(p.start)||!date(p.end)||p.end&&p.end<p.start||!['weekly','monthly'].includes(p.repeat)||!Number.isInteger(p.interval)||p.interval<1||p.interval>52||!string(p.technicianId,100)||!orderPriorities.includes(p.priority)||!amount(p.estimatedHours)||!string(p.instructions,5000)||typeof p.active!=='boolean'||!Array.isArray(p.tasks)||!p.tasks.length||p.tasks.length>50||p.tasks.some(t=>!string(t,500,true))?'Vérifiez l’équipement, le calendrier et les points de contrôle.':''}
export function partError(p:GmaoPart){return !p||!string(p.code,80,true)||!string(p.name,200,true)||!string(p.location,500)||!string(p.unit,30,true)||!Number.isFinite(p.minimum)||p.minimum<0||!amount(p.unitCost)||typeof p.active!=='boolean'?'Vérifiez le code, le nom, l’unité et le seuil du stock.':''}
export function planDates(p:GmaoPlan,from:string,to:string){return occurrenceDates({...p,title:p.name,start:p.start,time:'08:00',questions:[],teams:[],pilot:p.technicianId,description:p.instructions} as Routine,from,to)}
export function transitionError(o:GmaoOrder,to:string){const paths:Record<string,string[]>={'À qualifier':['À planifier','Annulée'],'À planifier':['Planifiée','En cours','Annulée'],'Planifiée':['En cours','À planifier','Annulée'],'En cours':['En attente','À vérifier','Annulée'],'En attente':['En cours','Annulée'],'À vérifier':['Clôturée','En cours'],'Clôturée':[],'Annulée':[]};if(!paths[o.status]?.includes(to))return 'Cette étape ne suit pas l’état actuel de l’intervention.';if(['Planifiée','En cours','À vérifier','Clôturée'].includes(to)&&!o.technicianId)return 'Attribuez un technicien.';if(to==='Planifiée'&&!o.scheduled)return 'Renseignez la date de planification.';if(to==='En cours'&&!o.safety.trim())return 'Précisez les conditions de sécurité avant l’intervention.';if(to==='En attente'&&!o.waitReason.trim())return 'Précisez la cause de l’attente.';if(['À vérifier','Clôturée'].includes(to)&&(!o.report.trim()||!o.result.trim()||o.hours===null||o.checklist.some(t=>!t.done)))return 'Renseignez le compte rendu, le résultat, les heures réalisées et terminez les contrôles.';return ''}
export const finishedOrder=(o:GmaoOrder)=>['Clôturée','Annulée'].includes(o.status);
