export const categories=['Sécurité','Environnement','Production','Qualité','Ressources humaines','Maintenance','R&D','Autre'];
export const ticketStatuses=['Ouvert','En cours','À vérifier','Clôturé'];
export type Task={id:string;title:string;done:boolean;pilot:string;due:string};
export type Ticket={gmaoOrderId?:string;archivedAt?:string;archivedBy?:string;qualityActionId?:string;title:string;category:string;description:string;teams:string[];pilot:string;due:string;status:string;actions:Task[];responsibles:string[];source?:{routineId:string;date:string}};
export type Routine={title:string;description:string;teams:string[];pilot:string;start:string;time:string;repeat:'none'|'daily'|'weekly'|'monthly';interval:number;end:string;questions:{id:string;label:string}[];active:boolean};
export type Communication={title:string;body:string;sourceTeam:string;teams:string[]};
export type Row<T>={id:string;data:T;revision:number;created_at?:string;updated_at?:string;author?:string};
export type Run={answers:{id:string;label:string;result:string;comment:string}[];notes:string;completed:boolean};
export const validDate=(s:unknown):s is string=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
const str=(s:unknown,max:number,required=false)=>typeof s==='string'&&s.length<=max&&(!required||!!s.trim());
const ids=(v:unknown)=>Array.isArray(v)&&v.length<=100&&v.every(x=>str(x,100,true))&&new Set(v).size===v.length;
export function ticketError(v:Ticket){if(!v||!str(v.title,200,true)||!categories.includes(v.category)||!str(v.description,10000)||!ids(v.teams)||!ids(v.responsibles)||!str(v.pilot,100)||!str(v.due,10)||(v.due&&!validDate(v.due))||!ticketStatuses.includes(v.status))return 'Vérifiez le titre, la catégorie, les équipes, le pilote et l’échéance.';if(!Array.isArray(v.actions)||v.actions.length>100||v.actions.some(a=>!a||!str(a.id,100,true)||!str(a.title,500,true)||typeof a.done!=='boolean'||!str(a.pilot,100)||!str(a.due,10)||(a.due&&!validDate(a.due)))||new Set(v.actions.map(a=>a.id)).size!==v.actions.length)return 'Chaque action doit avoir un libellé et une date valide si renseignée.';if(v.status==='Clôturé'&&(!v.pilot||v.actions.some(a=>!a.done)))return 'Désignez un pilote et terminez toutes les actions avant de clôturer.';if(v.source&&(!str(v.source.routineId,100,true)||!validDate(v.source.date)))return 'Origine du ticket invalide.';return ''}
export function routineError(v:Routine){if(!v||!str(v.title,200,true)||!str(v.description,10000)||!ids(v.teams)||!str(v.pilot,100)||!validDate(v.start)||!str(v.end,10)||(v.end&&(!validDate(v.end)||v.end<v.start))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v.time)||!['none','daily','weekly','monthly'].includes(v.repeat)||!Number.isInteger(v.interval)||v.interval<1||v.interval>52||typeof v.active!=='boolean')return 'Vérifiez le titre, le calendrier et la récurrence.';if(!Array.isArray(v.questions)||v.questions.length<1||v.questions.length>100||v.questions.some(q=>!q||!str(q.id,100,true)||!str(q.label,500,true))||new Set(v.questions.map(q=>q.id)).size!==v.questions.length)return 'Ajoutez au moins un point de contrôle, sans doublon.';return ''}
export function communicationError(v:Communication){return !v||!str(v.title,200,true)||!str(v.body,15000,true)||!str(v.sourceTeam,100,true)||!ids(v.teams)||!v.teams.length?'Renseignez le titre, le message, le service émetteur et au moins une équipe destinataire.':''}
export function occurrenceDates(r:Routine,from:string,to:string){if(!r.active||!validDate(from)||!validDate(to)||!validDate(r.start)||from>to)return [];const days:string[]=[];const start=new Date(r.start+'T00:00:00Z');const limit=r.end&&r.end<to?r.end:to;if(r.repeat==='none')return r.start>=from&&r.start<=limit?[r.start]:[];if(r.repeat==='monthly'){const f=new Date(from+'T00:00:00Z');const diff=(f.getUTCFullYear()-start.getUTCFullYear())*12+f.getUTCMonth()-start.getUTCMonth();let n=Math.max(0,Math.floor(diff/r.interval));for(let guard=0;guard<500;guard++,n++){const month=start.getUTCMonth()+n*r.interval;const target=new Date(Date.UTC(start.getUTCFullYear(),month,1));const last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();target.setUTCDate(Math.min(start.getUTCDate(),last));const s=target.toISOString().slice(0,10);if(s>limit)break;if(s>=from)days.push(s)}}else{const step=r.interval*(r.repeat==='weekly'?7:1)*86400000;let n=Math.max(0,Math.ceil((Date.parse(from)-start.getTime())/step));for(let guard=0;guard<500;guard++,n++){const s=new Date(start.getTime()+n*step).toISOString().slice(0,10);if(s>limit)break;days.push(s)}}return days}
export const newTicket=():Ticket=>({title:'',category:'Sécurité',description:'',teams:[],pilot:'',due:'',status:'Ouvert',actions:[],responsibles:[]});
export const todayParis=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
