export type Field={key:string;label:string;type?:string;options?:string[]};
export const modules:Record<string,{domain:string;intro:string;fields:Field[]}>= {
'Gestion des déchets':{domain:'Environnement',intro:'Suivez les flux, les quantités et les filières de traitement.',fields:[{key:'code',label:'Code déchet'},{key:'quantity',label:'Quantité (kg)',type:'number'},{key:'date',label:'Date d’enlèvement',type:'date'},{key:'collector',label:'Collecteur / prestataire'},{key:'treatment',label:'Filière de traitement'},{key:'bsd',label:'Référence du bordereau'},{key:'dangerous',label:'Déchet dangereux',options:['À vérifier','Oui','Non']}]},
'Analyse environnementale':{domain:'Environnement',intro:'Identifiez vos aspects, leurs impacts et les moyens de maîtrise.',fields:[{key:'activity',label:'Activité / procédé'},{key:'aspect',label:'Aspect environnemental'},{key:'impact',label:'Impact associé'},{key:'severity',label:'Gravité',options:['1','2','3','4','5']},{key:'frequency',label:'Fréquence',options:['1','2','3','4','5']},{key:'controls',label:'Mesures de maîtrise'}]},
'RSE':{domain:'Environnement',intro:'Pilotez vos engagements et mesurez vos progrès.',fields:[{key:'axis',label:'Axe RSE',options:['Environnement','Social','Gouvernance']},{key:'goal',label:'Objectif'},{key:'indicator',label:'Indicateur / unité'},{key:'baseline',label:'Valeur de référence'},{key:'target',label:'Valeur cible'},{key:'actual',label:'Valeur actuelle'}]},
'Accidents du travail':{domain:'Sécurité',intro:'Consignez les faits et préparez le suivi interne des accidents.',fields:[{key:'date',label:'Date de l’accident',type:'date'},{key:'time',label:'Heure',type:'time'},{key:'place',label:'Lieu / atelier'},{key:'person',label:'Personne concernée (initiales)'},{key:'circumstances',label:'Circonstances factuelles'},{key:'immediate',label:'Mesures immédiates'},{key:'analysis',label:'Causes identifiées / analyse'}]},
'Situations dangereuses':{domain:'Sécurité',intro:'Remontez un danger et suivez sa mise en sécurité.',fields:[{key:'date',label:'Date du constat',type:'date'},{key:'place',label:'Lieu / atelier'},{key:'danger',label:'Danger observé'},{key:'exposure',label:'Personnes / activités exposées'},{key:'immediate',label:'Mise en sécurité immédiate'}]},
'DUERP':{domain:'Sécurité',intro:'Évaluez les risques par unité de travail et suivez les mesures de prévention.',fields:[{key:'unit',label:'Unité de travail'},{key:'activity',label:'Activité / tâche'},{key:'danger',label:'Danger / risque'},{key:'exposure',label:'Personnes exposées'},{key:'severity',label:'Gravité',options:['1','2','3','4','5']},{key:'frequency',label:'Fréquence',options:['1','2','3','4','5']},{key:'controls',label:'Prévention existante'},{key:'planned',label:'Mesures complémentaires'}]},
'EPI':{domain:'Sécurité',intro:'Suivez les équipements, les dotations et les contrôles.',fields:[{key:'equipment',label:'Type d’EPI'},{key:'reference',label:'Référence / norme'},{key:'assignee',label:'Bénéficiaire / service'},{key:'quantity',label:'Quantité',type:'number'},{key:'date',label:'Date de remise',type:'date'},{key:'check',label:'Prochain contrôle / renouvellement',type:'date'}]},
'Plans de prévention':{domain:'Sécurité',intro:'Préparez les interventions des entreprises extérieures.',fields:[{key:'contractor',label:'Entreprise extérieure'},{key:'operation',label:'Nature de l’intervention'},{key:'place',label:'Zone d’intervention'},{key:'start',label:'Début',type:'date'},{key:'end',label:'Fin',type:'date'},{key:'inspection',label:'Inspection commune',type:'date'},{key:'risks',label:'Risques de coactivité'},{key:'measures',label:'Mesures de prévention'},{key:'validation',label:'Validation du plan',options:['À préparer','À valider','Validé']}]},
'Gestion documentaire':{domain:'Qualité',intro:'Centralisez vos références, leurs versions et leurs échéances de révision.',fields:[{key:'reference',label:'Référence du document'},{key:'version',label:'Version'},{key:'category',label:'Type de document',options:['Procédure','Instruction','Formulaire','FDS','Autre']},{key:'validation',label:'Validation',options:['Brouillon','À valider','Approuvé','Obsolète']},{key:'review',label:'Prochaine révision',type:'date'}]},
'Réglementation':{domain:'Qualité',intro:'Tenez votre registre des exigences et des vérifications de conformité.',fields:[{key:'reference',label:'Texte / référence'},{key:'scope',label:'Périmètre d’application'},{key:'requirement',label:'Exigence applicable'},{key:'compliance',label:'Évaluation',options:['À évaluer','Conforme','Non conforme','Non applicable']},{key:'checked',label:'Dernière vérification',type:'date'},{key:'proof',label:'Preuve / justification'}]},
'Amélioration continue':{domain:'Qualité',intro:'Transformez les écarts et les idées en actions suivies.',fields:[{key:'origin',label:'Origine',options:['Non-conformité','Audit','Réclamation','Suggestion','Autre']},{key:'finding',label:'Constat'},{key:'cause',label:'Cause identifiée'},{key:'measure',label:'Action corrective / préventive'},{key:'effectiveness',label:'Vérification de l’efficacité'}]}
};
export const recordKinds=['Action','Audit',...Object.keys(modules)];
