import {validDate} from './hub';
export const actionStatuses=['NON COMMENCEE','EN COURS','REPORTEE','SOLDEE','CLOTUREE','ANNULEE'];
export const targets=['Humaine','Machine','Environnement','Produit','Plusieurs cibles'];
export type QualityAction={parentId?:string;id:string;revision:number;sourceRow:number;reference:string;created:string;service:string;teamId:string;pilot:string;pilotId:string;origin:string;problem:string;objective:string;method:string;action:string;hours:number|null;cost:number|null;gravity:number|null;exposure:number|null;target:string;validation:string;due:string;status:string;comment:string;usedHours:number|null;usedCost:number|null;criterion:string;afterGravity:number|null;afterExposure:number|null;effectiveEvidence:string;verifiedAt:string;verifiedBy:string;verificationNote:string;ticketId:string;gedId:string;sourceClass:string;sourceEffective:string;sourceNewAction:string;raw?:Record<string,string>};
export const serviceTeams:Record<string,string>={'M1':'direction','M2':'qsse','M3':'direction','R1':'commercial','R2/R6':'planification','R3':'rd','R4':'production','R5':'laboratoire','S1':'travaux-neufs','S2':'achats','S3':'rh','S4':'procedes','S5':'maintenance','S6':'informatique','AQ':'qsse'};
export const actionTeam=(a:QualityAction)=>a.teamId||serviceTeams[a.service.split(' - ')[0]]||'qsse';
export function priority(g:number|null,e:number|null){if(!g||!e)return 'A COTER';const score=g*e;return score>=16?'P1':score>=8?'P2':score>=4?'P3':'P4'}
export function proposedDue(a:QualityAction){const p=priority(a.gravity,a.exposure);if(p==='A COTER'||!validDate(a.created))return '';const d=new Date(a.created+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+(p==='P1'?30:p==='P2'?90:365));return d.toISOString().slice(0,10)}
export function engagement(a:QualityAction){if(a.hours===null||a.cost===null)return 'À chiffrer';return a.hours>200||a.cost>30000?'Investissement CAPEX':a.hours>40||a.cost>5000?'Chantier / projet':a.hours>8||a.cost>500?'Action courante':'Quick-win'}
export function effectiveness(a:QualityAction){if(a.status==='ANNULEE')return 'Annulée';if(!['SOLDEE','CLOTUREE'].includes(a.status))return 'À réaliser';if(!a.verifiedAt)return 'À vérifier';const before=priority(a.gravity,a.exposure),after=priority(a.afterGravity,a.afterExposure);if(before==='A COTER'||after==='A COTER')return 'À vérifier';return (before==='P1'||before==='P2'?['P3','P4'].includes(after):before==='P3'?after==='P4':Number(a.afterGravity)*Number(a.afterExposure)===1)?'Efficace':'Non efficace'}
export function actionIssues(a:QualityAction){const issues=[];if(priority(a.gravity,a.exposure)==='A COTER')issues.push('Cotation à compléter');if(a.created==='2026-08-13'&&a.sourceRow)issues.push('Date de consolidation : ouverture réelle à confirmer');if(!a.action||a.action==='(a definir)')issues.push('Action à définir');if(!a.pilotId)issues.push('Compte du pilote à associer');if(['SOLDEE','CLOTUREE'].includes(a.status)&&!a.verifiedAt)issues.push('Efficacité à vérifier');return issues}
export function actionError(a:QualityAction,today:string){for(const k of ['reference','created','service','teamId','pilotId','origin','problem','objective','method','action','target','validation','due','status','comment','criterion','effectiveEvidence','gedId'] as const)if(typeof a[k]!=='string'||a[k].length>10000)return 'Champ invalide : '+k; if(!a.action.trim()||!a.service||!validDate(a.created)||(a.due&&!validDate(a.due))||!actionStatuses.includes(a.status))return 'Renseignez l’action, le service, la date et un statut valide.';for(const k of ['gravity','exposure','afterGravity','afterExposure'] as const)if(a[k]!==null&&(!Number.isInteger(a[k])||a[k]!<1||a[k]!>5))return 'Les notes doivent être comprises entre 1 et 5.';for(const k of ['hours','cost','usedHours','usedCost'] as const)if(a[k]!==null&&(!Number.isFinite(a[k])||a[k]!<0))return 'Les ressources doivent être positives.';if(a.gravity&&a.exposure&&!targets.includes(a.target))return 'Précisez la cible majeure du danger.';if(a.due&&a.due<today&&!['CLOTUREE','ANNULEE'].includes(a.status)&&!a.comment.trim())return 'Un commentaire est obligatoire après dépassement de l’échéance décidée.';return ''}

export function blankQualityAction(created:string):QualityAction{return {id:'',revision:0,sourceRow:0,reference:'',created,service:'M2 - QSSE',teamId:'qsse',pilot:'',pilotId:'',origin:'ANOMALIE INTERNE',problem:'',objective:'',method:'',action:'',hours:null,cost:null,gravity:null,exposure:null,target:'',validation:'',due:'',status:'NON COMMENCEE',comment:'',usedHours:null,usedCost:null,criterion:'',afterGravity:null,afterExposure:null,effectiveEvidence:'',verifiedAt:'',verifiedBy:'',verificationNote:'',ticketId:'',gedId:'',sourceClass:'',sourceEffective:'',sourceNewAction:''}}

export const actionStatusLabels:Record<string,string>={'NON COMMENCEE':'À démarrer','EN COURS':'En cours','REPORTEE':'Reportée','SOLDEE':'Réalisée','CLOTUREE':'Clôturée','ANNULEE':'Annulée'};
export function verificationIssues(a:QualityAction){const missing=[];if(!['SOLDEE','CLOTUREE'].includes(a.status))missing.push('Marquer l’action réalisée');if(priority(a.gravity,a.exposure)==='A COTER')missing.push('Compléter la cotation initiale');if(priority(a.afterGravity,a.afterExposure)==='A COTER')missing.push('Compléter la cotation après action');if(!a.criterion.trim())missing.push('Définir un critère mesurable');if(!a.effectiveEvidence.trim())missing.push('Renseigner le résultat observé');return missing}
export function actionOrder(a:QualityAction,b:QualityAction,today:string){const finished=(x:QualityAction)=>x.status==='ANNULEE'||effectiveness(x)==='Efficace';const late=(x:QualityAction)=>!['SOLDEE','CLOTUREE','ANNULEE'].includes(x.status)&&!!x.due&&x.due<today;const ranks:Record<string,number>={P1:0,P2:1,P3:2,P4:3,'A COTER':4};return Number(finished(a))-Number(finished(b))||Number(late(b))-Number(late(a))||ranks[priority(a.gravity,a.exposure)]-ranks[priority(b.gravity,b.exposure)]||(a.due||'9999').localeCompare(b.due||'9999')||a.reference.localeCompare(b.reference,'fr',{numeric:true})}
