import type {Standard,Requirement} from './smi';
export const standardSeed:Standard[]=[{id:'iso9001-2026',badge:'Q',name:'ISO 9001',edition:'2026',color:'#005eaa',source:'https://www.iso.org/fr/standard/9001',active:true},{id:'iso14001-2026',badge:'E',name:'ISO 14001',edition:'2026',color:'#238151',source:'https://www.iso.org/fr/standard/14001',active:true},{id:'iso45001-2018',badge:'S',name:'ISO 45001',edition:'2018 + Amd 1:2024',color:'#c34949',source:'https://www.iso.org/fr/standard/88428.html',active:true}];
// Paraphrases de thèmes de suivi, pas reproduction des textes normatifs.
// Les sous-clausules sont consultables dans les exemplaires ISO de l’organisme.
type Theme=[string,string,string,string,string[],string?];
const common:Theme[]=[
['4.1','context','Compréhension du contexte','Analyser les enjeux internes et externes ; examiner la pertinence du changement climatique.',['Analyse du contexte','SWOT','PESTEL','Analyse des enjeux']],
['4.2','stakeholders','Parties intéressées','Identifier les parties concernées et les attentes à prendre en compte, dont celles liées au climat.',['Matrice des parties intéressées']],
['4.3','scope','Périmètre du système','Définir les activités et sites compris dans le système.',['Périmètre du SMI','Cartographie des sites']],
['4.4','system','Organisation du système','Décrire le fonctionnement des processus et leurs interactions.',['Manuel SMI','Cartographie des processus']],
['5.1','leadership','Engagement de la direction','Démontrer le pilotage, les moyens et la mobilisation de la direction.',['Revue de direction','Engagement de la direction']],
['5.2','policy','Politique et orientations','Partager des orientations adaptées au contexte.',['Politique QSSE']],
['5.3','roles','Responsabilités et autorités','Identifier les missions, responsabilités et délégations.',['Organigramme','Fiches de fonction']],
['6.1','risks','Risques et opportunités','Identifier, évaluer et traiter les risques et opportunités propres à chaque référentiel.',['Matrice risques et opportunités']],
['6.2','objectives','Objectifs et programme','Fixer les objectifs, les moyens, les pilotes et le suivi des résultats.',['Programme QSSE','Plan d’actions']],
['7.1','resources','Moyens disponibles','Justifier les ressources nécessaires au système.',['Budget','Plan de maintenance']],
['7.2','skills','Compétences','Démontrer les compétences nécessaires et l’efficacité des formations.',['Matrice de compétences','Habilitations','Plan de formation']],
['7.3','awareness','Sensibilisation des équipes','S’assurer que chacun comprend sa contribution.',['Accueil QSSE','Supports de sensibilisation']],
['7.4','communication','Communication','Organiser les échanges internes et externes pertinents.',['Plan de communication']],
['7.5','documents','Maîtrise documentaire','Maîtriser la création, l’accès, l’utilisation et la conservation des informations.',['Procédure GED','Liste des documents applicables']],
['8.1','operations','Maîtrise opérationnelle','Organiser et maîtriser les activités, y compris les prestations externes pertinentes.',['Modes opératoires','Plans de contrôle','Plan de prévention']],
['9.1','monitoring','Mesure des performances','Suivre les résultats du système et évaluer les performances.',['Tableau de bord QSSE']],
['9.2','audits','Audits internes','Planifier les audits, restituer les constats et suivre les suites données.',['Programme d’audit','Rapport audit Qualité','Rapport audit Environnement','Rapport audit SST']],
['9.3','review','Revue de direction','Faire le bilan du système et tracer les décisions prises.',['Compte rendu de revue de direction']],
['10.2','corrective','Écarts et actions correctives','Traiter les écarts, rechercher les causes et vérifier les résultats.',['Fiche de non-conformité','5 Pourquoi','Ishikawa']],
];
const specific:Record<string,Theme[]>={Q:[['6.3','changes','Changements planifiés','Préparer les évolutions du système.',['Fiche de changement']],['8.2','customer','Besoins clients','Préciser les engagements et les échanges avec les clients.',['Revue de contrat','Cahier des charges']],['8.3','design','Conception','Maîtriser les études et développements.',['Dossier de conception']],['8.4','suppliers','Fournisseurs et sous-traitants','Évaluer et suivre les prestations externes.',['Évaluation fournisseurs']],['8.5','production','Production et prestation','Maîtriser la réalisation, la traçabilité et les changements.',['Dossier de lot','Instructions de fabrication']],['8.6','release','Libération','Tracer les contrôles avant mise à disposition.',['Certificat de conformité']],['8.7','nonconforming-output','Produits non conformes','Identifier les produits ou prestations non conformes et leur traitement.',['Fiche de blocage']],['10.1','improvement','Progrès continus','Améliorer les résultats du système.',['Plan de progrès']]],E:[['6.3','changes','Changements planifiés','Préparer les changements ayant des effets sur le système environnemental.',['Fiche de changement']],['8.2','emergency','Situations d’urgence','Préparer les réponses et tester leur efficacité.',['Plan d’urgence','Exercices']],['10.1','improvement','Progrès continus','Améliorer les résultats du système.',['Plan de progrès']]],S:[['5.4','participation','Participation des travailleurs','Organiser leur consultation et leur participation.',['Compte rendu CSE','Remontées terrain']],['8.2','emergency','Situations d’urgence','Préparer les secours et tester les dispositifs.',['Plan d’urgence','Exercices']],['10.1','improvement-general','Opportunités de progrès','Définir les améliorations nécessaires.',['Programme de prévention']],['10.3','improvement','Progrès continus','Améliorer les résultats du système SST.',['Plan de progrès']]]};
export const requirementSeed:Requirement[]=standardSeed.flatMap(s=>[...common,...specific[s.badge]].map(([code,topic,title,guidance,examples])=>({id:s.id+':'+code,standard_id:s.id,chapter:Number(code.split('.')[0]),code,title,topic,guidance:guidance+(topic==='risks'?(s.badge==='E'?' Inclure les aspects environnementaux, obligations de conformité et plans associés (§6.1.2 à 6.1.5).':s.badge==='S'?' Inclure dangers, évaluation SST et exigences légales (§6.1.2 à 6.1.4).':' Distinguer le traitement des risques et des opportunités (§6.1.2 et §6.1.3).'):topic==='operations'&&s.badge==='S'?' Inclure prévention, changements, achats, entreprises extérieures et externalisation (§8.1.1 à §8.1.4).':''),examples:topic==='risks'?[...examples,...(s.badge==='S'?['DUERP']:s.badge==='E'?['Analyse environnementale']:[])]:examples,active:true,revision:1})));
export function suggestions(title:string,requirements:Requirement[]){const t=title.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();let topics:string[]=[],badges=['Q','E','S'];if(/\bduerp\b/.test(t)){topics=['risks'];badges=['S']}else if(/analyse environnementale/.test(t)){topics=['risks'];badges=['E']}else if(/risques et opportunit/.test(t))topics=['risks'];else if(/documents applicables|gestion documentaire|procedure ged/.test(t))topics=['documents'];else if(/formation|competence|habilitation/.test(t)){topics=['skills'];if(/habilitation/.test(t))badges=['S']}else if(/audit/.test(t)){topics=['audits'];if(/environnement/.test(t)&&!/securite/.test(t))badges=['E'];else if(/securite|sst/.test(t)&&!/environnement/.test(t))badges=['S'];else if(/qualite/.test(t)&&!/qsse/.test(t))badges=['Q']}else if(/non.conform|ishikawa|5 pourquoi/.test(t)){topics=['corrective'];if(/fournisseur|client/.test(t))badges=['Q']}else if(/parties interessees/.test(t))topics=['stakeholders'];else if(/contexte|\bswot\b|\bpestel\b/.test(t))topics=['context'];return requirements.filter(r=>topics.includes(r.topic)&&badges.includes(standardSeed.find(s=>s.id===r.standard_id)?.badge||'')).map(r=>r.id)}
