import type {GedDocument} from './ged';
export type Standard={id:string;badge:string;name:string;edition:string;color:string;source:string;active:boolean;revision?:number};
export type Requirement={id:string;standard_id:string;chapter:number;code:string;title:string;topic:string;guidance:string;examples:string[];active:boolean;revision:number};
export type SmiLink={document_id:string;requirement_id:string;confirmed:number;note:string;revision:number;updated_at:string};
export type SmiDocument=GedDocument&{status:'Validé'|'En révision'|'À créer'|'Obsolète / Archivé';statusReason:string;authorId:string;reviewerId:string;approverId:string;nextReview:string;teamId:string;norms:string[];canEdit:boolean;latestVersionId:string};
export type SmiPayload={standards:Standard[];requirements:Requirement[];documents:SmiDocument[];links:SmiLink[];removedLinks?:SmiLink[];manage:boolean;editableTeams:string[];teams:{id:string;name:string}[];users:any[];updatedAt:string};
export type SmiFilters={search:string;chapter:string;standard:string;status:string;team:string;type:string};
export const chapters:Record<number,string>={4:'Contexte de l’organisme',5:'Leadership',6:'Planification',7:'Support',8:'Réalisation des activités opérationnelles',9:'Évaluation des performances',10:'Amélioration'};
export const smiStatuses=['Validé','En révision','À créer','Obsolète / Archivé'] as const;
export const emptyFilters:SmiFilters={search:'',chapter:'',standard:'',status:'',team:'',type:''};
export const fold=(s:string)=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase('fr').trim();
export function documentNorms(id:string,links:SmiLink[],requirements:Requirement[]){const rs=new Map(requirements.filter(r=>r.active).map(r=>[r.id,r]));return [...new Set(links.filter(l=>l.document_id===id).map(l=>rs.get(l.requirement_id)?.standard_id).filter(Boolean))] as string[]}
export function coverage(rid:string,links:SmiLink[],docs:SmiDocument[]){const rows=links.filter(l=>l.requirement_id===rid),map=new Map(docs.map(d=>[d.id,d])),visible=rows.filter(l=>map.has(l.document_id));if(!visible.length)return 0;const score=visible.reduce((s,l)=>s+(!l.confirmed?0:map.get(l.document_id)?.status==='Validé'?1:map.get(l.document_id)?.status==='En révision'?.5:0),0);return Math.floor(100*score/visible.length)}
export const coverageLabel=(n:number)=>n===100?'Couverture complète':n>0?'Couverture partielle':'Non couvert';
export function smiView(data:SmiPayload,f:SmiFilters){const normIds=(ids:string[])=>!f.standard||f.standard==='C'?(!f.standard||ids.length>1):ids.includes(f.standard);const docs=data.documents.filter(d=>(!f.status||d.status===f.status)&&(!f.team||d.teamId===f.team)&&(!f.type||d.type===f.type));const map=new Map(docs.map(d=>[d.id,d]));const q=fold(f.search);const groups=new Map<string,Requirement[]>();for(const r of data.requirements.filter(r=>r.active&&data.standards.some(s=>s.id===r.standard_id&&s.active)&&(!f.chapter||r.chapter===Number(f.chapter)))){const g=groups.get(r.topic)||[];g.push(r);groups.set(r.topic,g)}return [...groups.entries()].flatMap(([topic,all])=>{if(!normIds([...new Set(all.map(r=>r.standard_id))]))return [];const requirements=f.standard&&f.standard!=='C'?all.filter(r=>r.standard_id===f.standard):all;const ids=new Set(requirements.map(r=>r.id));const ls=data.links.filter(l=>ids.has(l.requirement_id)&&map.has(l.document_id));const unique=[...new Set(ls.map(l=>l.document_id))].map(id=>map.get(id)!);const matchesRequirement=!q||fold(requirements.map(r=>[r.code,r.title,r.guidance,chapters[r.chapter],data.standards.find(s=>s.id===r.standard_id)?.name,data.standards.find(s=>s.id===r.standard_id)?.edition].join(' ')).join(' ')).includes(q);const shown=unique.filter(d=>normIds(d.norms)&&(!q||matchesRequirement||fold([d.title,d.ref,d.index,data.teams.find(t=>t.id===d.teamId)?.name,d.type].join(' ')).includes(q)));if((f.status||f.team||f.type)&&!shown.length||q&&!matchesRequirement&&!shown.length)return [];return [{topic,requirements,documents:shown,chapter:all[0].chapter,title:all[0].title,percent:Math.floor(requirements.reduce((s,r)=>s+coverage(r.id,data.links,data.documents),0)/requirements.length)}]})}
export function exportMatrix(data:SmiPayload,f:SmiFilters){const rows:(string|number)[][]=[['Chapitre','Exigence','Norme','Document','Référence','Version','Statut','Pilote','Couverture (%)','Rattachement','Prochaine révision','Lien GED']];for(const group of smiView(data,f)){for(const r of group.requirements){const docs=group.documents.filter(d=>data.links.some(l=>l.document_id===d.id&&l.requirement_id===r.id));for(const d of docs.length?docs:[null]){const l=d?data.links.find(l=>l.document_id===d.id&&l.requirement_id===r.id):null;rows.push([`${r.chapter} · ${chapters[r.chapter]}`,`${r.code} · ${r.title}`,data.standards.find(s=>s.id===r.standard_id)?.name+' '+(data.standards.find(s=>s.id===r.standard_id)?.edition||''),d?.title||'Aucune preuve associée',d?.ref||'',d?.index||'',d?.status||'À créer',data.teams.find(t=>t.id===d?.teamId)?.name||'',coverage(r.id,data.links,data.documents),l?.confirmed?'Confirmé':l?'À confirmer':'',d?.nextReview||'',d?'/ged?document='+encodeURIComponent(d.id):''])}}}return rows}
