export const widgetLabels={risks:'Répartition des risques',priorities:'Risques prioritaires',actions:'Suivi des actions',program:'PAPRIPACT annuel',team:'Métiers de l’unité',note:'Point d’équipe',indicator:'Indicateur personnalisé',links:'Liens et documents',checklist:'Liste de contrôle',table:'Tableau libre',chart:'Graphique en barres',heading:'Titre de section'} as const;
export type Widget={id:string;type:keyof typeof widgetLabels;wide:boolean;title:string;text:string;value:string;target:string;unit:string;date:string;span?:number;minHeight?:number;background?:string;accent?:string;align?:'left'|'center'|'right';fontSize?:number;hideTitle?:boolean;limit?:number;items?:{label:string;url?:string;done?:boolean}[];rows?:string[][]};
export type Board={title:string;widgets:Widget[];columns?:number;background?:string;gap?:number};
export function newWidget(type:Widget['type'],id=crypto.randomUUID()):Widget{return {id,type,wide:type==='actions',title:widgetLabels[type],text:'',value:'',target:'',unit:'',date:'',items:[],rows:[]}}
export function defaultBoard():Board{return {title:'Pilotage de l’unité',widgets:['risks','priorities','actions','program','note','team'].map((t,i)=>newWidget(t as Widget['type'],'default-'+i))}}
export function boardError(b:unknown):string{const v=b as Board;if(!v||typeof v.title!=='string'||!v.title.trim()||v.title.length>100||!Array.isArray(v.widgets)||v.widgets.length>60)return 'Titre requis (100 caractères maximum), 60 blocs maximum.';const visual=visualError(v,true);if(visual)return visual;const ids=new Set();for(const w of v.widgets){if(!w||typeof w.id!=='string'||!/^[a-zA-Z0-9-]{1,60}$/.test(w.id)||ids.has(w.id)||!Object.hasOwn(widgetLabels,w.type)||typeof w.wide!=='boolean')return 'Bloc invalide ou dupliqué.';ids.add(w.id);const visual=visualError(w);if(visual)return visual;if(w.items!==undefined&&(!Array.isArray(w.items)||w.items.length>50||w.items.some(i=>!i||typeof i.label!=='string'||!i.label.trim()||i.label.length>300||(i.url!==undefined&&(typeof i.url!=='string'||i.url.length>2000||!safeLink(i.url)))||(i.done!==undefined&&typeof i.done!=='boolean'))))return 'Liste invalide : 50 éléments maximum, liens HTTP(S) uniquement.';if(w.rows!==undefined&&(!Array.isArray(w.rows)||w.rows.length>51||w.rows.some(r=>!Array.isArray(r)||r.length>8||r.some(c=>typeof c!=='string'||c.length>300))))return 'Tableau invalide : 50 lignes de données et 8 colonnes maximum.';if(w.type==='chart'&&w.rows?.some(r=>r.length!==2||!r[0].trim()||!r[1]?.trim()||!Number.isFinite(Number(r[1].replace(',','.')))))return 'Chaque barre nécessite un libellé et une valeur numérique.';for(const k of ['title','text','value','target','unit','date'] as const)if(typeof w[k]!=='string'||w[k].length>(k==='text'?4000:120))return 'Contenu trop long ou invalide.';if(!w.title.trim())return 'Chaque bloc doit avoir un titre.';if(w.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(w.date)||Number.isNaN(Date.parse(w.date))||new Date(w.date).toISOString().slice(0,10)!==w.date))return 'Date invalide.'}return ''}
export function parisToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function actionSummary(actions:any[],today:string,year:number){const open=actions.filter(a=>a.status!=='Clôturée'),annual=actions.filter(a=>Number(a.programYear||a.due?.slice(0,4)||a.registered?.slice(0,4)||year)===year);return {open:open.length,late:open.filter(a=>a.due&&a.due<today).length,undated:open.filter(a=>!a.due).length,verify:open.filter(a=>a.status==='À vérifier').length,total:annual.length,closed:annual.filter(a=>a.status==='Clôturée').length}}

export function safeLink(value:string){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password}catch{return false}}
export function visualError(v:any,board=false):string{const ranges=board?{columns:[1,4],gap:[8,40]}:{span:[1,4],minHeight:[80,1000],fontSize:[14,32],limit:[1,50]};for(const [k,[min,max]] of Object.entries(ranges))if(v[k]!==undefined&&(!Number.isInteger(v[k])||v[k]<min||v[k]>max))return 'Dimension ou nombre d’éléments invalide.';for(const k of board?['background']:['background','accent'])if(v[k]!==undefined&&(typeof v[k]!=='string'||!/^#[0-9a-f]{6}$/i.test(v[k])))return 'Couleur invalide.';if(v.align!==undefined&&!['left','center','right'].includes(v.align))return 'Alignement invalide.';if(v.hideTitle!==undefined&&typeof v.hideTitle!=='boolean')return 'Affichage du titre invalide.';return ''}
export function readableInk(hex:string){if(!/^#[0-9a-f]{6}$/i.test(hex))return '#17314f';const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.179?'#111827':'#ffffff'}
export function duplicateWidget(w:Widget):Widget{return {...structuredClone(w),id:crypto.randomUUID(),title:(w.title+' · copie').slice(0,120)}}
export function reorderWidgets(widgets:Widget[],source:string,target:string){const from=widgets.findIndex(w=>w.id===source),to=widgets.findIndex(w=>w.id===target);if(from<0||to<0||from===to)return widgets;const result=[...widgets], [item]=result.splice(from,1);result.splice(to,0,item);return result}
