export type WasteRecord={id:string;revision:number;date:string;dateSource:string;status:'Prévu'|'Enlevé';type:string;family:string;code:string;danger:'Oui'|'Non'|'À vérifier';quantity:number|null;estimate:number|null;unit:'t'|'kg'|'unité'|'à vérifier';excluded:boolean;client:boolean;collector:string;destination:string;treatment:string;bsd:string;owner:string;notes:string;documentUrl:string;sourceRow:number;issues:string[];raw?:Record<string,string>;updatedAt?:string;updatedBy?:string};
export const wasteTreatments=['La préparation en vue de la réutilisation','Le recyclage matière','Toute autre valorisation, notamment la valorisation énergétique',"L’élimination"];
export const wasteFamilies=['DIB','Déchets dangereux','Plastiques','Cartons','Papier','Palettes','Bois','Ferraille','Purges','Terre et granulés','4 flux','Big-bags','Déchets ménagers','Déchets clients','Retraits salariés','Intervenants extérieurs','Déchetterie','Autres'];
export const fold=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function validDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(value+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===value}
export function wasteIssues(r:WasteRecord){const issues:string[]=[];if(!validDate(r.date))issues.push('Date absente ou à corriger');if(r.unit==='à vérifier')issues.push('Unité de la quantité à confirmer');if(r.status==='Enlevé'&&r.quantity===null)issues.push('Quantité réelle non renseignée');if(r.danger==='À vérifier')issues.push('Dangerosité non renseignée');if(r.code.includes('*')&&r.danger==='Non')issues.push('Code étoilé et dangerosité NON');if(r.danger==='Oui'&&!r.bsd.trim())issues.push('Référence BSD à renseigner');if(!r.collector.trim())issues.push('Collecteur à renseigner');if(r.status==='Enlevé'&&!r.destination.trim())issues.push('Destination à renseigner');return issues}
export function tonnes(r:WasteRecord):number|null {if(r.status!=='Enlevé'||!validDate(r.date)||r.quantity===null||!Number.isFinite(r.quantity)||r.quantity<0||!['t','kg'].includes(r.unit))return null;return r.quantity/(r.unit==='kg'?1000:1)}
export function wasteMetrics(records:WasteRecord[]){const masses=records.flatMap(r=>{const mass=tonnes(r);return mass===null?[]:[{r,mass}]});const total=masses.reduce((a,x)=>a+x.mass,0),material=masses.filter(x=>x.r.treatment==='Le recyclage matière').reduce((a,x)=>a+x.mass,0);return {total,material,materialRate:total?material/total*100:null,dangerous:masses.filter(x=>x.r.danger==='Oui').reduce((a,x)=>a+x.mass,0),weighed:masses.length,planned:records.filter(r=>r.status==='Prévu').length,review:records.filter(r=>wasteIssues(r).length).length,pallets:records.filter(r=>r.status==='Enlevé'&&validDate(r.date)&&r.unit==='unité'&&r.family==='Palettes').reduce((a,r)=>a+(r.quantity??0),0)}}
export function wastePoints(records:WasteRecord[],by:'month'|'family'|'treatment'){const groups=new Map<string,number>();for(const r of records){const mass=tonnes(r);if(mass===null)continue;const key=by==='month'?r.date.slice(0,7):by==='family'?r.family:r.treatment||'Non renseigné';groups.set(key,(groups.get(key)||0)+mass)}return [...groups].sort((a,b)=>by==='month'?a[0].localeCompare(b[0]):b[1]-a[1]).map(([label,value])=>({label,value}))}
export function blankWaste():WasteRecord{return {id:'',revision:0,date:'',dateSource:'',status:'Prévu',type:'',family:'DIB',code:'',danger:'À vérifier',quantity:null,estimate:null,unit:'t',excluded:false,client:false,collector:'',destination:'',treatment:'',bsd:'',owner:'',notes:'',documentUrl:'',sourceRow:0,issues:[]}}
export function validateWaste(r:WasteRecord){const errors:string[]=[];if(!r.type.trim())errors.push('Renseignez le type de déchet.');if(r.date&&!validDate(r.date))errors.push('La date est invalide.');for(const key of ['quantity','estimate'] as const)if(r[key]!==null&&(typeof r[key]!=='number'||!Number.isFinite(r[key])||r[key]!<0||r[key]!>1000000))errors.push('La quantité doit être un nombre positif ou zéro.');if(!['Prévu','Enlevé'].includes(r.status)||!['t','kg','unité','à vérifier'].includes(r.unit)||!['Oui','Non','À vérifier'].includes(r.danger))errors.push('Valeur de sélection invalide.');if(r.documentUrl&&!/^https?:\/\//i.test(r.documentUrl))errors.push('Le lien du document doit commencer par https:// ou http://.');return errors}
