import { modules, type Field } from './modules';
export type QRecord={id?:string;title:string;kind:string;domain:string;status:string;priority:string;owner:string;due:string;description:string;url:string;details:Record<string,string>;created?:string;updated?:string;revision?:number;sourceId?:string};
type Workflow={noun:string;states:string[];closed:string[];dueLabel:string;columns:string[];required:string[];fields:Field[];tip?:string};
const f=(key:string,label:string,type?:string,options?:string[]):Field=>({key,label,type,options});
const extras:Record<string,Field[]>={
Action:[f('measure','Action à réaliser'),f('result','Résultat / preuve de réalisation'),f('verifiedBy','Vérifié par'),f('verifiedDate','Date de vérification','date'),f('effectiveness','Résultat de la vérification d’efficacité')],
Audit:[f('scope','Périmètre / atelier'),f('reference','Référentiel / critères'),f('date','Date de réalisation','date'),f('auditor','Auditeur'),f('finding','Constats et écarts'),f('conclusion','Conclusion')],
'DUERP':[f('evaluated','Date de l’évaluation','date')],
'Analyse environnementale':[f('situation','Situation de fonctionnement',undefined,['Normale','Dégradée','Urgence']),f('evaluated','Date de l’évaluation','date')],
'Gestion des déchets':[f('destination','Installation de destination')],
'Plans de prévention':[f('contact','Contact de l’entreprise extérieure'),f('validator','Validation interne par')],
'Gestion documentaire':[f('approver','Approbateur'),f('approved','Date d’approbation','date')],
'RSE':[f('period','Période de suivi'),f('measured','Date de mesure','date')],
'Accidents du travail':[f('analysis','Analyse des causes'),f('externalReference','Référence de la déclaration externe (si effectuée)')]
};
function fields(kind:string){const base=modules[kind]?.fields||[];const removed=kind==='Gestion documentaire'?['validation','review']:kind==='Plans de prévention'?['validation']:kind==='Réglementation'?['compliance']:kind==='EPI'?['check']:[];return [...base.filter(f=>!removed.includes(f.key)),...(extras[kind]||[]).filter(f=>!base.some(b=>b.key===f.key))];}
function w(kind:string,noun:string,states:string[],closed:string[],dueLabel:string,columns:string[],required:string[],tip?:string):Workflow{return {noun,states,closed,dueLabel,columns,required,fields:fields(kind),tip};}
export const flows:Record<string,Workflow>={
Action:w('Action','action',['À faire','En cours','À vérifier','Clôturée'],['Clôturée'],'Échéance de réalisation',['measure','result'],['measure']),
Audit:w('Audit','audit',['À planifier','Planifié','Réalisé','Clôturé'],['Clôturé'],'Date prévue de l’audit',['scope','auditor'],['scope','reference']),
'Gestion des déchets':w('Gestion des déchets','mouvement de déchets',['Prévu','Enlevé','Traçabilité à compléter','Dossier complet'],['Dossier complet'],'Prochain suivi',['quantity','code','collector'],['code','collector'],'Un mouvement correspond à un enlèvement. Les quantités sont enregistrées en kilogrammes.'),
'Analyse environnementale':w('Analyse environnementale','aspect environnemental',['À évaluer','Évalué','À réviser'],[],'Prochaine révision',['activity','aspect','impact'],['activity','aspect','impact']),
RSE:w('RSE','objectif RSE',['À définir','En cours','Atteint','Non atteint'],['Atteint','Non atteint'],'Date cible',['indicator','target','actual'],['goal','indicator','period']),
'Accidents du travail':w('Accidents du travail','accident du travail',['Signalé','En analyse','Actions en cours','Clôturé'],['Clôturé'],'Prochain suivi interne',['date','place','person'],['date','place','circumstances'],'Ce registre assure le suivi interne. Il ne transmet aucune déclaration officielle.'),
'Situations dangereuses':w('Situations dangereuses','situation dangereuse',['Signalée','Mise en sécurité','Actions en cours','Clôturée'],['Clôturée'],'Échéance de traitement',['date','place','danger'],['date','place','danger']),
DUERP:w('DUERP','risque professionnel',['À évaluer','Évalué','À réviser'],[],'Prochaine révision',['unit','danger','score'],['unit','activity','danger'],'Chaque fiche correspond à un risque d’une unité de travail. La cotation indicative doit être adaptée à la méthode validée par Polytechs.'),
EPI:w('EPI','dotation EPI',['À remettre','En service','À remplacer','Retiré'],['Retiré'],'Prochain contrôle / renouvellement',['equipment','assignee','quantity'],['equipment','assignee','quantity'],'Une fiche correspond à une dotation individuelle ou à un service ; elle ne représente pas le stock magasin.'),
'Plans de prévention':w('Plans de prévention','plan de prévention',['À préparer','À valider','Validé','Clôturé'],['Clôturé'],'Prochaine revue du plan',['contractor','start','end'],['contractor','operation','place','start','end'],'La validation ici est un suivi interne, sans signature électronique. Joignez le lien du plan validé.'),
'Gestion documentaire':w('Gestion documentaire','document',['Brouillon','À valider','Approuvé','Obsolète'],['Obsolète'],'Prochaine révision',['reference','version','category'],['reference','version','category'],'Une fiche suit un document et sa version courante. Le fichier est accessible par un lien interne ; les anciennes fiches restent consultables dans l’historique.'),
Réglementation:w('Réglementation','exigence',['À évaluer','Conforme','Non conforme','Non applicable'],['Non applicable'],'Prochaine vérification',['reference','requirement','checked'],['reference','scope','requirement'],'Registre manuel : renseignez une source officielle, votre évaluation et les preuves associées.'),
'Amélioration continue':w('Amélioration continue','constat d’amélioration',['À analyser','En traitement','À vérifier','Clôturé'],['Clôturé'],'Prochain suivi',['origin','finding','cause'],['origin','finding'],'Le constat est enregistré ici ; ses actions sont créées et suivies dans le plan d’actions commun.')
};
export const blank:QRecord={title:'',kind:'Action',domain:'Sécurité',status:'À faire',priority:'Normale',owner:'',due:'',description:'',url:'',details:{},sourceId:''};
export function normalize(raw:any):QRecord{const details=typeof raw.details==='string'?JSON.parse(raw.details||'{}'):{...(raw.details||{})};for(const key of Object.keys(details))if(details[key]==='Non renseigné')details[key]='';let kind=raw.kind;if(kind==='Incident')kind='Situations dangereuses';if(kind==='Document')kind='Gestion documentaire';const flow=flows[kind];let status=raw.status;if(flow&&!flow.states.includes(status)){const old=status==='Terminé'?2:status==='En cours'?1:0;const maps:Record<string,string[]>={'Gestion documentaire':['Brouillon','À valider','Approuvé'],'Plans de prévention':['À préparer','À valider','Validé'],Réglementation:['À évaluer','À évaluer','Conforme'],EPI:['À remettre','En service','Retiré'],DUERP:['À évaluer','À réviser','Évalué'],'Analyse environnementale':['À évaluer','À réviser','Évalué'],Action:['À faire','En cours','Clôturée']};status=(maps[kind]||[flow.states[0],flow.states[1],flow.states.at(-1)!])[old];if(kind==='Gestion documentaire'&&flow.states.includes(details.validation))status=details.validation;if(kind==='Réglementation'&&flow.states.includes(details.compliance))status=details.compliance;}
return {...blank,...raw,kind,status,details,sourceId:raw.sourceId||raw.source_id||'',due:raw.due||details.review||details.check||'',revision:raw.revision||1};}
export function closed(r:QRecord){return flows[r.kind]?.closed.includes(r.status)||false;}
export function score(r:QRecord){const g=Number(r.details.severity),f=Number(r.details.frequency);return g>=1&&g<=5&&f>=1&&f<=5?g*f:null;}
export function dateToday(){const p=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Paris'}).format(new Date());return p;}
export function dateValid(s:string){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;}
export function fieldLabel(kind:string,key:string){return key==='score'?'Cotation indicative':flows[kind]?.fields.find(f=>f.key===key)?.label||key;}
export function dueEvents(r:QRecord){if(closed(r))return [];const events:{record:QRecord;date:string;label:string}[]=[];if(r.due&&!(r.kind==='Audit'&&r.status==='Réalisé'))events.push({record:r,date:r.due,label:flows[r.kind]?.dueLabel||'Échéance'});if(r.kind==='Plans de prévention'&&r.details.end&&r.details.end!==r.due)events.push({record:r,date:r.details.end,label:'Fin d’intervention'});return events;}
export function validate(r:QRecord,all:QRecord[]=[]):string[]{const errors:string[]=[];const flow=flows[r.kind];if(!flow)return ['Module inconnu.'];if(!r.title.trim())errors.push('Renseignez un intitulé.');if(!flow.states.includes(r.status))errors.push('Le statut est incompatible avec ce module.');if(modules[r.kind]&&r.domain!==modules[r.kind].domain&& !['Réglementation','Gestion documentaire','Amélioration continue'].includes(r.kind))errors.push('Le domaine est incompatible avec ce module.');
if(r.due&&!dateValid(r.due))errors.push('Échéance invalide.');if(r.url){try{if(!['http:','https:'].includes(new URL(r.url).protocol))errors.push('Le lien doit utiliser HTTPS ou HTTP.');}catch{errors.push('Le lien du document est invalide.');}}
for(const f of flow.fields){const v=r.details[f.key]||'';if(v&&f.type==='date'&&!dateValid(v))errors.push(`${f.label} : date invalide.`);if(v&&f.type==='number'&&(!Number.isFinite(Number(v))||Number(v)<0))errors.push(`${f.label} : indiquez un nombre positif ou nul.`);if(v&&f.options&&!f.options.includes(v))errors.push(`${f.label} : valeur invalide.`);}
const required=[...flow.required];const need=(key:string,label?:string)=>{if(!r.details[key]?.trim())errors.push(`Renseignez ${label||fieldLabel(r.kind,key)}.`);};required.forEach(k=>need(k));
if(r.status!==flow.states[0]&&!r.owner.trim())errors.push('Attribuez un responsable avant de faire avancer la fiche.');
if(r.kind==='Action'){if(['En cours','À vérifier','Clôturée'].includes(r.status)&&!r.due)errors.push('Une action engagée doit avoir une échéance.');if(['À vérifier','Clôturée'].includes(r.status))need('result');if(r.status==='Clôturée'){['verifiedBy','verifiedDate','effectiveness'].forEach(k=>need(k));}}
if(['DUERP','Analyse environnementale'].includes(r.kind)&&r.status==='Évalué'){['severity','frequency','controls','evaluated'].forEach(k=>need(k));if(!r.due)errors.push('Planifiez la prochaine révision.');}
if(r.kind==='Gestion des déchets'&&r.status!=='Prévu'){['quantity','date','treatment','destination'].forEach(k=>need(k));if(r.status==='Dossier complet'&&r.details.dangerous==='Oui')need('bsd');}
if(['Accidents du travail','Situations dangereuses'].includes(r.kind)&&closed(r)){need('immediate');if(r.kind==='Accidents du travail')need('analysis');}
if(r.kind==='Plans de prévention'){if(r.details.start&&r.details.end&&r.details.end<r.details.start)errors.push('La fin d’intervention précède le début.');if(['Validé','Clôturé'].includes(r.status)){need('inspection');need('risks');need('measures');need('validator');if(!r.url)errors.push('Ajoutez le lien du plan validé.');if(r.details.inspection>r.details.start)errors.push('L’inspection doit précéder ou coïncider avec le début.');}}
if(r.kind==='Gestion documentaire'&&r.status==='Approuvé'){need('approver');need('approved');if(!r.url)errors.push('Ajoutez le lien du document approuvé.');if(!r.due)errors.push('Planifiez la prochaine révision du document.');}
if(r.kind==='Réglementation'&&r.status!=='À évaluer'){need('checked');need('proof');if(!r.url)errors.push('Ajoutez le lien vers la source réglementaire.');}
if(r.kind==='EPI'&&r.status==='En service'){need('date');if(Number(r.details.quantity)<=0)errors.push('Une dotation en service doit avoir une quantité supérieure à zéro.');}
if(r.kind==='Audit'&&['Réalisé','Clôturé'].includes(r.status)){need('date');need('auditor');need('finding');if(closed(r))need('conclusion');}
if(r.kind==='RSE'&&closed(r)){need('target');need('actual');need('measured');}
if(r.kind==='Amélioration continue'&&closed(r)){need('cause');need('effectiveness');}
const factualDates=['verifiedDate','evaluated','approved','checked','measured'];if(['Accidents du travail','Situations dangereuses'].includes(r.kind))factualDates.push('date');for(const k of factualDates)if(r.details[k]&&r.details[k]>dateToday())errors.push(`${fieldLabel(r.kind,k)} ne peut pas être dans le futur.`);
if(r.kind==='Audit'&&r.status==='Planifié'&&!r.due)errors.push('Un audit planifié doit avoir une date prévue.');
if(r.sourceId){const source=all.find(x=>x.id===r.sourceId);if(source&&closed(source)&&!r.id)errors.push('Rouvrez la fiche d’origine avant de créer une action.');if(r.kind!=='Action'||!source||source.kind==='Action')errors.push('L’origine doit être une fiche existante autre qu’une action.');}
if(closed(r)&&r.kind!=='Action'&&all.some(x=>x.kind==='Action'&&x.sourceId===r.id&&!closed(x)))errors.push('Clôturez les actions liées avant de clôturer cette fiche.');
return [...new Set(errors)];}
