// Minimal Office Open XML writer: text cells stay strings (no formula execution).
const enc=new TextEncoder();
const xml=(s:unknown)=>String(s??'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').slice(0,32700).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const col=(n:number):string=>n<26?String.fromCharCode(65+n):col(Math.floor(n/26)-1)+col(n%26);
function crc(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function zip(files:[string,string][]){const parts:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;function header(size:number){const b=new Uint8Array(size);return {b,v:new DataView(b.buffer)}}for(const [name,value] of files){const n=enc.encode(name),data=enc.encode(value),sum=crc(data),h=header(30+n.length);h.v.setUint32(0,0x04034b50,true);h.v.setUint16(4,20,true);h.v.setUint32(14,sum,true);h.v.setUint32(18,data.length,true);h.v.setUint32(22,data.length,true);h.v.setUint16(26,n.length,true);h.b.set(n,30);parts.push(h.b,data);const c=header(46+n.length);c.v.setUint32(0,0x02014b50,true);c.v.setUint16(4,20,true);c.v.setUint16(6,20,true);c.v.setUint32(16,sum,true);c.v.setUint32(20,data.length,true);c.v.setUint32(24,data.length,true);c.v.setUint16(28,n.length,true);c.v.setUint32(42,offset,true);c.b.set(n,46);central.push(c.b);offset+=h.b.length+data.length}const size=central.reduce((s,b)=>s+b.length,0),end=header(22);end.v.setUint32(0,0x06054b50,true);end.v.setUint16(8,files.length,true);end.v.setUint16(10,files.length,true);end.v.setUint32(12,size,true);end.v.setUint32(16,offset,true);const result=new Uint8Array(offset+size+22);let pos=0;for(const b of [...parts,...central,end.b]){result.set(b,pos);pos+=b.length}return result}
export function workbook(sheets:{name:string;rows:(string|number)[][]}[]){const pre='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';return zip([
['[Content_Types].xml',pre+'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')+'</Types>'],
['_rels/.rels',pre+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
['xl/workbook.xml',pre+`<workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>`+sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')+'</sheets></workbook>'],
['xl/_rels/workbook.xml.rels',pre+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+`<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`],
['xl/styles.xml',pre+`<styleSheet xmlns="${ns}"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF005EAA"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf><xf fontId="1" fillId="2" borderId="0" xfId="0" applyFill="1" applyFont="1"><alignment wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`],
...sheets.map((s,i):[string,string]=>['xl/worksheets/sheet'+(i+1)+'.xml',pre+`<worksheet xmlns="${ns}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" state="frozen"/></sheetView></sheetViews><cols>`+(s.rows[0]||[]).map((_,j)=>`<col min="${j+1}" max="${j+1}" width="${j===1||j===3?42:24}" customWidth="1"/>`).join('')+'</cols><sheetData>'+s.rows.map((r,ri)=>`<row r="${ri+1}" ht="${ri?42:30}" customHeight="1">`+r.map((v,ci)=>typeof v==='number'&&Number.isFinite(v)?`<c r="${col(ci)}${ri+1}" s="${ri?0:1}"><v>${v}</v></c>`:`<c r="${col(ci)}${ri+1}" s="${ri?0:1}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')+'</row>').join('')+`</sheetData><autoFilter ref="A1:${col((s.rows[0]?.length||1)-1)}${Math.max(1,s.rows.length)}"/></worksheet>`])]);}
