import { database } from '@/db/raw';
import { normalize,validate } from '@/lib/workflows';
export async function GET(req:Request){try {const id=new URL(req.url).searchParams.get('history');if(id)return Response.json({history:(await database().prepare('SELECT revision,snapshot,saved_at FROM record_history WHERE record_id=? ORDER BY revision DESC').bind(id).all()).results});return Response.json({records:(await database().prepare('SELECT * FROM records ORDER BY created DESC').all()).results});}catch(e){console.error(e);return Response.json({error:'Chargement impossible. Réessayez dans un instant.'},{status:503});}}
export async function POST(req:Request){try{const b:any=await req.json();if(!b||typeof b!=='object'||Array.isArray(b))return Response.json({error:'Fiche invalide.'},{status:400});for(const key of ['title','kind','domain','status','priority','owner','due','description','url'])if(typeof b[key]!=='string'||b[key].length>5000)return Response.json({error:'Fiche invalide.'},{status:400});if(b.title.length>200||b.owner.length>150||!['Qualité','Sécurité','Environnement'].includes(b.domain)||!['Haute','Normale','Basse'].includes(b.priority))return Response.json({error:'Valeurs invalides.'},{status:400});for(const k of ['id','sourceId'])if(b[k]!==undefined&&(typeof b[k]!=='string'||b[k].length>100))return Response.json({error:'Référence invalide.'},{status:400});if(!b.details||typeof b.details!=='object'||Array.isArray(b.details)||Object.values(b.details).some(v=>typeof v!=='string'||v.length>5000)||JSON.stringify(b.details).length>30000)return Response.json({error:'Champs complémentaires invalides.'},{status:400});
const db=database(),all=(await db.prepare('SELECT * FROM records').all()).results.map(normalize),r=normalize(b);r.status=b.status;const errors=validate(r,all);if(errors.length)return Response.json({error:errors.join('\n')},{status:400});const now=new Date().toISOString(),id=b.id||crypto.randomUUID(),details=JSON.stringify(r.details);const previous=all.find(x=>x.id===b.id);
if(b.id){if(!previous)return Response.json({error:'Fiche introuvable.'},{status:404});if(previous.kind!==r.kind)return Response.json({error:'Le module d’une fiche existante ne peut pas être modifié.'},{status:400});if(b.revision!==previous.revision)return Response.json({error:'Cette fiche a été modifiée depuis son ouverture. Fermez-la puis rouvrez-la pour consulter la dernière version. Copiez votre saisie avant de fermer.'},{status:409});
const results=await db.batch([
db.prepare('INSERT INTO record_history (id,record_id,revision,snapshot,saved_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM records WHERE id=? AND revision=?)').bind(crypto.randomUUID(),id,previous.revision,JSON.stringify(previous),now,id,previous.revision),
db.prepare('UPDATE records SET title=?,domain=?,status=?,priority=?,owner=?,due=?,description=?,url=?,details=?,source_id=?,updated=?,revision=revision+1 WHERE id=? AND revision=?').bind(r.title.trim(),r.domain,r.status,r.priority,r.owner,r.due,r.description,r.url,details,r.sourceId||'',now,id,previous.revision)
]);if(!results[1].meta.changes)return Response.json({error:'Modification concurrente. Fermez et rouvrez la fiche avant de réessayer.'},{status:409});
}else await db.prepare('INSERT INTO records (id,title,kind,domain,status,priority,owner,due,description,url,details,created,updated,revision,source_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,r.title.trim(),r.kind,r.domain,r.status,r.priority,r.owner,r.due,r.description,r.url,details,now,now,1,r.sourceId||'').run();return Response.json({id});
}catch(e){console.error(e);return Response.json({error:'Enregistrement impossible. Votre saisie est conservée.'},{status:503});}}
