import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const records = sqliteTable('records', {id:text('id').primaryKey(),title:text('title').notNull(),kind:text('kind').notNull(),domain:text('domain').notNull(),status:text('status').notNull(),priority:text('priority').notNull(),owner:text('owner').notNull(),due:text('due').notNull(),description:text('description').notNull(),url:text('url').notNull(),details:text('details').notNull().default('{}'),created:text('created').notNull(),updated:text('updated').notNull().default(''),revision:integer('revision').notNull().default(1),sourceId:text('source_id').notNull().default('')});

export const history=sqliteTable('record_history',{id:text('id').primaryKey(),recordId:text('record_id').notNull(),revision:integer('revision').notNull(),snapshot:text('snapshot').notNull(),savedAt:text('saved_at').notNull()},t=>[index('idx_history_record').on(t.recordId)]);

export const users=sqliteTable('users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),displayName:text('display_name').notNull(),role:text('role').notNull(),passwordHash:text('password_hash').notNull(),mustChangePassword:integer('must_change_password').notNull().default(1),createdAt:text('created_at').notNull()});
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expiresAt:integer('expires_at').notNull()},t=>[index('idx_sessions_user').on(t.userId)]);
export const loginAttempts=sqliteTable('login_attempts',{username:text('username').primaryKey(),failures:integer('failures').notNull(),blockedUntil:integer('blocked_until').notNull()});

export const evrpUnits=sqliteTable('evrp_units',{code:text('code').primaryKey(),name:text('name').notNull(),roles:text('roles').notNull().default('[]'),sourceRef:text('source_ref').notNull().default(''),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull().default('')});
export const evrpRisks=sqliteTable('evrp_risks',{id:text('id').primaryKey(),unitCode:text('unit_code').notNull(),data:text('data').notNull(),original:text('original').notNull(),status:text('status').notNull().default('À vérifier'),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by').notNull().default('')},t=>[index('idx_evrp_risks_unit').on(t.unitCode)]);
export const evrpRiskHistory=sqliteTable('evrp_risk_history',{id:text('id').primaryKey(),riskId:text('risk_id').notNull(),revision:integer('revision').notNull(),snapshot:text('snapshot').notNull(),savedAt:text('saved_at').notNull(),savedBy:text('saved_by').notNull()},t=>[index('idx_evrp_history_risk').on(t.riskId)]);
export const evrpActions=sqliteTable('evrp_actions',{id:text('id').primaryKey(),unitCode:text('unit_code').notNull(),riskId:text('risk_id').notNull().default(''),data:text('data').notNull(),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by').notNull().default('')},t=>[index('idx_evrp_actions_unit').on(t.unitCode)]);
export const evrpActionHistory=sqliteTable('evrp_action_history',{id:text('id').primaryKey(),actionId:text('action_id').notNull(),revision:integer('revision').notNull(),snapshot:text('snapshot').notNull(),savedAt:text('saved_at').notNull(),savedBy:text('saved_by').notNull()},t=>[index('idx_evrp_action_history_action').on(t.actionId)]);
export const evrpRevisions=sqliteTable('evrp_revisions',{id:text('id').primaryKey(),date:text('date').notNull(),kind:text('kind').notNull(),description:text('description').notNull(),author:text('author').notNull().default(''),createdAt:text('created_at').notNull()});
export const unitDashboards=sqliteTable('unit_dashboards',{unitCode:text('unit_code').primaryKey().references(()=>evrpUnits.code),data:text('data').notNull(),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by').notNull()});
export const teams=sqliteTable('teams',{id:text('id').primaryKey(),name:text('name').notNull(),rank:integer('rank').notNull(),parentId:text('parent_id'),revision:integer('revision').notNull().default(1)});
export const teamDashboards=sqliteTable('team_dashboards',{id:text('id').primaryKey(),teamId:text('team_id').notNull().references(()=>teams.id),unitCode:text('unit_code').notNull().default(''),data:text('data').notNull(),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by').notNull()},t=>[index('idx_team_dashboards_team').on(t.teamId)]);
