import {teamsAllowed} from '@/lib/team-access';
import {database} from '@/db/raw';
import {checkOrigin,requireRole} from '@/lib/access';
import {epiCatalog as catalog} from '@/lib/epi-private-source';

const error=(message:string,status=400)=>Response.json({error:message},{status});
type Product={code:string;quantity:number|null;revision:number;catalog_status:string};
async function ensureCatalog(){const db=database();const row=await db.prepare('SELECT COUNT(*) AS total FROM epi_products').first<{total:number}>();if((row?.total??0)>=catalog.items.length)return;const statements=catalog.items.map(item=>db.prepare('INSERT OR IGNORE INTO epi_products (code,family,name,specifics,source_row,source_sheet,catalog_status,quantity,minimum,location,revision,updated_at) VALUES (?,?,?,?,?,?,?,NULL,NULL,?,1,?)').bind(item.code,item.family,item.name,item.specifics,item.sourceRow,item.sourceSheet,item.catalogStatus,'',new Date().toISOString()));for(let i=0;i<statements.length;i+=40)await db.batch(statements.slice(i,i+40))}

export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;if(!await teamsAllowed(gate.user!,['qsse']))return Response.json({error:'Accès QSSE nécessaire.'},{status:403});const params=new URL(req.url).searchParams,code=params.get('code');const db=database();if(code){const offset=Number(params.get('offset')||0);if(!/^[A-Za-z0-9*_-]{4,80}$/.test(code)||!Number.isSafeInteger(offset)||offset<0||offset>100000)return error('Historique invalide.');const movements=await db.prepare('SELECT * FROM epi_movements WHERE code=? ORDER BY created_at DESC,id DESC LIMIT 101 OFFSET ?').bind(code,offset).all();return Response.json({movements:movements.results.slice(0,100),hasMore:movements.results.length>100},{headers:{'Cache-Control':'no-store'}})}await ensureCatalog();const products=await db.prepare('SELECT * FROM epi_products ORDER BY family,name,code').all();return Response.json({products:products.results,source:catalog.source,sourceCount:catalog.items.length,duplicateRows:catalog.duplicateRows},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return error('Stock EPI indisponible.',503)}}

export async function POST(req:Request){try{if(!checkOrigin(req))return error('Requête non autorisée.',403);const gate=await requireRole(req,'editor');if(gate.error)return gate.error;if(!await teamsAllowed(gate.user!,['qsse'],true))return Response.json({error:'Droit de modification QSSE nécessaire.'},{status:403});const body=await req.json() as Record<string,unknown>;const db=database();if(body.action==='import'){if(gate.user!.role!=='admin')return error('Import réservé aux administrateurs.',403);await ensureCatalog();return Response.json({ok:true})}
const code=String(body.code||'');if(!/^[A-Za-z0-9*_-]{4,80}$/.test(code))return error('Référence invalide.');
if(body.action==='catalog'){if(gate.user!.role!=='admin')return error('Validation réservée aux administrateurs.',403);const status=String(body.status||''),revision=Number(body.revision);if(!['Actif','À confirmer','Inactif'].includes(status)||!Number.isSafeInteger(revision))return error('Statut invalide.');const result=await db.prepare('UPDATE epi_products SET catalog_status=?,revision=revision+1,updated_at=? WHERE code=? AND revision=?').bind(status,new Date().toISOString(),code,revision).run();if(!result.meta.changes)return error('Référence modifiée entre-temps. Rechargez.',409);return Response.json({ok:true})}
if(body.action==='settings'){const minimum=body.minimum===''||body.minimum===null?null:Number(body.minimum),location=String(body.location||'').trim(),revision=Number(body.revision);if(minimum!==null&&(!Number.isSafeInteger(minimum)||minimum<0||minimum>1000000)||location.length>150||!Number.isSafeInteger(revision))return error('Paramètres invalides.');const result=await db.prepare('UPDATE epi_products SET minimum=?,location=?,revision=revision+1,updated_at=? WHERE code=? AND revision=?').bind(minimum,location,new Date().toISOString(),code,revision).run();if(!result.meta.changes)return error('Référence modifiée entre-temps. Rechargez.',409);return Response.json({ok:true})}
const kind=String(body.kind||''),amount=Number(body.amount),recipient=String(body.recipient||'').trim(),note=String(body.note||'').trim();if(body.amount===null||body.amount===undefined||body.amount===''||!['inventaire','entree','sortie'].includes(kind)||!Number.isSafeInteger(amount)||amount<0||amount>1000000||recipient.length>150||note.length>1000)return error('Mouvement invalide.');if(kind!=='inventaire'&&amount===0)return error('Indiquez une quantité positive.');if(kind==='sortie'&&!recipient)return error('Indiquez le bénéficiaire ou le service.');const product=await db.prepare('SELECT code,quantity,revision,catalog_status FROM epi_products WHERE code=?').bind(code).first<Product>();if(!product)return error('Référence inconnue.',404);if(product.catalog_status==='Inactif'&&kind==='entree')return error('Une référence inactive ne peut plus être réapprovisionnée.');if(product.quantity===null&&kind!=='inventaire')return error('Faites le premier inventaire avant une entrée ou une sortie.');const before=product.quantity??0,after=kind==='inventaire'?amount:before+(kind==='entree'?amount:-amount);if(after<0)return error('Sortie supérieure au stock disponible.');if(after>1000000)return error('Le solde dépasse la limite de suivi.');const delta=after-before,now=new Date().toISOString();const result=await db.batch([db.prepare('UPDATE epi_products SET quantity=?,revision=revision+1,updated_at=? WHERE code=? AND revision=?').bind(after,now,code,product.revision),db.prepare('INSERT INTO epi_movements (id,code,kind,delta,quantity,recipient,note,author,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM epi_products WHERE code=? AND revision=?)').bind(crypto.randomUUID(),code,kind,delta,after,recipient,note,gate.user!.displayName,now,code,product.revision+1)]);if(!result[0].meta.changes||!result[1].meta.changes)return error('Stock modifié simultanément. Rechargez et recommencez.',409);return Response.json({ok:true,quantity:after});
}catch(e){console.error(e);return error('Enregistrement impossible. Réessayez.',503)}}
