import {database,bucket} from '@/db/raw';
import {checkOrigin,requireRole} from '@/lib/access';

const locales=new Set(['fr','en','de','it','es']);
const noStore={'Cache-Control':'private, no-store'};
const error=(message:string,status=400)=>Response.json({error:message},{status,headers:noStore});
async function boundedImage(req:Request){const reader=req.body?.getReader();if(!reader)return null;const chunks:Uint8Array[]= [];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>2_000_000){await reader.cancel();return null}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return bytes}
type Profile={locale:string;photo_key:string;photo_mime:string;photo_updated_at:string};
async function profile(userId:string){return database().prepare('SELECT locale,photo_key,photo_mime,photo_updated_at FROM user_profiles WHERE user_id=?').bind(userId).first<Profile>()}
function publicProfile(row:Profile|null){return {locale:row?.locale||'fr',photoUrl:row?.photo_key?'/api/profile/photo?v='+encodeURIComponent(row.photo_updated_at):''}}

export async function GET(req:Request){try{const gate=await requireRole(req);if(gate.error)return gate.error;return Response.json(publicProfile(await profile(gate.user!.id)),{headers:noStore})}catch{return error('Profil indisponible.',503)}}

export async function POST(req:Request){try{if(!checkOrigin(req))return error('Origine non autorisée.',403);const gate=await requireRole(req);if(gate.error)return gate.error;const body=await req.json() as {locale?:unknown};if(!body||typeof body.locale!=='string'||!locales.has(body.locale))return error('Langue invalide.');await database().prepare('INSERT INTO user_profiles(user_id,locale) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET locale=excluded.locale').bind(gate.user!.id,body.locale).run();return Response.json(publicProfile(await profile(gate.user!.id)),{headers:noStore})}catch{return error('Enregistrement impossible.',503)}}

export async function PUT(req:Request){try{if(!checkOrigin(req))return error('Origine non autorisée.',403);const gate=await requireRole(req);if(gate.error)return gate.error;if(Number(req.headers.get('content-length')||0)>2_000_000)return error('Photo trop volumineuse.',413);const contentType=req.headers.get('content-type')?.split(';')[0];if(!['image/jpeg','image/png','image/webp'].includes(contentType||''))return error('Choisissez une image JPEG, PNG ou WebP.');const bytes=await boundedImage(req);if(!bytes?.length)return error('La photo doit faire au maximum 2 Mo.',413);const jpeg=bytes.length>=3&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const png=bytes.length>=8&&bytes.slice(0,8).every((n,i)=>n===[137,80,78,71,13,10,26,10][i]);const webp=bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';const mime=jpeg?'image/jpeg':png?'image/png':webp?'image/webp':'';if(mime!==contentType)return error('Format de photo invalide.');const old=await profile(gate.user!.id),key='profiles/'+gate.user!.id+'/'+crypto.randomUUID(),stamp=new Date().toISOString();await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});try{await database().prepare('INSERT INTO user_profiles(user_id,photo_key,photo_mime,photo_updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET photo_key=excluded.photo_key,photo_mime=excluded.photo_mime,photo_updated_at=excluded.photo_updated_at').bind(gate.user!.id,key,mime,stamp).run()}catch(e){await bucket().delete(key);throw e}if(old?.photo_key)await bucket().delete(old.photo_key).catch(()=>{});return Response.json(publicProfile(await profile(gate.user!.id)),{headers:noStore})}catch{return error('Téléversement impossible.',503)}}

export async function DELETE(req:Request){try{if(!checkOrigin(req))return error('Origine non autorisée.',403);const gate=await requireRole(req);if(gate.error)return gate.error;const old=await profile(gate.user!.id);await database().prepare("UPDATE user_profiles SET photo_key='',photo_mime='',photo_updated_at='' WHERE user_id=?").bind(gate.user!.id).run();if(old?.photo_key)await bucket().delete(old.photo_key).catch(()=>{});return Response.json(publicProfile(await profile(gate.user!.id)),{headers:noStore})}catch{return error('Suppression impossible.',503)}}
